package de.dlr.shepard.plugin;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.time.Duration;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;

/**
 * PM1f — renderer tests for {@link SidecarsAssembler}.
 *
 * <p>The assembler is deterministic + stateless — these tests pin
 * the exact compose-v3 shape it emits so plugin authors can rely on
 * stable byte-level output across runs.
 */
class SidecarsAssemblerTest {

  private final SidecarsAssembler assembler = new SidecarsAssembler();

  @Test
  void emptySpecsListProducesEmptyString() {
    assertThat(assembler.assembleComposeSnippet(List.of())).isEmpty();
  }

  @Test
  void nullSpecsListThrows() {
    assertThatThrownBy(() -> assembler.assembleComposeSnippet(null))
      .isInstanceOf(NullPointerException.class);
  }

  @Test
  void singleSpecRendersServicesHeaderAndServiceName() {
    String out = assembler.assembleComposeSnippet(List.of(minimalGarage()));
    assertThat(out).startsWith("# Generated by SidecarsAssembler");
    assertThat(out).contains("services:\n");
    assertThat(out).contains("  shepard-garage:\n");
    assertThat(out).contains("    image: dxflrs/garage:v1.0.1\n");
  }

  @Test
  void portRenderingIncludesRoleAsYamlComment() {
    String out = assembler.assembleComposeSnippet(
      List.of(
        new SidecarSpec(
          "garage",
          "dxflrs/garage:v1.0.1",
          List.of(
            new PortSpec(3900, "s3-api"),
            new PortSpec(3902, "web-admin")
          ),
          List.of(),
          Map.of(),
          validHealthcheck(),
          List.of(),
          Map.of()
        )
      )
    );
    assertThat(out).contains("    ports:\n");
    assertThat(out).contains("      - \"3900:3900\"  # s3-api\n");
    assertThat(out).contains("      - \"3902:3902\"  # web-admin\n");
  }

  @Test
  void volumeRenderingProducesTopLevelVolumesBlock() {
    String out = assembler.assembleComposeSnippet(List.of(minimalGarage()));
    assertThat(out).contains("    volumes:\n");
    assertThat(out).contains("      - garage_data:/var/lib/garage\n");
    // top-level volumes: block at the document root so the snippet
    // is a valid standalone docker-compose override.
    assertThat(out).contains("volumes:\n  garage_data:\n");
  }

  @Test
  void envRenderingIsSortedForByteStableOutput() {
    String out = assembler.assembleComposeSnippet(
      List.of(
        new SidecarSpec(
          "garage",
          "dxflrs/garage:v1.0.1",
          List.of(),
          List.of(),
          Map.of(
            "GARAGE_S3_API_BIND_ADDR",
            "0.0.0.0:3900",
            "GARAGE_RPC_SECRET",
            "{{generate:hex:64}}",
            "GARAGE_WEB_BIND_ADDR",
            "0.0.0.0:3902"
          ),
          validHealthcheck(),
          List.of(),
          Map.of()
        )
      )
    );
    int rpc = out.indexOf("GARAGE_RPC_SECRET");
    int s3 = out.indexOf("GARAGE_S3_API_BIND_ADDR");
    int web = out.indexOf("GARAGE_WEB_BIND_ADDR");
    assertThat(rpc).isGreaterThan(0);
    assertThat(rpc).isLessThan(s3);
    assertThat(s3).isLessThan(web);
  }

  @Test
  void envRenderingPreservesTemplatingPlaceholdersVerbatim() {
    String out = assembler.assembleComposeSnippet(List.of(minimalGarage()));
    assertThat(out).contains("GARAGE_RPC_SECRET: \"{{generate:hex:64}}\"");
  }

  @Test
  void healthcheckRenderingMapsToComposeV3Shape() {
    String out = assembler.assembleComposeSnippet(List.of(minimalGarage()));
    assertThat(out).contains("    healthcheck:\n");
    assertThat(out)
      .contains("      test: [\"CMD-SHELL\", \"curl -fsS http://localhost:3900/health\"]\n");
    assertThat(out).contains("      interval: 30s\n");
    assertThat(out).contains("      timeout: 10s\n");
    assertThat(out).contains("      retries: 3\n");
  }

  @Test
  void postInitRenderedAsNumberedComments() {
    String out = assembler.assembleComposeSnippet(List.of(minimalGarage()));
    assertThat(out)
      .contains("    # post-init (run by operator-side bootstrap after healthy):\n");
    assertThat(out).contains("    #   [0] /garage layout assign");
    assertThat(out).contains("    #   [3] /garage key new --name shepard-backend");
  }

  @Test
  void backendEnvBindingRenderedAsHintComments() {
    String out = assembler.assembleComposeSnippet(List.of(minimalGarage()));
    assertThat(out)
      .contains("    # backend-env (inject into the shepard backend service):\n");
    assertThat(out).contains("    #   SHEPARD_FILES_S3_BUCKET=shepard-files\n");
    assertThat(out).contains("    #   SHEPARD_FILES_S3_ENDPOINT=http://{{sidecar.host}}:3900\n");
  }

  @Test
  void durationFormattingPrefersMinutesWhenWhole() {
    String out = assembler.assembleComposeSnippet(
      List.of(
        new SidecarSpec(
          "kafka",
          "confluent/kafka:7.6.0",
          List.of(),
          List.of(),
          Map.of(),
          new HealthcheckSpec(
            "kafka-topics --list",
            Duration.ofMinutes(2),
            Duration.ofMinutes(1),
            5
          ),
          List.of(),
          Map.of()
        )
      )
    );
    assertThat(out).contains("interval: 2m\n");
    assertThat(out).contains("timeout: 1m\n");
  }

  @Test
  void multipleSpecsAllRenderedInOrder() {
    SidecarSpec garage = minimalGarage();
    SidecarSpec kafka = new SidecarSpec(
      "kafka",
      "confluent/kafka:7.6.0",
      List.of(new PortSpec(9092, "broker")),
      List.of(new VolumeSpec("kafka_data", "/var/lib/kafka")),
      Map.of(),
      new HealthcheckSpec(
        "kafka-topics --list",
        Duration.ofSeconds(15),
        Duration.ofSeconds(5),
        2
      ),
      List.of(),
      Map.of()
    );
    String out = assembler.assembleComposeSnippet(List.of(garage, kafka));
    int garageIdx = out.indexOf("shepard-garage:");
    int kafkaIdx = out.indexOf("shepard-kafka:");
    assertThat(garageIdx).isPositive();
    assertThat(kafkaIdx).isGreaterThan(garageIdx);
    assertThat(out).contains("  garage_data:\n");
    assertThat(out).contains("  kafka_data:\n");
  }

  @Test
  void noVolumesAcrossAllSpecsOmitsTopLevelVolumesBlock() {
    SidecarSpec noVol = new SidecarSpec(
      "noop",
      "alpine:3.20",
      List.of(),
      List.of(),
      Map.of(),
      validHealthcheck(),
      List.of(),
      Map.of()
    );
    String out = assembler.assembleComposeSnippet(List.of(noVol));
    assertThat(out).doesNotContain("volumes:");
  }

  @Test
  void renderIsByteStableAcrossInvocations() {
    SidecarSpec spec = minimalGarage();
    String first = assembler.assembleComposeSnippet(List.of(spec));
    String second = assembler.assembleComposeSnippet(List.of(spec));
    assertThat(first).isEqualTo(second);
  }

  /** Full-shape Garage spec — mirrors what FileS3PluginManifest declares. */
  private static SidecarSpec minimalGarage() {
    return new SidecarSpec(
      "garage",
      "dxflrs/garage:v1.0.1",
      List.of(
        new PortSpec(3900, "s3-api"),
        new PortSpec(3902, "web-admin")
      ),
      List.of(new VolumeSpec("garage_data", "/var/lib/garage")),
      Map.of(
        "GARAGE_RPC_SECRET",
        "{{generate:hex:64}}",
        "GARAGE_S3_API_BIND_ADDR",
        "0.0.0.0:3900",
        "GARAGE_WEB_BIND_ADDR",
        "0.0.0.0:3902"
      ),
      validHealthcheck(),
      List.of(
        "/garage layout assign ${NODE_ID} -z dc1 -c 1G",
        "/garage layout apply --version 1",
        "/garage bucket create shepard-files",
        "/garage key new --name shepard-backend",
        "/garage bucket allow --read --write shepard-files --key shepard-backend"
      ),
      Map.of(
        "SHEPARD_FILES_S3_ENDPOINT",
        "http://{{sidecar.host}}:3900",
        "SHEPARD_FILES_S3_REGION",
        "garage-region",
        "SHEPARD_FILES_S3_PATH_STYLE",
        "true",
        "SHEPARD_FILES_S3_BUCKET",
        "shepard-files",
        "SHEPARD_FILES_S3_ACCESS_KEY_ID",
        "{{from:postInit.3.access_key_id}}",
        "SHEPARD_FILES_S3_SECRET_ACCESS_KEY",
        "{{from:postInit.3.secret_access_key}}"
      )
    );
  }

  private static HealthcheckSpec validHealthcheck() {
    return new HealthcheckSpec(
      "curl -fsS http://localhost:3900/health",
      Duration.ofSeconds(30),
      Duration.ofSeconds(10),
      3
    );
  }
}
