quarkus.http.test-port=8083
quarkus.http.test-ssl-port=8446
quarkus.http.test-timeout=10s
quarkus.http.root-path=/shepard/api
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,HEAD,OPTIONS,DELETE,PUT
quarkus.http.cors.headers=Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization,X-API-KEY

quarkus.test.continuous-testing=enabled
quarkus.test.display-test-output=true
quarkus.test.type=quarkus-test
quarkus.shutdown.timeout=PT10S

# Logging
quarkus.log.level=INFO
quarkus.log.min-level=DEBUG
quarkus.log.file.enable=true
quarkus.log.file.path=logs/shepard.log
# https://docs.redhat.com/en/documentation/red_hat_build_of_quarkus/3.2/html/logging_configuration/logging-configuration#root-logger-configuration
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c] (%t) %s%e%n
quarkus.log.file.level=INFO
quarkus.log.file.rotation.max-backup-index=10
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd

# Influx DB
influx.host=[::1]:8086
influx.username=influx
influx.password=shepard

# Neo4j
neo4j.host=[::1]:7687
neo4j.username=neo4j
neo4j.password=shepard

# MongoDB
mongo.host=[::1]:27017
mongo.username=mongo
mongo.password=shepard
mongo.authDB=admin
# configure the mongoDB client for a replica set of two nodes
quarkus.mongodb.connection-string=mongodb://mongo:shepard@[::1]:27017
mp.openapi.extensions.smallrye.operationIdStrategy=METHOD
