quarkus.http.test-port=8083
quarkus.http.test-ssl-port=8446
quarkus.http.test-timeout=10s
quarkus.test.continuous-testing=enabled
quarkus.test.display-test-output=true
quarkus.test.type=quarkus-test
quarkus.log.level=INFO
quarkus.http.root-path=/shepard/api
quarkus.shutdown.timeout=PT10S
quarkus.live-reload.instrumentation=true
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,HEAD,OPTIONS,DELETE,PUT
quarkus.http.cors.headers=Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization,X-API-KEY
influx.host=[::1]:8086
influx.username=influx
influx.password=shepard
neo4j.host=[::1]:7687
neo4j.username=neo4j
neo4j.password=shepard
mongo.host=[::1]:27017
mongo.username=mongo
mongo.password=shepard
mongo.authDB=admin
# configure the mongoDB client for a replica set of two nodes
quarkus.mongodb.connection-string=mongodb://mongo:shepard@[::1]:27017
mp.openapi.extensions.smallrye.operationIdStrategy=METHOD
