resourcePackages:
  - de.dlr.shepard.endpoints
prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    version: ${project.version}
    title: ${project.name}
  servers:
    - url: /shepard/api
      description: shepard backend
  components:
    securitySchemes:
      bearer:
        type: http
        scheme: bearer
        bearerFormat: JWT
      apikey:
        type: apiKey
        in: header
        name: X-API-KEY
  security:
    - bearer: []
    - apikey: []
