ifndef::imagesdir[:imagesdir: ../../images]

=== Authorization

==== Requirements & Constraints

- The backend can verify the identity of users
- Users are uniquely identified in the backend by usernames
- The backend can easily verify whether a user has permissions to a particular object
- This check is quick and easy to perform, so there is no noticeable delay
- Records created before the introduction of permissions can still be used
- Permissions may only be configured for "top-level" entities, e.g. collections, containers, userGroups.
Subordinate entities like data objects inherit their permissions from the superior entity.
In case of versioning all versions of a collection share the same permissions.

==== Permissions

The permissions of a top level entity describe who:

1. owns the entity (a single user)
2. may manage the entity (update the permissions) (a list of users)
3. may edit/write the entity (a list of users or user groups)
4. may read the entity (a list of users or user groups)

These permissions build on top of each other.
That means:

- everybody with write permissions is allowed to read
- everybody with manage permissions is allowed to write
- the owner is allowed to perform all operations

The owner is a single user.
Entities without owner belong to everyone (backwar compatibility).

In addition, there is a general permission type defined for each entity which can be one of `Public`, `PublicReadable` or `Private`.

`Public` means all authenticated users have permissions to read and write.
`PublicReadable` means all authenticated users can read the entity.
`Private` means only the users explicitly granted access are allowed to interact with the entity.

Newly created objects have the creator set as owner and the permissionType set to `Private`.

==== Available Endpoints

An endpoint `/.../<id>/permissions` can be used to manage permissions of an object.
Allowed methods are `GET` and `PUT`.
Permissions follow the following format:

```json
{
  "owner": "<user-name>",
  "permissionType": "<Public|PublicReadable|Private>",
  "reader": [
    "<user-name>"
  ],
  "writer": [
    "<user-name>"
  ],
  "readerGroupIds": [
    0
  ],
  "writerGroupIds": [
    0
  ],
  "manager": [
    "<user-name>"
  ]
}
```

An endpoint `/.../<id>/roles` can be used to check which operations the requesting user may perform on the entity.
It is available for all entities for all authenticated users.
The response looks like the following and describes which operations the user may perform:

```json
{
  "owner": "<boolean>",
  "manager": "<boolean>",
  "writer": "<boolean>",
  "reader": "<boolean>"
}
```
