ifndef::imagesdir[:imagesdir: ../../images]

=== Authentication

We decided to rely on external identity providers with shepard.
This allows us to use existing user databases such as Active Directories.
In addition, we do not have to implement our own user database.
Most shepard instances use keycloak as their identity provider.
However, we want to be compatible with the OIDC specification so that other OIDC identity providers could work with shepard.

The `JWTFilter`, which filters every incoming request, implements authentication by validating the submitted JWT.
For this purpose, the JWT is decoded with a statically configured public key.
OIDC allows the key to be obtained dynamically from the identity provider.
However, we decided that a static configuration is more secure and has practically no disadvantages.
The attack vector we are trying to mitigate here is that an attacker gains access to the infrastructure and somehow injects their own public key, which shepard would accept from that point on.

If configured, the system also checks whether certain roles are present among the JWT's `realm_access.roles` attribute.
This can be done by configuring the variable `OIDC_ROLES` for the backend.
The backend then only accepts JWTs with the specified role.
This enables the reuse of existing identity providers for different shepard instances, each of which can be accessed by different user groups.
For example, if someone uses an Active Directory for Keycloak to fetch users from, then Keycloak could add specific roles to people based on AD groups they belong to.

In addition to OIDC, we also allow authentication via API keys.
Shepard generates these keys itself and stores them in our internal database.
Although the API keys are also JWTs, we have to check whether the specified key can be found in our database.
Otherwise, we would continue to accept keys that have already been deleted, which is not the intended behavior.

==== Using Nuxt-Auth

To be able to authenticate in the frontend and acquire a JWT token, we use link:https://auth.sidebase.io/[@sidebase/nuxt-auth] as our authentication module in the frontend.

===== Adjust Nuxt config

The file `nuxt.config.ts` holds configuration for the application.

That is where we need to add the `@sidebase/nuxt-auth` module to the modules array.

Then, in the same config object, populate the `auth` configuration.

The `auth` config holds details about our authentication provider and session refresh management.

Add the `@sidebase/nuxt-auth` module to the modules array and enable the `auth` configuration in `nuxt.config.ts`

```typescript
export default defineNuxtConfig({
  modules: [
    "@sidebase/nuxt-auth",
    ...,
  ],

  auth: {
    isEnabled: true,
    provider: {
      type: "authjs",
      ...,
    },
    sessionRefresh: {...},
  },
  ...,
})
```

Details about the auth config attributes could be found in the link:https://auth.sidebase.io/guide/application-side/configuration[docs]

===== Add environment variables

A couple of env variables are needed for this to work.
These variables are documented in the setup of the frontend.

To be able to make use of them we should list them in the `runtimeConfig`.

```typescript
export default defineNuxtConfig({  runtimeConfig: {
  authSecret: "",
  oidcClientId: "",
  oidcIssuer: "",
  }
})
```

===== Configure the authentication provider

After the configuration adjustment mentioned previously, an automatically generated auth path is created `/api/auth`.

Which is where we should create our OIDC provider config under `/src/server/api/auth/[...].ts`.

```typescript
export default NuxtAuthHandler({
  secret: runtimeConfig.authSecret,
  providers: [
    {
      id: "oidc",
      name: "OIDC",
      type: "oauth",
      ...,
    },
  ],
})
```

Details about the provider config can be found in the link:https://next-auth.js.org/configuration/providers/oauth#using-a-custom-provider[NextAuth docs]

After this setup we should be able to authenticate using the specified OIDC provider.

To handle token and session refresh we can use the `jwt()` and `session()` callbacks to control the behavior in the same `NuxtAuthHandler`.

The `jwt()` callback handles three different scenarios:

1. The user initially signed in by clicking on the `Sign In` button. Then, the `jwt()` function retrieves a `token` and an `account` object. Whereas the received `token` object looks like this:
+
```typescript
{ 
  name: 'user',
  email: 'user@testmail.xyz',
  picture: undefined,
  sub: 'user'
}
```
and the `account` object looks like this:
+
```typescript
{ 
  provider: 'oidc',
  type: 'oauth',
  providerAccountId: 'user',
  access_token: '[...]',
  expires_at: 1736171866,
  refresh_expires_in: 1800,
  refresh_token: '[...]',
  token_type: 'Bearer',
  id_token: '[...]',
  'not-before-policy': 0,
  session_state: 'UUID',
  scope: '[...]'
}
```
The `jwt()` callback returns a new `token` object with information from the `account` object.
This new token object is then used for the other scenarios too and looks like this:
+
```typescript
interface JWT {
  expiresAt: number;
  accessToken: string;
  idToken: string;
  refreshToken: string;
  error?: "RefreshTokenError";
  userId: string;
}
```

2. The second scenario occurs when the session is refreshed either by reloading the page or automatically according to the refresh interval specified by the `enablePeriodically` setting in the `nuxt.config.ts`. If the session is refreshed and the authentication key is still active, then the currently used `token` object is returned. This scenario therefore occurs when the following condition is true: 
+
```typescript
Date.now() < (token.expiresAt * 1000 - REFRESH_INTERVAL * 2)
```

3. The third scenario occurs when the condition of scenario 2 is false. This implies that the access token needs to be refreshed by providing the current access token and the current refresh token to the OIDC provider.
In this scenario we utilize the `token` object that was initialized in the first scenario, which is extended by the Nuxt auth with a couple of fields, like `iat` or `exp`. The `token` object that is used in this scenario looks like this:
+
```typescript
{ 
  accessToken: '[...]',
  idToken: '[...]',
  expiresAt: 1736173016,
  refreshToken: '[...]',
  userId: 'user',
  iat: 1736172865,
  exp: 1736174665,
  jti: 'UUID'
}
```
The `iat` and `exp` fields are specified by the official RFC 7519 (JWT) and are automatically set by Nuxt. For example, the `exp` field is calculated by adding `maxAge` config from the `NuxtAuthHandler` to the `iat` value (issued at). But we do not actually rely on these fields.
+
In this third scenario a new refresh token is requested from the OIDC provider. If there is an error due to an expired refresh token, the error is directly thrown. If everything is ok, the current `token` object is updated with a new `expiresAt` value, a new access token and if possible, a new refresh token. Then this new `token` object is returned.

===== Authentication Middleware

The global authentication is handled by a custom authentication middleware, which is defined in `middleware/authentication.global.ts`.
This middleware protects most frontend pages (i.e., `/collections`) and therefore requires an authenticated user session before it can be shown. 
If the user is not authenticated and therefore does not an authenticated user session, the middleware redirects the user to the OIDC's login page.
When the user successfully logged in, they are redirected to the protected page, which now can be opened by the user.

Not all pages need to be protected. 
Pages that should not require an authenticated user session can be configured in the `middleware/publicEndpoints.ts` file.
This defines a list of endpoints that do not require a logged in user, i.e., the shepard frontpage (`/`).

As long as the user stays on the page and has a network connection to the OIDC provider, the user session is refreshed infinitely.
When the user closes the browser or tab of the frontend, the session cannot be refreshed and the access token expires.
In this case an error message should be shown (Invalid Authentication), which requires the user to either reload the page, click on the sign-in button or redirect to a different protected page to trigger the sign-in that creates a new user session.