ifndef::imagesdir[:imagesdir: ../../images]

=== Configuration

==== Backend (Quarkus)

This section is a short summary of link:https://quarkus.io/guides/config[this page].

===== Setting Properties

Quarkus reads configuration properties from several sources.
More information on the sources and how they override each other can be found link:https://quarkus.io/guides/config-reference#configuration-sources[here].

We define a standard value for most properties under `src/main/resources/application.properties`.
In a dev environment, they can be overridden using a `.env` file.
In a dockerized setup they can be overridden by providing environment variables to the service.

To support administrators, relevant configuration options are documented in link:https://gitlab.com/dlr-shepard/shepard/-/blob/main/infrastructure/env.example[infrastructure/env.example] and link:https://gitlab.com/dlr-shepard/shepard/-/blob/main/infrastructure/README.md[infrastructure/README.md].

===== Reading Properties

Poperties can be either link:https://quarkus.io/guides/config#inject-the-configuration[injected] or link:https://quarkus.io/guides/config#programmatically-access-the-configuration[accessed programatically].

===== Conditionally Excluding Beans at Buildtime

Quarkus allows us to conditionally exclude beans at runtime.
For example, the endpoints of an experimental feature can be enabled or disabled at build time to be included in dev builds but excluded in release builds.

For example, the `ExperimentalTimeseriesRest` can have a `@IfBuildProperty` annotation like this:

```java
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
@Path("experimental-" + Constants.TIMESERIES_CONTAINERS)
@RequestScoped
@IfBuildProperty(name = "shepard.experimental-timeseries.enabled", stringValue = "true")
public class ExperimentalTimeseriesRest {
  ...
}
```

In this example the endpoints are only available when `shepard.experimental-timeseries.enabled` was `true` at build time.

Using this we can enable the variable locally and for dev builds to make sure the experimental code is not deployed to production.

[CAUTION]
Don't mistake the build profiles `dev` and `prod` for the profiles for dev and prod images.
To have our dev environment as close to the production environment as possible, the dev images are also built using the `prod` profile.

See link:https://quarkus.io/guides/cdi-reference#enable_build_properties[here] for more information.

==== Frontend (Nuxt)

This section is a short summary of link:https://nuxt.com/docs/getting-started/configuration[this page].

===== Setting properties

We define environment variables in the Nuxt config like this:

```typescript
export default defineNuxtConfig({  runtimeConfig: {
  // A value that should only be available on server-side
  apiSecret: '123',
  // Values that should be available also on client side
  public: {
    apiBase: '/api'
  }
}})
```

These values can be overridden by a `.env` file like this:

```
NUXT_API_SECRET=api_secret_token
NUXT_PUBLIC_API_BASE=https://nuxtjs.org
```

In order to ease the configuration we provide a `env.example` file with all relevant variables.
That file can be copied to `.env` and filled with the appropriate values.

===== Reading Properties

Properties can be accessed using `useRuntimeConfig()`.
