ifndef::imagesdir[:imagesdir: ../../images]

[[dependency-updates,Dependency Updates]]
=== Dependency Updates

Dependencies of shepard are updated regularly.
To automate most of this, we use link:https://docs.renovatebot.com/[renovate] in GitLab.
The configuration for the repository is located at link:https://gitlab.com/dlr-shepard/shepard/-/blob/main/renovate.json?ref_type=heads[renovate.json].
In order for the config to be active, it has to be present at the default branch of the repository (main).
The renovate runner is located in this (private) repository: link:https://gitlab.com/dlr-shepard/renovate-runner[].

The developer team is responsible of regularly handling the pull requests opened by renovate.
This should happen once a month directly after creating a monthly release.
As a reminder, monthly update tickets are part of the sprints.

==== Performing Updates

We handle the merge requests opened by renovate by performing the following steps for each update:

1. reading the change logs of the dependency
2. testing if everything is still working
3. applying necessary changes if they are not too much effort
4. merging the branch *or* <<suspending-an-update, suspending the update>>.

Also, the dependencies in package-lock.json should be updated.
This is done by running `npm update` in the top level directory.

[[suspending-an-update]]
==== Suspending an Update

In case we could not perform the update it should be suspended and documented in the list of <<suspended-updates, suspended updates>>.
The reason can either be too much effort (we create a new story for that update) or that the update is not possible or feasible right now.

This can be done by excluding the library or specific version in the link:https://gitlab.com/dlr-shepard/shepard/-/blob/main/renovate.json?ref_type=heads[renovate config].
Afterwards the config needs to be merged to main with the following commands:

```sh
git checkout main
git cherry-pick <commit-hash>
```

Afterwards the merge request can be closed.

==== Abandoned dependency updates

Sometimes, when the configuration changes or dependency updates were done without renovate, the bot might abandon a merge request.
In this case the merge request is not automatically closed and has to be closed manually.
The corresponding branch must also be deleted manually to keep things clean.

[[suspended-updates]]
===== Suspended Updates

[cols="1,1"]
|===
|Package and version|Issue that blocks an update

|tomcat<11
|v11 is still a pre-release

|influxdb<=1.8
|V2 introduces major breaking changes.
Since we want to move to timescaleDB anyways, we disregard any new updates that require some kind of migration effort.

|chronograf<1.10
|The container cannot be started with v1.10. We expect to move away from influxdb in the future, so we will stick with v1.9 for the time being.

|neo4j<5
|V5 introduces major breaking changes

|mongo<5
|no real reason, there are some major changes, but nothing serious

|vue<3
|not compatible with bootstrap v4

|vue-router<4
|not compatible with vue v2

|vuex<4
|not compatible with vue v2

|bootstrap<5
|v5 has no vue integration

|portal-vue<3
|needed for bootstrap-vue

|typescript<5
|not compatible with vue v2

|@vue/tsconfig<2
|not compatible with vue v2

|vue-tsc<2.0.24
|

|eslint<9
|`--ext` option is not supported and the current eslintrc file structure is not supported anymore.

|@vue/eslint-config-prettier<10
|Has peer dependency to current version of eslint

|@vue/eslint-config-typescript<14
|Has peer dependency to current version of eslint

|neo4j-ogm<4
|v5 is not compatible with neo4j v4

|jjwt<0.12
|v0.12.x introduces a series of breaking changes in preparation for v1.0. It is recommended to stay on v0.11 until v1.0 is finished to fix all changes at once.

|junit-jupiter<5.11
|Not possible atm because parametrized tests in combination with CsvSource do not work any longer. We will wait for the next version.
|===
