ifndef::imagesdir[:imagesdir: ../../images]

=== Testing Strategy

To automatically test shepard, several strategies are used.
They are described in this section.

==== Unit Tests

We use junit5 for unit testing parts of our backend code.
We aim to cover everything except endpoints by our unit tests.

===== @QuarkusTest with Running Databases

For special cases, we use tests with the `@QuarkusTest` annotation to test beans of a running quarkus instance with running databases.
This is especially used for behaviour strongly coupled to databases, in order to reduce the need for mocking and get more precise test results.
They are executed in a seperate job in the pipeline in order to provide the needed databases.

==== Integration Tests

To test the overall functionality of the backend we test our http endpoints with integration tests using `@QuarkusIntegrationTest`.
In the pipeline, the tests are executed on a quarkus instance based on the build artifact built in the pipeline.

===== Integration Tests utilizing External REST APIs

Some of the integration tests in the backend rely on an external REST API.
One example are the integration tests that utilize semantic annotations like the `CollectionSearcherIT`.
This test includes creating a semantic repository with an external ontology service and executing requests against this endpoint.

This introduces an external dependency to our integration tests, which we cannot control.
If the external service is not available, the HTTP connection results in a timeout and the whole integration test fails, even though this is not related to our backend code.
Since we want to test if the health check to the external service works, we cannot replace the health check function with a mocked version of this function.
By introducing https://wiremock.org/[WireMock], it is possible to mock the HTTP response itself.

WireMock is a testing framework to map HTTP responses to specific HTTP requests.
WireMock acts as a simple HTTP server in the background that allows defining rules to match on HTTP requests with pre-defined HTTP responses.
For example, this code snippet in the `WireMockResource.java` mocks the behavior for the health check against an external ontology service:
```Java
wireMockServer.stubFor(
      // stub for health check on: https://dbpedia.org/sparql/
      get(urlPathEqualTo("/sparql"))
        .withQueryParam("query", equalTo("ASK { ?x ?y ?z }"))
        .willReturn(aResponse().withStatus(200).withBody("{ \"head\": {\"link\": []  }, \"boolean\": true }"))
    );
```
The rules in this snippet are defined as the following:
for every GET request to `localhost:PORT/sparql` with the query parameter `query=ASK { ?x ?y ?z }`, the WireMock HTTP server will return a HTTP response with code 200, containing this JSON string in its body `"{ \"head\": {\"link\": []  }, \"boolean\": true }"`.

Since we are using Quarkus as our backend framework, we utilize the https://docs.quarkiverse.io/quarkus-wiremock/0.x/index.html[Quarkus WireMock Extension].
This extensions allows an easier integration into an existing Quarkus application.
It directly supports injection, to inject a WireMock server in an integration test.
Generally, injection is our preferred way to initialize objects.

However, injection is not used in our current implementation of WireMock mocking due to limitations of our concrete scenario, i.e. usage in static functions, where injection is not possible.
Therefore, we utilize WireMock in a static approach.

A proper way to integrate WireMock into a Quarkus integration test is described in the https://docs.quarkiverse.io/quarkus-wiremock/0.x/index.html[extension's introduction page] and also by the official https://quarkus.io/guides/getting-started-testing#quarkus-test-resource[Quarkus guide for test resources].

WireMock is a strong tool and provides many options to mock complex web services.
To name only a few possibilities with WireMock, you are able to use https://wiremock.org/docs/response-templating/[response templates], it provides https://wiremock.org/docs/proxying[proxying] to forward specific requests, and it supports multiple protocols like gRPC,GraphQL, HTTPS and JWT.

==== Generic Endpoints Integration Tests
In order to perform endpoints tests we have implemented `GenericEndpointsIT` which will perform parametrized test on all the provided endpoints.
This generic test will ensure the validity checks on parameters, perform access control checks, and expected status codes.
Currently it is testing the below cases:

* Requests with valid path
* Requests with invalid path
* Requests with valid body (POST, PUT)
* Requests with invalid body (POST, PUT)
* Requests for not found resource
* Unauthorized access
* Unauthorized public access (no user)

Test cases can be added to `loadTestCases` method by providing the inputs and expected outputs and codes.
Every endpoint test case has the following properties:
```Java
String url; // The resource path, example: /collections/{collectionId}/roles
List<String> methods; // http methods to test, example: ["GET", "PUT"]
Map<String, String> validPathParams; // Valid path parameters that will pass through, example: {"collectionId": "123"}
Map<String, String> invalidPathParams; // Invalid path parameters that will not pass through, example: {"collectionId": "abc"}
Map<String, String> notFoundPathParams; // Path parameter to not existing resource, example: {"collectionId": "999999"}
/*
 Expected status codes for every method, example:
 "GET": { "valid": 200, "invalid": 403, "unauthorized": 403, "unauthenticated": 401, "notFound": 404 },
 "PUT": { "valid": 200, "invalid": 400, "unauthorized": 403, "unauthenticated": 401, "notFound": 404 }
*/
Map<String, Map<String, Integer>> expectedStatusCodes;
Map<String, Object> requestBody;// Valid request body to be used with PUT and POST methods, example: {"name", "A collection"}
Map<String, Object> invalidRequestBody;// Invalid request body to be used with PUT and POST methods, example: {"someKey", "some value"}
```

For reference refer to the sample tests in the resource file `generic_endpoints_test_cases.json`.

==== Load and Performance Tests
We are using https://k6.io[grafana k6] for load and performance tests.
They are in the directory `load-tests` and are written in TypeScript.
Tests can only be triggered on a local development computer but can be configured to use the local or the dev environment.

===== Configuration
* Create a file under `load-tests/mount/settings.json`
* Copy contents from `load-tests/mount/settings.example.json`
* Adapt configuration settings as needed
* run `npm install` in `load-tests/`

===== Execute tests
There is a shell script `run-load-test.sh` that can be used to execute load tests.
It takes the test file to execute as first parameter.

```Javascript
./run-load-test.sh src/collections/smoke-test.ts
```

===== Good to know
* `Webpack` is used for bundling all dependencies into the test file.
* `Webpack` uses `ts-loader` to transpile TypeScript to JavaScript.
* K6 does not use a node environment.
Therefore some functionality is not available.
* `Webpack.config.js` identifies entry points (tests) dynamically.
All `*.ts` files are added automatically if they are not located in the `utils` folder.
* K6 pushes some metrics to prometheus after test execution.
* To run the tests against a locally run backend on linux, you need to put the ip address into `settings.json`
