image: node:16.16.0

variables:
  SECRET_DETECTION_EXCLUDED_PATHS: "node_modules"
  DOCKER_IMAGE: "${CI_REGISTRY_IMAGE}:latest"
  DS_EXCLUDED_PATHS: "node_modules"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

include:
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml

stages:
  - install
  - test
  - build
  - upload

.version_number:
  script:
    - export VERSION_NUMBER=$(echo ${CI_PIPELINE_CREATED_AT} | cut -d'T' -f 1 | tr - .)

.prepare_npm: &prepare_npm
  - NPM_PACKAGE_NAME=$(node -p "require('./package.json').name")
  - NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")
  - echo //gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN} >> .npmrc

install:
  stage: install
  before_script:
    - *prepare_npm
  script:
    - npm install --progress=false

lint:
  stage: test
  before_script:
    - *prepare_npm
  script:
    - npm install --progress=false
    - npm run lint
  only:
    - branches

build:
  stage: build
  before_script:
    - !reference [.version_number, script]
    - *prepare_npm
  script:
    - npm install --progress=false
    - npm version --no-git-tag-version ${VERSION_NUMBER}
    - npm run type-check
    - npm run build-only
  artifacts:
    paths:
      - dist/

.upload_docker: &upload_docker
  image: docker:latest
  stage: upload
  needs: [build]
  dependencies: [build]
  services:
    - name: docker:dind

upload_docker_dev:
  <<: *upload_docker
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}
    - !reference [.version_number, script]
    - export VERSION_NUMBER=${VERSION_NUMBER}-dev.${CI_PIPELINE_IID}
    - echo ${VERSION_NUMBER}
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${VERSION_NUMBER} -t ${CI_REGISTRY_IMAGE}:dev .
    - docker push ${CI_REGISTRY_IMAGE}:${VERSION_NUMBER}
    - docker push ${CI_REGISTRY_IMAGE}:dev
  only:
    - master

upload_docker:
  <<: *upload_docker
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}
    - !reference [.version_number, script]
    - echo ${VERSION_NUMBER}
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${VERSION_NUMBER} -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:${VERSION_NUMBER}
    - docker push ${CI_REGISTRY_IMAGE}:latest
  only:
    - /^.*-release$/
