image: maven:3-openjdk-11

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
  REPO: shepard
  IMAGE: backend
  OPENAPI_VERSION: 5.3.0
  DOCKER_IMAGE: "${CI_REGISTRY_IMAGE}:latest"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/
    - target/

include:
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

stages:
  - test
  - build
  - build_clients
  - upload
  - deploy

.version_number: &version_number
  - export VERSION_NUMBER=$(echo ${CI_PIPELINE_CREATED_AT} | cut -d'T' -f 1 | tr - .)
  - echo ${VERSION_NUMBER}

format-prettier:
  stage: test
  image: node:14-slim
  before_script:
    - npm install -g prettier
  script:
    - npx prettier --check .

test:
  stage: test
  before_script:
    - *version_number
  script:
    - mvn ${MAVEN_CLI_OPTS} -Drevision=${VERSION_NUMBER}-SNAPSHOT -DskipITs verify -P test
    - cat target/site/jacoco/index.html | grep -oP 'Total.*?([0-9]{1,3})%'
    - ls -hal target
  artifacts:
    when: always
    expire_in: 2 days
    paths:
      - target/jacoco.exec
      - target/surefire-reports/*
      - target/site/jacoco/*
    reports:
      junit:
        - target/surefire-reports/*.xml

integration-test:
  stage: test
  before_script:
    - *version_number
  variables:
    NEO4J_AUTH: neo4j/shepard
    MONGO_INITDB_ROOT_USERNAME: mongo
    MONGO_INITDB_ROOT_PASSWORD: shepard
    MONGO_INITDB_DATABASE: test
    INFLUXDB_ADMIN_USER: influx
    INFLUXDB_ADMIN_PASSWORD: shepard
  services:
    - name: neo4j:latest
      alias: neo4j
    - name: mongo:latest
      alias: mongodb
    - name: influxdb:1.8
      alias: influxdb
  script:
    - mvn ${MAVEN_CLI_OPTS} -Drevision=${VERSION_NUMBER}-SNAPSHOT -DskipUTs verify -P test
    - ls -hal target
  artifacts:
    when: always
    expire_in: 2 days
    paths:
      - target/tomcat9x-logs/*
      - target/failsafe-reports/*
    reports:
      junit:
        - target/failsafe-reports/*.xml

site:
  stage: build
  needs: [test]
  dependencies: [test]
  before_script:
    - *version_number
  script:
    - ls -hal target
    - mvn ${MAVEN_CLI_OPTS} -Drevision=${VERSION_NUMBER}-SNAPSHOT site -P test
    - ls -hal target/site
  artifacts:
    when: always
    expire_in: 2 days
    paths:
      - target/site/*

coverage:
  stage: build
  image: haynes/jacoco2cobertura:latest
  needs: [test]
  dependencies: [test]
  script:
    - ls -hal target/site/jacoco
    # convert report from jacoco to cobertura
    - python /opt/cover2cover.py target/site/jacoco/jacoco.xml src/main/java > target/site/cobertura.xml
    # read the <source></source> tag and prepend the path to every filename attribute
    - python /opt/source2filename.py target/site/cobertura.xml
  artifacts:
    expire_in: 2 days
    reports:
      cobertura: target/site/cobertura.xml

build:
  stage: build
  before_script:
    - *version_number
  script:
    - mvn ${MAVEN_CLI_OPTS} -Drevision=${VERSION_NUMBER}-SNAPSHOT -DskipTests package -P prod
  artifacts:
    when: always
    expire_in: 2 days
    paths:
      - target/shepard.war
      - target/openapi/*

upload_docker:
  image: docker:latest
  stage: upload
  needs: [build]
  dependencies: [build]
  services:
    - name: docker:dind
  before_script:
    - *version_number
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}
    - docker info
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${VERSION_NUMBER} -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:${VERSION_NUMBER}
    - docker push ${CI_REGISTRY_IMAGE}:latest
  only:
    refs:
      - /^.*-release$/

build_pythonclient:
  stage: build_clients
  needs: [build]
  dependencies: [build]
  before_script:
    - *version_number
    - wget -nv https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/${OPENAPI_VERSION}/openapi-generator-cli-${OPENAPI_VERSION}.jar -O openapi-generator-cli.jar
  script:
    - java -jar openapi-generator-cli.jar generate -i target/openapi/openapi.json -g python-legacy -o clients/python -p=packageName=shepard_client,packageVersion=${VERSION_NUMBER}
  artifacts:
    expire_in: 2 days
    paths:
      - clients/python

upload_pythonclient:
  stage: upload
  image: python:3.9-slim
  needs: [build_pythonclient]
  dependencies: [build_pythonclient]
  before_script:
    - python3 -m pip install wheel setuptools twine
  script:
    - cd clients/python
    - python3 setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi --disable-progress-bar dist/*
  only:
    refs:
      - /^.*-release$/

build_typescriptclient:
  stage: build_clients
  needs: [build]
  dependencies: [build]
  before_script:
    - *version_number
    - wget -nv https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/${OPENAPI_VERSION}/openapi-generator-cli-${OPENAPI_VERSION}.jar -O openapi-generator-cli.jar
  script:
    - java -jar openapi-generator-cli.jar generate -i target/openapi/openapi.json -g typescript-fetch -o clients/typescript -p=npmName=@dlr-shepard/shepard-client,npmRepository=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/,npmVersion=${VERSION_NUMBER},supportsES6=true,typescriptThreePlus=true
  artifacts:
    expire_in: 2 days
    paths:
      - clients/typescript

upload_typescriptclient:
  stage: upload
  image: node:14-slim
  needs: [build_typescriptclient]
  dependencies: [build_typescriptclient]
  before_script:
    - node -v
    - npm -v
    - cd clients/typescript
    - touch .npmrc
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - echo "${CI_API_V4_URL#http*:}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}" >> .npmrc
  script:
    - npm install
    - npm run build
    - npm publish
  only:
    refs:
      - /^.*-release$/

build_javaclient:
  stage: build_clients
  needs: [build]
  dependencies: [build]
  before_script:
    - *version_number
    - wget -nv https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/${OPENAPI_VERSION}/openapi-generator-cli-${OPENAPI_VERSION}.jar -O openapi-generator-cli.jar
  script:
    - java -jar openapi-generator-cli.jar generate -i target/openapi/openapi.json -g java -o clients/java/client -p=apiPackage=de.dlr.shepard.client.java.api,modelPackage=de.dlr.shepard.client.java.model,artifactId=shepard-client,groupId=de.dlr.shepard.client.java,parentGroupId=de.dlr.shepard.client.java,parentArtifactId=de.dlr.shepard.client.java,parentVersion=1.0.0-SNAPSHOT,artifactVersion=${VERSION_NUMBER}-SNAPSHOT
  artifacts:
    expire_in: 2 days
    paths:
      - clients/java

upload_javaclient:
  stage: upload
  needs: [build_javaclient]
  dependencies: [build_javaclient]
  script:
    - cd clients/java
    - mvn ${MAVEN_CLI_OPTS} compile package deploy -s ci_settings.xml
  only:
    refs:
      - /^.*-release$/

pages:
  stage: upload
  needs: [site]
  dependencies: [site]
  script:
    - ls -hal target/site
    - mkdir public
    - mv target/site/* public/
    - echo ${CI_PAGES_DOMAIN}
  artifacts:
    expire_in: 2 days
    paths:
      - public
  only:
    - master
