package de.dlr.shepard.cli;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import picocli.CommandLine;

/**
 * Reads the artefact version from {@code shepard-admin.properties}
 * shipped as a classpath resource at build time. Picocli wires
 * this into {@code --version} via
 * {@code @Command(versionProvider = ...)}.
 *
 * <p>The properties file is generated by the Maven build (see
 * {@code cli/src/main/resources/shepard-admin.properties}) and
 * resolves the {@code ${revision}} placeholder against the pom.
 */
public final class VersionProvider implements CommandLine.IVersionProvider {

  @Override
  public String[] getVersion() throws IOException {
    Properties props = new Properties();
    try (InputStream in = VersionProvider.class.getResourceAsStream("/shepard-admin.properties")) {
      if (in != null) {
        props.load(in);
      }
    }
    String version = props.getProperty("version", "unknown");
    return new String[] { "shepard-admin " + version };
  }
}
