version: "3"

services:
  frontend:
    image: registry.gitlab.com/dlr-shepard/shepard/frontend:dev
    environment:
      - VUE_APP_BACKEND=${VUE_APP_BACKEND-http://localhost:8080/shepard/api}
      - VUE_APP_OIDC_AUTHORITY=${VUE_APP_OIDC_AUTHORITY}
      - VUE_APP_CLIENT_ID=${VUE_APP_CLIENT_ID}
    ports:
      - 8081:80
    restart: unless-stopped

  neo4j:
    extends:
      file: docker-compose.headless.yml
      service: neo4j

  mongodb:
    extends:
      file: docker-compose.headless.yml
      service: mongodb

  mongoexpress:
    extends:
      file: docker-compose.headless.yml
      service: mongoexpress

  influxdb:
    extends:
      file: docker-compose.headless.yml
      service: influxdb

  chronograf:
    extends:
      file: docker-compose.headless.yml
      service: chronograf

  timescaledb:
    extends:
      file: docker-compose.headless.yml
      service: timescaledb

  prometheus:
    extends:
      file: docker-compose.headless.yml
      service: prometheus

  grafana:
    extends:
      file: docker-compose.headless.yml
      service: grafana

networks:
  shepard:
