package de.dlr.shepard.plugin;

import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * PM1f — renders an operator-pasteable {@code docker-compose} snippet
 * from a collection of plugin-declared {@link SidecarSpec}s.
 *
 * <p>This is the <strong>bootstrap-reader</strong> stub: it walks the
 * sidecar declarations of all registered plugins and emits a
 * {@code services:} block an operator can append to their
 * {@code docker-compose.override.yml}. Per
 * {@code aidocs/integrations/93-mffd-import-v15-requirements.md §9},
 * the v15 MFFD import script bakes this assembler into its pre-flight
 * — when the script detects the S3 provider is inactive, it prints
 * the snippet, exits cleanly, and the operator pastes-and-restarts.
 *
 * <p>Templating in the rendered output is intentionally preserved
 * verbatim — the placeholders ({@code {{generate:hex:64}}},
 * {@code {{sidecar.host}}}, {@code {{from:postInit.N.field}}}) are
 * resolved by the operator-side bootstrap (which holds the secrets
 * file, has knowledge of the deploy hostname, and can capture
 * post-init structured output), not by the assembler.
 *
 * <p>{@link #assembleComposeSnippet(List)} is stateless and
 * deterministic — the same list of specs produces the same snippet
 * byte-for-byte, so the snippet can be diffed across plugin-version
 * upgrades.
 */
public final class SidecarsAssembler {

  private static final String INDENT_2 = "  ";

  private static final String INDENT_4 = "    ";

  private static final String INDENT_6 = "      ";

  /**
   * Renders a {@code services:} compose snippet for the given
   * sidecar specs. The output is YAML 1.2-compatible and uses the
   * docker-compose v3 schema.
   *
   * <p>Each {@link SidecarSpec} becomes one service named
   * {@code shepard-<id>}. Templating placeholders are emitted
   * verbatim (see class-level javadoc).
   *
   * <p>An empty list produces an empty string (no {@code services:}
   * header) so a no-op assembly doesn't leave a dangling YAML key.
   *
   * @param specs the sidecar declarations to render; may be empty
   *   but must not be null.
   * @return a YAML snippet; empty string if {@code specs} is empty.
   */
  public String assembleComposeSnippet(List<SidecarSpec> specs) {
    Objects.requireNonNull(specs, "specs");
    if (specs.isEmpty()) {
      return "";
    }

    StringBuilder out = new StringBuilder();
    out.append("# Generated by SidecarsAssembler from active plugin manifests.\n");
    out.append("# Append to your docker-compose.override.yml.\n");
    out.append("# Placeholders ({{generate:hex:N}}, {{sidecar.host}},\n");
    out.append(
      "# {{from:postInit.N.field}}) are resolved by the operator-side bootstrap.\n"
    );
    out.append("services:\n");
    for (SidecarSpec spec : specs) {
      renderService(out, spec);
    }
    // Collect every distinct volume across all specs into a single
    // top-level volumes: block so docker-compose accepts the snippet
    // standalone.
    boolean anyVolume = specs.stream().anyMatch(s -> !s.volumes().isEmpty());
    if (anyVolume) {
      out.append("volumes:\n");
      for (SidecarSpec spec : specs) {
        for (VolumeSpec v : spec.volumes()) {
          out.append(INDENT_2).append(v.name()).append(":\n");
        }
      }
    }
    return out.toString();
  }

  private void renderService(StringBuilder out, SidecarSpec spec) {
    String service = "shepard-" + spec.id();
    out.append(INDENT_2).append(service).append(":\n");
    out.append(INDENT_4).append("image: ").append(spec.image()).append("\n");
    out.append(INDENT_4).append("restart: unless-stopped\n");

    if (!spec.ports().isEmpty()) {
      out.append(INDENT_4).append("ports:\n");
      for (PortSpec p : spec.ports()) {
        // role label preserved as a YAML comment so the operator
        // sees what the port is for without consulting docs.
        out
          .append(INDENT_6)
          .append("- \"")
          .append(p.port())
          .append(":")
          .append(p.port())
          .append("\"  # ")
          .append(p.role())
          .append("\n");
      }
    }

    if (!spec.volumes().isEmpty()) {
      out.append(INDENT_4).append("volumes:\n");
      for (VolumeSpec v : spec.volumes()) {
        out
          .append(INDENT_6)
          .append("- ")
          .append(v.name())
          .append(":")
          .append(v.mountpoint())
          .append("\n");
      }
    }

    if (!spec.env().isEmpty()) {
      out.append(INDENT_4).append("environment:\n");
      // Sorted for byte-stable output.
      spec
        .env()
        .entrySet()
        .stream()
        .sorted(Map.Entry.comparingByKey())
        .forEach(e -> {
          out
            .append(INDENT_6)
            .append(e.getKey())
            .append(": \"")
            .append(escapeYamlDouble(e.getValue()))
            .append("\"\n");
        });
    }

    HealthcheckSpec hc = spec.healthcheck();
    if (hc != null) {
      out.append(INDENT_4).append("healthcheck:\n");
      out
        .append(INDENT_6)
        .append("test: [\"CMD-SHELL\", \"")
        .append(escapeYamlDouble(hc.cmd()))
        .append("\"]\n");
      out
        .append(INDENT_6)
        .append("interval: ")
        .append(formatDuration(hc.interval()))
        .append("\n");
      out
        .append(INDENT_6)
        .append("timeout: ")
        .append(formatDuration(hc.timeout()))
        .append("\n");
      out.append(INDENT_6).append("retries: ").append(hc.retries()).append("\n");
    }

    if (!spec.postInit().isEmpty()) {
      out.append(INDENT_4).append("# post-init (run by operator-side bootstrap after healthy):\n");
      int i = 0;
      for (String cmd : spec.postInit()) {
        out
          .append(INDENT_4)
          .append("#   [")
          .append(i++)
          .append("] ")
          .append(cmd)
          .append("\n");
      }
    }

    if (!spec.backendEnvBinding().isEmpty()) {
      out.append(INDENT_4).append("# backend-env (inject into the shepard backend service):\n");
      spec
        .backendEnvBinding()
        .entrySet()
        .stream()
        .sorted(Map.Entry.comparingByKey())
        .forEach(e -> {
          out
            .append(INDENT_4)
            .append("#   ")
            .append(e.getKey())
            .append("=")
            .append(e.getValue())
            .append("\n");
        });
    }
  }

  private static String escapeYamlDouble(String s) {
    // YAML double-quoted scalars: backslash + double-quote need
    // escaping; everything else passes through. Templating braces
    // are NOT escaped — they pass through verbatim so the
    // operator-side bootstrap can substitute.
    return s.replace("\\", "\\\\").replace("\"", "\\\"");
  }

  private static String formatDuration(java.time.Duration d) {
    long sec = d.getSeconds();
    if (sec % 60 == 0 && sec >= 60) {
      return (sec / 60) + "m";
    }
    return sec + "s";
  }
}
