.build_cpp_client:
  stage: build
  image:
    name: openapitools/openapi-generator-cli:v7.8.0
    entrypoint: [""]
  needs: [build_backend]
  script:
    - docker-entrypoint.sh generate -i backend/target/openapi/openapi.json -g cpp-restsdk -o clients/cpp/client -c clients/cpp/config.yaml --type-mappings set=std::vector
  artifacts:
    expire_in: 2 days
    paths:
      - clients/cpp/client

.upload_cpp: &upload_cpp
  stage: upload
  needs: [build_cpp_client]
  script:
    - cd clients/cpp
    - tar cvfz cpp-client.tgz client/
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cpp-client.tgz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/cpp-client/${VERSION_NUMBER}/cpp-client.tgz"'

.upload_cpp_client_dev:
  <<: *upload_cpp
  before_script:
    - !reference [.version_number, script]
    - export VERSION_NUMBER=${VERSION_NUMBER}-dev.${CI_PIPELINE_IID}
    - echo ${VERSION_NUMBER}

.upload_cpp_client:
  <<: *upload_cpp
  before_script:
    - !reference [.version_number, script]
    - echo ${VERSION_NUMBER}
