.build_java: &build_java
  stage: build
  image:
    name: openapitools/openapi-generator-cli:v7.8.0
    entrypoint: [""]
  needs: [build_backend]
  script:
    - docker-entrypoint.sh generate -i backend/target/openapi/openapi.json -g java -o clients/java/client -p=apiPackage=de.dlr.shepard.client.java.api,modelPackage=de.dlr.shepard.client.java.model,artifactId=shepard-client,groupId=de.dlr.shepard.client.java,parentGroupId=de.dlr.shepard.client.java,parentArtifactId=de.dlr.shepard.client.java,parentVersion=1.0.0-SNAPSHOT,artifactVersion=${VERSION_NUMBER}
  artifacts:
    expire_in: 2 days
    paths:
      - clients/java

.upload_java_client:
  stage: upload
  image: maven:3-eclipse-temurin-17
  needs: [build_java_client, get_version]
  script:
    - cd clients/java
    - mvn ${MAVEN_CLI_OPTS} deploy -s ci_settings.xml

.build_java_client_dev:
  <<: *build_java
  before_script:
    - export VERSION_NUMBER=${VERSION_NUMBER}-dev-${CI_PIPELINE_IID}-SNAPSHOT
    - echo ${VERSION_NUMBER}

.build_java_client:
  <<: *build_java
  before_script:
    - echo ${VERSION_NUMBER}
