.build_java: &build_java
  stage: build
  image:
    name: openapitools/openapi-generator-cli:v7.16.0
    entrypoint: [""]
  needs: [build_backend, get_version]
  script:
    - docker-entrypoint.sh generate -i backend/target/openapi/openapi.json -g java -o clients/java/client -c clients/java/config.yaml -p=artifactVersion=${VERSION_NUMBER}
  artifacts:
    expire_in: 2 days
    paths:
      - clients/java

.upload_java_client:
  stage: upload
  image: maven:3-eclipse-temurin-17
  needs: [build_java_client]
  script:
    - cd clients/java
    - mvn ${MAVEN_CLI_OPTS} deploy -s ci_settings.xml

.build_java_client:
  <<: *build_java
  before_script:
    # add a '-SNAPSHOT' to dev builds
    - if [ $IS_DEV_JOB -eq 1 ]; then
      export VERSION_NUMBER=${VERSION_NUMBER}-SNAPSHOT;
      fi
    - echo ${VERSION_NUMBER}
