.build_typescript: &build_typescript
  stage: build
  image:
    name: openapitools/openapi-generator-cli:v7.9.0
    entrypoint: [""]
  needs: [build_backend, get_version]
  script:
    - docker-entrypoint.sh generate -i backend/target/openapi/openapi.json -g typescript-fetch -o clients/typescript -p=npmName=@dlr-shepard/shepard-client,npmRepository=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/,npmVersion=${VERSION_NUMBER},supportsES6=true,typescriptThreePlus=true
  artifacts:
    expire_in: 2 days
    paths:
      - clients/typescript

.upload_typescript: &upload_typescript
  stage: upload
  image: node:22-slim
  needs: [build_typescript_client, get_version]
  before_script:
    - cd clients/typescript
    - touch .npmrc
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - echo "${CI_API_V4_URL#http*:}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}" >> .npmrc
  script:
    - npm install
    - npm run build
    - npm publish --tag ${NPM_TAG}

.build_typescript_client:
  <<: *build_typescript
  before_script:
    # overwrite version number format if it is a dev job, to match typescript naming conventions
    - if [ $IS_DEV_JOB -eq 1 ]; then
      export VERSION_NUMBER=${LATEST_TAG}-dev.${CI_PIPELINE_IID};
      export NPM_TAG=dev;
      else
      NPM_TAG=latest;
      fi
    - echo ${VERSION_NUMBER}
    - echo ${NPM_TAG}

.upload_typescript_client:
  <<: *upload_typescript
  variables:
    NPM_TAG: latest
