ifndef::imagesdir[:imagesdir: ../../images]

[[section-technical-risks]]
== Risks and Technical Debts

=== Risks

_Propability: very unprobable, unprobable, unsure, propable, very propable_

_Costs: critical, expensive, unsure, cheap, negligible_

[cols="1,1,1,1,1,1,1"]
|===
|ID|Name|Description|Possible Actions|Probability|Costs|Priority

|
|
|
|
|
|
|

|===

=== Technical Debt

> Software systems are prone to the build up of cruft - deficiencies in internal quality that make it harder than it would ideally be to modify and extend the system further. Technical Debt is a metaphor, coined by Ward Cunningham, that frames how to think about dealing with this cruft [...]
> - 21 May 2019, Martin Fowler (https://martinfowler.com/bliki/TechnicalDebt.html)

==== Technical Debt Process

The following process handles all technical debt except for dependency updates, which have <<dependency-updates, their own process>>.
Besides dependency updates, every other technical debt is to be documented in the form of an issue in the backlog.

If a technical debt has been identified and a corresponding issue has been created in the backlog, the usual planning and prioritization process takes care of this debt.
This makes the backlog the single source of truth for all known and unresolved technical debt.

Usually, the technical debt can be resolved in this way.
In rare cases, it can happen that we want to keep this debt or decide that the debt is not really a problem for us.
In these cases, the situation needs to be described in the <<technical-debt, table below>> and the corresponding issue can then be closed.

[[technical-debt]]
[cols="1,1,1,1,1"]
|===
|ID|Name|Description|Solution Strategy|Priority

|1
|Missing permissions
|Back in the time when we started developing shepard, there was no authorization implemented. Therefore, not all Collections or Containers are guaranteed to have permissions attached. There is a fallback solution implemented in shepard to take care of such situations. We decided that `no permissions` means `everyone has access`.
|A database migration could be implemented to add empty permissions to all entities. However, we should not make any assumptions about the actual permissions to avoid breaking existing datasets.
|Low

|2
|Cryptic usernames
|Depending on how the OIDC identity provider is configured, shepard sometimes generates very cryptic user names. The username is retrieved from the `subject` field of the JWT. While the subject is guaranteed to be unique, some identity providers generate a UUID, which makes the resulting username not very user-friendly. Keycloak uses subjects in the form `f:173df088-e611-4535-827a-feb57457a5a6:haas_tb`, where the last part is the actual username as it appears in the active directory. Therefore it seemed to be a good idea to use only the last part as username in shepard. However, this logic breaks as soon as another identity provider is used.
|Since the username is used to identify users in shepard, it is not so easy to change it. A migration would be possible if shepard could fetch all available users from the identity provider and then migrate all users at once. However, this is not possible with the current configuration. Keycloak adds a `preferred_username` field to the JWTs, but this is an addition that comes from Keycloak and is not specified by OIDC.
|High

|===
