ifndef::imagesdir[:imagesdir: ../../images]

[[section-solution-strategy]]
== Solution Strategy

[CAUTION]
====
This chapter is still under construction
====

[cols="1,2,2,1"]
|===
|Quality Goal|Scenario|Solution Approach|Link to Details

|Usability
|
|
|

|Reliability
|
|
|

|Maintainability
|
|
|

|Performance
|
|
|

|Operability
|
|
|
|===

=== Backend (Quarkus)

==== Modularization

The backend is split into modules by their functionality.
That means that there is e.g. a module for timeseries including managing containers and timeseries data, a module for managing files, for collections & data objects etc.

Each of those modules contains all technical components needed to fulfill it's purpose, including endpoints, services, domain model objects, DAOs, entities and repositories.

Additionally, there may be modules for special functionalities like authentication.

See <<building-blocks-level-2>> for the concrete modularization.

===== Internal Module Structure

A module should only expose it's services to other modules, not internal components like DAOs or repositories.

Also, following <<adr-016>> the services are responsible for validating the operation.
That includes checking the appropriate permissions of the user or the existence of the resource.

Service methods will throw a runtime exception in case the collection does not exist, is deleted or the user does not have appropriate permissions.
Usually it would be an `InvalidPathException` or `InvalidAuthException`.
The exception type should be documented in the JavaDoc of the methods.

[[solution_strategy_rest-endpoints]]
==== REST Endpoints

We use link:https://quarkus.io/guides/rest[quarkus-rest] to define REST endpoints.

For authentication and general request validation, we use filters following the link:https://quarkus.io/guides/rest#the-jakarta-rest-way[Jakarta REST way].
The filters can be found at `filters/`.
In general, all requests need to be done by authenticated users.
The `JWTFilter` and the `UserFilter` take care of validating authentication.

Some endpoints should be public, for example `/healthz` and `/versionz`.
To make this possible we use the `PublicEndpointRegistry` class.
In this class we register all public endpoints in a static string array.
The authentication filters will be bypassed for endpoints in this array.
Since the `/healthz` endpoint is automatically public thanks to the link:https://quarkus.io/guides/smallrye-health[SmallRye Health] extension, we don't need to add it to the `PublicEndpointRegistry`.

=== Frontend (Nuxt)

==== Structure

Each route is defined in **pages/**.
The root file of a route itself should not contain a lot of logic, instead it should invoke one or more components.

In **components/** all components are stored.
These are grouped in folders by domain, e.g. `components/collections`.

Stateful logic can be extracted into link:https://vuejs.org/guide/reusability/composables[composables] and are stored in **composables/**.

Stateless utility functions should be stored under **utils/**.

===== Routing

We aim to make routes as understandable as possible and try to make each resource view have a unique URL in order to be able to directly link to resources.

This means that for example the collections list view is at `/collections`.
One collection can be found at `/collections/:id`.
Since data objects belong to a collection and share a common side bar menu with their collection, they can be found at `/collections/:id/dataobjects/:id`.

====== Links

In order to navigate users to another page we aim to avoid:

* javascript only navigations like `router.push(...)` to make users able to see where they will be redirected
* standard href links to avoid rerendering the whole page

Instead, we use link:https://nuxt.com/docs/api/components/nuxt-link[NuxtLink] as much as possible.
This enables a url display on hover as well as client-side navigations in a hydrated page.

==== Backend Interaction

For the interaction with the backend we check a generated openapi client into the repository, see <<backend-client-for-frontend, here>> for more information.

In order to directly instantiate the API clients with our default configuration, we use the `createApiInstance` utility.

=== Technology Choices

==== Using Node LTS

The current LTS version of Node.js should be used in all of the project (Gitlab jobs, docker images, local development, etc.) to maintain reliability and performance.

==== Using Quarkus LTS

The current LTS version of Quarkus should be used in our backend to maintain reliability and performance.
