package de.dlr.shepard.v2.importer.io;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.util.List;
import java.util.Map;

/**
 * IMP1 — request body for {@code POST /v2/import/validate}.
 *
 * <p>A manifest describes the full set of DataObjects, Containers, and
 * Container-to-DataObject references that should be created as an atomic
 * logical batch.  The validate endpoint performs a dry run and returns a
 * commitId (plan seal) if the manifest is structurally sound.
 *
 * <p>Design rules (enforced by {@code ImportValidationService}):
 * <ul>
 *   <li>Every {@code localRef} is an opaque caller-defined string that scopes
 *       the manifest — it is not an appId and is not persisted.</li>
 *   <li>{@code parentRef} and {@code predecessorRefs} in
 *       {@link ManifestDataObjectIO} must resolve to other {@code localRef}
 *       values within the same manifest.</li>
 *   <li>Reference rows ({@link ManifestReferenceIO}) must similarly point at
 *       declared DataObject and Container localRefs.</li>
 * </ul>
 */
public record ImportManifestIO(
  @NotBlank String collectionAppId,
  @NotNull @Valid List<ManifestDataObjectIO> dataObjects,
  @Valid List<ManifestContainerIO> containers,
  @Valid List<ManifestReferenceIO> references,
  @Valid AgentContextIO agentContext
) {

  /**
   * Optional agent-context hint embedded in the manifest.
   *
   * <p>When present, signals that the manifest was generated by an automated
   * importer/agent that consulted the collection's current state via
   * {@code GET /v2/import/context} before producing the manifest.
   *
   * <p>{@code null} on the top-level {@link ImportManifestIO} means no agent
   * context was requested — fully backwards-compatible with manifests produced
   * before this field was added.
   *
   * @param includeSemanticGraph  {@code true} if the agent requested semantic
   *                              vocabulary from the context endpoint. Default
   *                              {@code false} — opt-in.
   * @param ontologyAppIds        IDs of ontologies the agent restricted its
   *                              vocabulary to.  {@code null} means "all
   *                              available"; an empty list means "none".
   */
  public record AgentContextIO(
    boolean includeSemanticGraph,
    List<String> ontologyAppIds
  ) {}



  /**
   * One DataObject to create.
   *
   * @param localRef       caller-scoped key used to form parent/predecessor refs within this manifest
   * @param name           the DataObject's display name
   * @param description    optional free-text description
   * @param status         lifecycle status — must be one of the shepherd-defined values if provided
   * @param attributes     key/value metadata attributes
   * @param parentRef      localRef of a DataObject in this manifest to be set as the parent
   * @param predecessorRefs localRefs of DataObjects in this manifest to set as predecessors
   */
  public record ManifestDataObjectIO(
    @NotBlank String localRef,
    @NotBlank String name,
    String description,
    String status,
    Map<String, String> attributes,
    String parentRef,
    List<String> predecessorRefs
  ) {}

  /**
   * One Container to create.
   *
   * @param localRef caller-scoped key used in {@link ManifestReferenceIO}
   * @param type     must be one of {@code TIMESERIES}, {@code FILE}, {@code STRUCTURED_DATA}
   * @param name     the Container's display name
   */
  public record ManifestContainerIO(
    @NotBlank String localRef,
    @NotBlank String type,
    @NotBlank String name
  ) {}

  /**
   * Declares that a Container belongs to a DataObject.
   *
   * @param dataObjectRef localRef of the owning DataObject
   * @param containerRef  localRef of the container to attach
   */
  public record ManifestReferenceIO(
    @NotBlank String dataObjectRef,
    @NotBlank String containerRef
  ) {}
}
