ifndef::imagesdir[:imagesdir: ../../images]

[[section-building-block-view]]
== Building Block View

[CAUTION]
====
This chapter is still under construction
====

=== Whitebox Overall System

[plantuml, "{plantUMLDir}whitebox-overview", png]
----
@startuml Whitebox Overview

:User: as user
[Webfrontend (UI)] as frontend
[External Services & Scripts] as stc #ffffff

[Backend] as backend
database "Neo4j" as neo4j #DAE8FC
database "InfluxDB" as influxdb #D5E8D4
database "TimescaleDB" as timescale #AAEEFF
database "MongoDB" as mongodb #FFE6CC

stc --> backend
frontend --> backend

backend --> neo4j
backend --> influxdb
backend --> timescale
backend --> mongodb

user --> frontend
user --> backend
@enduml
----


The backend is designed to be modular and expandable.
One of the main tasks of the backend is the management of metadata.
The data structure is used to manage the attached data.
This structure as well as the corresponding references is managed by the `core` package and stored in Neo4j.

**Contained Blackboxes:**
[cols="1,1"]
|===
|Building Block | Responsibility

| Backend
| Handles incoming requests from actors like the shepard Timeseries Collector, Webfrontend and Users.
Allows these actors to upload, search and retrieve different kinds of data.

| Webfrontend (UI)
| Allows users to interact (upload, search, retrieve) with the stored data via a webapp.

| External Services & Scripts
| External services that interact with a shepard instance.
For example the shepard Timeseries Collector (sTC).
It is one of many tools in the shepard ecosystem and aims to collect data from different sources and stores them as timeseries data to shepard.

|===

[[building-blocks-level-2]]
=== Level 2

[plantuml, "{plantUMLDir}whitebox-backend-level-2", png]
----
@startuml Whitebox Backend

:User: as user

package "deprecated" {
  database "InfluxDB" as influxdb #D5E8D4
}

[Context] as context
[Data] as data
[Auth] as auth
[Common] as common

database "Neo4j" as neo4j #DAE8FC
database "TimescaleDB" as timescaledb #AAEEFF
database "MongoDB" as mongodb #FFE6CC

user --> context
user --> data

context -> data: references data
context --> neo4j
data --> neo4j
data --> mongodb
data --> influxdb: extracts data during migration
data --> timescaledb

data -[hidden]> common
common -[hidden]> auth

@enduml
----

**Contained Blackboxes:**
[cols="1,1"]
|===
|Building Block | Responsibility

|Data|
The data module is responsible for handling research data, including persisting and retrieval of this data.
Containers for each data type are also part of the data module.

|Context|
The context module is responsible for managing the context of the research data.
This includes collections, data objects, references to data (or rather containers) as well as the lab journal.

|Auth|
The auth module is responsible for everything concerning authentication and authorization.

|Common|
The common module provides core functionality of shepard as well as commonly used code for other modules.
For example, it encapsulates common logic to interact with the neo4j database.

The common module must not have dependencies on other modules.
|===

=== Level 3

// TODO: Include Auth and Common properly as external dependencies & describe blackboxes a little bit more

==== Context

[plantuml, "{plantUMLDir}level-3-overview", png]
----
@startuml Level 3 Overview
left to right direction

[Collections & DataObjects] as collections
[Lab Journal] as labjournal
[References] as references

[Data] as data #white

database "Neo4j" as neo4j #DAE8FC


collections --> neo4j
labjournal --> neo4j
references --> neo4j
references --> data

@enduml
----

**Contained Blackboxes:**
[cols="1,1"]
|===
|Building Block | Responsibility

| Collections & DataObjects
| Manages metadata and references of organizational elements like `DataObjects` and `Collections`.

| Lab Journal
|

| References
|

|===


==== Data

[plantuml, "{plantUMLDir}level-3-overview", png]
----
@startuml Level 3 Overview
left to right direction

[Timeseries] as timeseries
[Structured Data] as structureddata
[Files] as files
[Semantic Repository] as semantic

package "deprecated" {
  database "InfluxDB" as influxdb #D5E8D4
}

database "Neo4j" as neo4j #DAE8FC
database "TimescaleDB" as timescaledb #AAEEFF
database "MongoDB" as mongodb #FFE6CC

timeseries --> influxdb: extracts data

neo4j <-- timeseries
neo4j <-- structureddata
neo4j <-- files
timeseries --> timescaledb
structureddata --> mongodb
files --> mongodb

timeseries -[hidden]> semantic

@enduml
----


**Contained Blackboxes:**
[cols="1,1"]
|===
|Building Block | Responsibility


| Timeseries
| Manages timeseries data.
Uses TimescaleDB for persistence.
Provides all needed code from the endpoint to the database access.

| Structured Data
| Manages structured data uploads.

| Files
| Manages file uploads.

|===

==== Lab Journal

[plantuml, "{plantUMLDir}component-lab-journal", png]
----
@startuml Component Lab Journal

database "Neo4j"

REST - [LabJournal]
[LabJournal] ..> [Collections & DataObjects] : use
[LabJournal] ..> [Authorization] : use
[LabJournal] ..> [Neo4j] : use
[Frontend] ..> REST : use

@enduml
----

The Lab Journal module allows users to create, edit and delete journal entries.
Lab Journal Entries can be used for documentation purposes.
This feature is thought to be used via the frontend but can also be used directly via the REST interface if needed.
Lab Journal entries are stored in the neo4j database.
This module has a dependency to the `Collections & DataObjects` module because they are always linked to a `DataObject`.
This module also has a dependency to the `Authoriziation` module because the user needs the correct permissions to see and edit lab journal entries.


[plantuml, "{plantUMLDir}classes-lab-journal", png]
----
@startuml Classes Lab Journal

class LabJournalEntryRest
class LabJournalEntryService
class AbstractEntity
class LabJournalEntry {
  String content
}
class LabJournalEntryDAO
class LabJournalEntryIO

AbstractEntity <|-- LabJournalEntry

@enduml
----

Following our solution strategy, we have the following classes:

- `LabJournalEntryRest` contains the REST endpoints
- `LabJournalEntryIO` is the data transfer object used in the REST interface
- `LabJournalEntryService` contains the business logic
- `LabJournalEntry` is the main business entity containing the content as html string
- `LabJournalEntryDAO` is used for communication with the neo4j database

==== Timeseries

[INFO]
====
This module replaced the old implementation using InfluxDB as of version 4.0.0.
For decisions and reasoning, check out <<adr008>>, <<adr010>> and <<adr011>>.
For migration instructions of shepard instances up to version 3.x.x, see here: https://gitlab.com/dlr-shepard/shepard/-/merge_requests/389#migration-instructions
For a more technical description of the migration, check out <<migration-from-influx>>
====

This module handles persisting timeseries data in a link:https://www.timescale.com/[TimescaleDB].
It includes all relevant endpoints and services.
The database schema includes two tables:

* A timeseries table containing the metadata for each timeseries (measurement, field, etc.) similar to the metadata in an Influx timeseries.
* A link:https://docs.timescale.com/use-timescale/latest/hypertables/[hypertable] containing the data points.

The schema for both tables is defined by the database migrations in `src/main/java/resources/db/migration`.
The timeseries table is managed in the code using hibernate entities.
The data point table is managed directly using custom queries, since we want to make full use of TimescaleDB features and performance.

[[migration-from-influx]]
===== Migration from InfluxDB

Shepard can be started in migration mode by setting the property `shepard.migration-mode.enabled` to true.
For example, the following command starts the dev mode in migration mode:

```bash
./mvnw quarkus:dev -Dshepard.migration-mode.enabled=true
```

.Migration Behaviour

When shepard is started in migration mode, the migration from InfluxDB to TimescaleDB is run.
More specifically, the behaviour is as follows:

[cols="1a,1a,1a,1a,1a"]
|===
|Migration Mode|InfluxDB|TimescaleDB|Migration Status|Behaviour

|Off|*|*|Open|stops with error
|Off|Configured|Available|Done|runs as usual, informs user that influx config is obsolete
|Off|*|Available|Done|runs as usual
|On|Unavailable|*|Open|stops with error
|On|*|Unavailable|Open|stops with error
|On|Available|Available|Open|Run the migrations and shepard without endpoints and stop afterwards
|On|*|*|Done|Stop and inform users that data is already migrated
|===

.Migration Status

We identify the status of previous migrations in the following way:

For all timeseries containers with a database name set (this identifies the ones created for influx) that are not deleted there must be a migration task entity in the database.
This entity must have the finished status and no errors.
In this case, all data was migrated successfully.
This also means that new instances have no need for migration, as they don't have timeseries containers yet.

.Rollback Strategy

Since we require the migrations to be run before starting a post-4.0.0 instance of shepard, the TimescaleDB must be empty before the migrations.
The migration progress is persisted in the TimescaleDB.
In case of errors, the migration can be re-run by deleting the data in the timescaledb (or removing the timescale container including it's volumes).
