openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
paths:
  /search/:
    post:
      summary: Search
      operationId: search_search__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResult"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
    Query:
      title: Query
      required:
        - query
      type: object
      properties:
        query:
          title: Query
          type: string
    QueryType:
      title: QueryType
      enum:
        - structuredData
        - timeseries
        - file
      type: string
      description: An enumeration.
    Result:
      title: Result
      required:
        - collectionId
        - dataObjectId
        - referenceId
      type: object
      properties:
        collectionId:
          title: Collectionid
          type: integer
        dataObjectId:
          title: Dataobjectid
          type: integer
        referenceId:
          title: Referenceid
          type: integer
    Scope:
      title: Scope
      required:
        - collectionId
        - traversalRules
      type: object
      properties:
        collectionId:
          title: Collectionid
          type: integer
        dataObjectId:
          title: Dataobjectid
          type: integer
        traversalRules:
          type: array
          items:
            $ref: "#/components/schemas/TraversalRule"
    SearchEntity:
      title: SearchEntity
      required:
        - query
        - queryType
      type: object
      properties:
        query:
          $ref: "#/components/schemas/Query"
        queryType:
          $ref: "#/components/schemas/QueryType"
    SearchRequest:
      title: SearchRequest
      required:
        - scopes
        - search
      type: object
      properties:
        scopes:
          title: Scopes
          type: array
          items:
            $ref: "#/components/schemas/Scope"
        search:
          $ref: "#/components/schemas/SearchEntity"
    SearchResult:
      title: SearchResult
      required:
        - resultSet
        - search
      type: object
      properties:
        resultSet:
          title: Resultset
          type: array
          items:
            $ref: "#/components/schemas/Result"
        search:
          $ref: "#/components/schemas/SearchEntity"
    TraversalRule:
      title: TraversalRule
      enum:
        - children
        - parent
        - predecessors
        - successors
      type: string
      description: An enumeration.
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
