/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShepardTemplate } from './ShepardTemplate';
import {
    ShepardTemplateFromJSON,
    ShepardTemplateFromJSONTyped,
    ShepardTemplateToJSON,
} from './ShepardTemplate';

/**
 * 
 * @export
 * @interface AasIdtaImportResult
 */
export interface AasIdtaImportResult {
    /**
     * Templates created or updated during this import run.
     * @type {Array<ShepardTemplate>}
     * @memberof AasIdtaImportResult
     */
    created: Array<ShepardTemplate>;
    /**
     * Count of templates skipped because their content was already current.
     * @type {number}
     * @memberof AasIdtaImportResult
     */
    skipped: number;
}

/**
 * Check if a given object implements the AasIdtaImportResult interface.
 */
export function instanceOfAasIdtaImportResult(value: object): value is AasIdtaImportResult {
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('skipped' in value) || value['skipped'] === undefined) return false;
    return true;
}

export function AasIdtaImportResultFromJSON(json: any): AasIdtaImportResult {
    return AasIdtaImportResultFromJSONTyped(json, false);
}

export function AasIdtaImportResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AasIdtaImportResult {
    if (json == null) {
        return json;
    }
    return {
        
        'created': ((json['created'] as Array<any>).map(ShepardTemplateFromJSON)),
        'skipped': json['skipped'],
    };
}

export function AasIdtaImportResultToJSON(value?: AasIdtaImportResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created': ((value['created'] as Array<any>).map(ShepardTemplateToJSON)),
        'skipped': value['skipped'],
    };
}

