/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AasLangString
 */
export interface AasLangString {
    /**
     * BCP 47 language tag, e.g. `en`.
     * @type {string}
     * @memberof AasLangString
     */
    language: string;
    /**
     * Text value in the given language.
     * @type {string}
     * @memberof AasLangString
     */
    text: string;
}

/**
 * Check if a given object implements the AasLangString interface.
 */
export function instanceOfAasLangString(value: object): value is AasLangString {
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function AasLangStringFromJSON(json: any): AasLangString {
    return AasLangStringFromJSONTyped(json, false);
}

export function AasLangStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): AasLangString {
    if (json == null) {
        return json;
    }
    return {
        
        'language': json['language'],
        'text': json['text'],
    };
}

export function AasLangStringToJSON(value?: AasLangString | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'language': value['language'],
        'text': value['text'],
    };
}

