/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AasReference } from './AasReference';
import {
    AasReferenceFromJSON,
    AasReferenceFromJSONTyped,
    AasReferenceToJSON,
} from './AasReference';
import type { AasAssetInformation } from './AasAssetInformation';
import {
    AasAssetInformationFromJSON,
    AasAssetInformationFromJSONTyped,
    AasAssetInformationToJSON,
} from './AasAssetInformation';
import type { AasLangString } from './AasLangString';
import {
    AasLangStringFromJSON,
    AasLangStringFromJSONTyped,
    AasLangStringToJSON,
} from './AasLangString';

/**
 * 
 * @export
 * @interface AasShell
 */
export interface AasShell {
    /**
     * Globally unique IRI for this Shell. Derived from the Collection appId: `urn:shepard:collection:{appId}`.
     * @type {string}
     * @memberof AasShell
     */
    id: string;
    /**
     * Short, non-unique identifier per IDTA AAS v3. Sanitised from the Collection name: leading digit or special chars replaced so the value matches [a-zA-Z][a-zA-Z0-9_]*.
     * @type {string}
     * @memberof AasShell
     */
    idShort: string;
    /**
     * Minimal asset information block per IDTA AAS v3 §7.
     * @type {AasAssetInformation}
     * @memberof AasShell
     */
    assetInformation: AasAssetInformation;
    /**
     * Human-readable description list (langString). Sourced from Collection.description. Absent when the Collection has no description.
     * @type {Array<AasLangString>}
     * @memberof AasShell
     */
    description?: Array<AasLangString>;
    /**
     * Submodel references (IDTA AAS v3 Reference objects). Empty in AAS1a; populated by AAS1b from top-level DataObjects on single-Shell GET. Type changed from List<String> to List<AasReference> in AAS1b Commit 2.
     * @type {Array<AasReference>}
     * @memberof AasShell
     */
    submodels: Array<AasReference>;
}

/**
 * Check if a given object implements the AasShell interface.
 */
export function instanceOfAasShell(value: object): value is AasShell {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('idShort' in value) || value['idShort'] === undefined) return false;
    if (!('assetInformation' in value) || value['assetInformation'] === undefined) return false;
    if (!('submodels' in value) || value['submodels'] === undefined) return false;
    return true;
}

export function AasShellFromJSON(json: any): AasShell {
    return AasShellFromJSONTyped(json, false);
}

export function AasShellFromJSONTyped(json: any, ignoreDiscriminator: boolean): AasShell {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'idShort': json['idShort'],
        'assetInformation': AasAssetInformationFromJSON(json['assetInformation']),
        'description': json['description'] == null ? undefined : ((json['description'] as Array<any>).map(AasLangStringFromJSON)),
        'submodels': ((json['submodels'] as Array<any>).map(AasReferenceFromJSON)),
    };
}

export function AasShellToJSON(value?: AasShell | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'idShort': value['idShort'],
        'assetInformation': AasAssetInformationToJSON(value['assetInformation']),
        'description': value['description'] == null ? undefined : ((value['description'] as Array<any>).map(AasLangStringToJSON)),
        'submodels': ((value['submodels'] as Array<any>).map(AasReferenceToJSON)),
    };
}

