/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbandonRequestIO
 */
export interface AbandonRequestIO {
    /**
     * 
     * @type {string}
     * @memberof AbandonRequestIO
     */
    errorMessage?: string;
}

/**
 * Check if a given object implements the AbandonRequestIO interface.
 */
export function instanceOfAbandonRequestIO(value: object): value is AbandonRequestIO {
    return true;
}

export function AbandonRequestIOFromJSON(json: any): AbandonRequestIO {
    return AbandonRequestIOFromJSONTyped(json, false);
}

export function AbandonRequestIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbandonRequestIO {
    if (json == null) {
        return json;
    }
    return {
        
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
    };
}

export function AbandonRequestIOToJSON(value?: AbandonRequestIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'errorMessage': value['errorMessage'],
    };
}

