/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbstractDataObject
 */
export interface AbstractDataObject {
    /**
     * 
     * @type {number}
     * @memberof AbstractDataObject
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof AbstractDataObject
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof AbstractDataObject
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof AbstractDataObject
     */
    readonly updatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof AbstractDataObject
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof AbstractDataObject
     */
    name: string;
    /**
     * Application-level UUID v7 identifier.
     * @type {string}
     * @memberof AbstractDataObject
     */
    readonly appId?: string | null;
    /**
     * Write counter (V2a revision). 0 for non-versionable entities.
     * @type {number}
     * @memberof AbstractDataObject
     */
    readonly revision?: number;
    /**
     * 
     * @type {string}
     * @memberof AbstractDataObject
     */
    description?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof AbstractDataObject
     */
    attributes?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof AbstractDataObject
     */
    status?: AbstractDataObjectStatusEnum | null;
    /**
     * 
     * @type {string}
     * @memberof AbstractDataObject
     */
    license?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AbstractDataObject
     */
    accessRights?: AbstractDataObjectAccessRightsEnum | null;
    /**
     * FAIR2: ORCID of the creator, stamped server-side at creation. Read-only — not accepted as input. Absent when null or creator had no ORCID set.
     * @type {string}
     * @memberof AbstractDataObject
     */
    readonly createdByOrcid?: string | null;
    /**
     * ISO-8601 date (e.g. '2027-12-31') after which the embargo lifts; only meaningful when accessRights=EMBARGOED.
     * @type {string}
     * @memberof AbstractDataObject
     */
    embargoEndDate?: string | null;
}


/**
 * @export
 */
export const AbstractDataObjectStatusEnum = {
    Draft: 'DRAFT',
    InReview: 'IN_REVIEW',
    Ready: 'READY',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED',
    NcrOpen: 'NCR_OPEN',
    OnHold: 'ON_HOLD',
    Rejected: 'REJECTED',
    Certified: 'CERTIFIED',
    ConcessionPending: 'CONCESSION_PENDING'
} as const;
export type AbstractDataObjectStatusEnum = typeof AbstractDataObjectStatusEnum[keyof typeof AbstractDataObjectStatusEnum];

/**
 * @export
 */
export const AbstractDataObjectAccessRightsEnum = {
    Open: 'OPEN',
    Restricted: 'RESTRICTED',
    Closed: 'CLOSED',
    Embargoed: 'EMBARGOED'
} as const;
export type AbstractDataObjectAccessRightsEnum = typeof AbstractDataObjectAccessRightsEnum[keyof typeof AbstractDataObjectAccessRightsEnum];


/**
 * Check if a given object implements the AbstractDataObject interface.
 */
export function instanceOfAbstractDataObject(value: object): value is AbstractDataObject {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AbstractDataObjectFromJSON(json: any): AbstractDataObject {
    return AbstractDataObjectFromJSONTyped(json, false);
}

export function AbstractDataObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbstractDataObject {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'createdBy': json['createdBy'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
        'updatedBy': json['updatedBy'],
        'name': json['name'],
        'appId': json['appId'] == null ? undefined : json['appId'],
        'revision': json['revision'] == null ? undefined : json['revision'],
        'description': json['description'] == null ? undefined : json['description'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'status': json['status'] == null ? undefined : json['status'],
        'license': json['license'] == null ? undefined : json['license'],
        'accessRights': json['accessRights'] == null ? undefined : json['accessRights'],
        'createdByOrcid': json['createdByOrcid'] == null ? undefined : json['createdByOrcid'],
        'embargoEndDate': json['embargoEndDate'] == null ? undefined : json['embargoEndDate'],
    };
}

export function AbstractDataObjectToJSON(value?: Omit<AbstractDataObject, 'id'|'createdAt'|'createdBy'|'updatedAt'|'updatedBy'|'appId'|'revision'|'createdByOrcid'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
        'attributes': value['attributes'],
        'status': value['status'],
        'license': value['license'],
        'accessRights': value['accessRights'],
        'embargoEndDate': value['embargoEndDate'],
    };
}

