/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminGitCredentialResultIO
 */
export interface AdminGitCredentialResultIO {
    /**
     * 
     * @type {string}
     * @memberof AdminGitCredentialResultIO
     */
    appId?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminGitCredentialResultIO
     */
    host?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminGitCredentialResultIO
     */
    username?: string;
}

/**
 * Check if a given object implements the AdminGitCredentialResultIO interface.
 */
export function instanceOfAdminGitCredentialResultIO(value: object): value is AdminGitCredentialResultIO {
    return true;
}

export function AdminGitCredentialResultIOFromJSON(json: any): AdminGitCredentialResultIO {
    return AdminGitCredentialResultIOFromJSONTyped(json, false);
}

export function AdminGitCredentialResultIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminGitCredentialResultIO {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['appId'] == null ? undefined : json['appId'],
        'host': json['host'] == null ? undefined : json['host'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function AdminGitCredentialResultIOToJSON(value?: AdminGitCredentialResultIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'appId': value['appId'],
        'host': value['host'],
        'username': value['username'],
    };
}

