/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BasicEntityV2
 */
export interface BasicEntityV2 {
    /**
     * 
     * @type {number}
     * @memberof BasicEntityV2
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof BasicEntityV2
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof BasicEntityV2
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof BasicEntityV2
     */
    readonly updatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof BasicEntityV2
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof BasicEntityV2
     */
    name: string;
    /**
     * Application-level UUID v7 identifier.
     * @type {string}
     * @memberof BasicEntityV2
     */
    readonly appId?: string | null;
    /**
     * Write counter (V2a revision). 0 for non-versionable entities.
     * @type {number}
     * @memberof BasicEntityV2
     */
    readonly revision?: number;
    /**
     * 
     * @type {string}
     * @memberof BasicEntityV2
     */
    uniqueId?: string;
}

/**
 * Check if a given object implements the BasicEntityV2 interface.
 */
export function instanceOfBasicEntityV2(value: object): value is BasicEntityV2 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function BasicEntityV2FromJSON(json: any): BasicEntityV2 {
    return BasicEntityV2FromJSONTyped(json, false);
}

export function BasicEntityV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): BasicEntityV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'createdBy': json['createdBy'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
        'updatedBy': json['updatedBy'],
        'name': json['name'],
        'appId': json['appId'] == null ? undefined : json['appId'],
        'revision': json['revision'] == null ? undefined : json['revision'],
        'uniqueId': json['uniqueId'] == null ? undefined : json['uniqueId'],
    };
}

export function BasicEntityV2ToJSON(value?: Omit<BasicEntityV2, 'id'|'createdAt'|'createdBy'|'updatedAt'|'updatedBy'|'appId'|'revision'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'uniqueId': value['uniqueId'],
    };
}

