/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BootstrapRequest
 */
export interface BootstrapRequest {
    /**
     * The bootstrap token from /opt/shepard/.bootstrap-token (or shepard.bootstrap.token-path).
     * @type {string}
     * @memberof BootstrapRequest
     */
    token: string;
    /**
     * Username to grant the instance-admin role to.
     * @type {string}
     * @memberof BootstrapRequest
     */
    username: string;
}

/**
 * Check if a given object implements the BootstrapRequest interface.
 */
export function instanceOfBootstrapRequest(value: object): value is BootstrapRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function BootstrapRequestFromJSON(json: any): BootstrapRequest {
    return BootstrapRequestFromJSONTyped(json, false);
}

export function BootstrapRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BootstrapRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'username': json['username'],
    };
}

export function BootstrapRequestToJSON(value?: BootstrapRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
        'username': value['username'],
    };
}

