/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BulkAnnotationItemResult } from './BulkAnnotationItemResult';
import {
    BulkAnnotationItemResultFromJSON,
    BulkAnnotationItemResultToJSON,
} from './BulkAnnotationItemResult';

/**
 * Response from POST /v2/annotations/bulk.
 * @export
 * @interface BulkAnnotationResult
 */
export interface BulkAnnotationResult {
    /**
     * Number of annotation rows in the request.
     * @type {number}
     * @memberof BulkAnnotationResult
     */
    requested: number;
    /**
     * Number of rows that succeeded.
     * @type {number}
     * @memberof BulkAnnotationResult
     */
    succeeded: number;
    /**
     * Number of rows that failed.
     * @type {number}
     * @memberof BulkAnnotationResult
     */
    failed: number;
    /**
     * Per-row results, in the same order as the request items.
     * @type {Array<BulkAnnotationItemResult>}
     * @memberof BulkAnnotationResult
     */
    results: Array<BulkAnnotationItemResult>;
}

/**
 * Check if a given object implements the BulkAnnotationResult interface.
 */
export function instanceOfBulkAnnotationResult(value: object): value is BulkAnnotationResult {
    if (!('requested' in value) || value['requested'] === undefined) return false;
    if (!('succeeded' in value) || value['succeeded'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function BulkAnnotationResultFromJSON(json: any): BulkAnnotationResult {
    return BulkAnnotationResultFromJSONTyped(json, false);
}

export function BulkAnnotationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkAnnotationResult {
    if (json == null) {
        return json;
    }
    return {
        'requested': json['requested'],
        'succeeded': json['succeeded'],
        'failed': json['failed'],
        'results': (json['results'] as Array<any>).map(BulkAnnotationItemResultFromJSON),
    };
}

export function BulkAnnotationResultToJSON(value?: BulkAnnotationResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        'requested': value['requested'],
        'succeeded': value['succeeded'],
        'failed': value['failed'],
        'results': value['results'].map(BulkAnnotationItemResultToJSON),
    };
}
