/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One Excel cell mapping: optional worksheet name + A1-style cell ref.
 * @export
 * @interface CellMappingIO
 */
export interface CellMappingIO {
    /**
     * Worksheet name (urn:btkvs:sheet).
     * @type {string}
     * @memberof CellMappingIO
     */
    sheet?: string | null;
    /**
     * A1-style cell reference (urn:btkvs:cell-mapping).
     * @type {string}
     * @memberof CellMappingIO
     */
    cell?: string | null;
}

/**
 * Check if a given object implements the CellMappingIO interface.
 */
export function instanceOfCellMappingIO(value: object): value is CellMappingIO {
    return true;
}

export function CellMappingIOFromJSON(json: any): CellMappingIO {
    return CellMappingIOFromJSONTyped(json, false);
}

export function CellMappingIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CellMappingIO {
    if (json == null) {
        return json;
    }
    return {
        
        'sheet': json['sheet'] == null ? undefined : json['sheet'],
        'cell': json['cell'] == null ? undefined : json['cell'],
    };
}

export function CellMappingIOToJSON(value?: CellMappingIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sheet': value['sheet'],
        'cell': value['cell'],
    };
}

