/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResolvedChannelIO } from './ResolvedChannelIO';
import {
    ResolvedChannelIOFromJSON,
    ResolvedChannelIOFromJSONTyped,
    ResolvedChannelIOToJSON,
} from './ResolvedChannelIO';

/**
 * One channel-binding slot from the VIEW_RECIPE template.
 * @export
 * @interface ChannelBindingProjectionIO
 */
export interface ChannelBindingProjectionIO {
    /**
     * Renderer-facing role name (x, y, z, time, color, size, …). Conventions are per-renderer-family; Trace3D uses x/y/z/color.
     * @type {string}
     * @memberof ChannelBindingProjectionIO
     */
    role?: string;
    /**
     * Channel selector as declared in the template. Today: JSON-encoded 5-tuple {measurement, device, location, symbolicName, field}. Post TS-ID migration (aidocs/platform/87): a single appId string.
     * @type {string}
     * @memberof ChannelBindingProjectionIO
     */
    channelSelector?: string;
    /**
     * Expected QUDT unit IRI (e.g. 'http://qudt.org/vocab/unit/MilliM'). Null when the template declares no unit expectation.
     * @type {string}
     * @memberof ChannelBindingProjectionIO
     */
    unit?: string | null;
    /**
     * If true the renderer cannot operate when this binding is MISSING. If false the renderer degrades gracefully (omits the dimension).
     * @type {boolean}
     * @memberof ChannelBindingProjectionIO
     */
    required?: boolean;
    /**
     * Resolution status: DECLARED (beta) | OK | MISSING | UNIT_MISMATCH. In this beta release always DECLARED — live resolution ships in TPL2c.
     * @type {string}
     * @memberof ChannelBindingProjectionIO
     */
    status?: string;
    /**
     * Resolved channel reference. Null in the beta release. In TPL2c: non-null when status=OK, containing the TS reference appId.
     * @type {ResolvedChannelIO}
     * @memberof ChannelBindingProjectionIO
     */
    resolved?: ResolvedChannelIO | null;
}

/**
 * Check if a given object implements the ChannelBindingProjectionIO interface.
 */
export function instanceOfChannelBindingProjectionIO(value: object): value is ChannelBindingProjectionIO {
    return true;
}

export function ChannelBindingProjectionIOFromJSON(json: any): ChannelBindingProjectionIO {
    return ChannelBindingProjectionIOFromJSONTyped(json, false);
}

export function ChannelBindingProjectionIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelBindingProjectionIO {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'] == null ? undefined : json['role'],
        'channelSelector': json['channelSelector'] == null ? undefined : json['channelSelector'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'required': json['required'] == null ? undefined : json['required'],
        'status': json['status'] == null ? undefined : json['status'],
        'resolved': json['resolved'] == null ? undefined : ResolvedChannelIOFromJSON(json['resolved']),
    };
}

export function ChannelBindingProjectionIOToJSON(value?: ChannelBindingProjectionIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'role': value['role'],
        'channelSelector': value['channelSelector'],
        'unit': value['unit'],
        'required': value['required'],
        'status': value['status'],
        'resolved': ResolvedChannelIOToJSON(value['resolved']),
    };
}

