/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Assign a spatial axis role to a timeseries channel (TS-AXIS-AUTO).
 * @export
 * @interface ChannelAxisAnnotationIO
 */
export interface ChannelAxisAnnotationIO {
    /**
     * Axis role to assign to this channel. Accepted values: x, y, z, rot_a, rot_b, rot_c.
     * @type {string}
     * @memberof ChannelAxisAnnotationIO
     */
    value: string;
}

/**
 * Check if a given object implements the ChannelAxisAnnotationIO interface.
 */
export function instanceOfChannelAxisAnnotationIO(value: object): value is ChannelAxisAnnotationIO {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ChannelAxisAnnotationIOFromJSON(json: any): ChannelAxisAnnotationIO {
    return ChannelAxisAnnotationIOFromJSONTyped(json, false);
}

export function ChannelAxisAnnotationIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelAxisAnnotationIO {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function ChannelAxisAnnotationIOToJSON(value?: ChannelAxisAnnotationIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'value': value['value'],
    };
}

