/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionReference
 */
export interface CollectionReference {
    /**
     * 
     * @type {number}
     * @memberof CollectionReference
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof CollectionReference
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CollectionReference
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof CollectionReference
     */
    readonly updatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CollectionReference
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof CollectionReference
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CollectionReference
     */
    readonly dataObjectId?: number;
    /**
     * 
     * @type {string}
     * @memberof CollectionReference
     */
    readonly type?: string;
    /**
     * 
     * @type {number}
     * @memberof CollectionReference
     */
    referencedCollectionId: number;
    /**
     * 
     * @type {string}
     * @memberof CollectionReference
     */
    relationship?: string | null;
}

/**
 * Check if a given object implements the CollectionReference interface.
 */
export function instanceOfCollectionReference(value: object): value is CollectionReference {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('referencedCollectionId' in value) || value['referencedCollectionId'] === undefined) return false;
    return true;
}

export function CollectionReferenceFromJSON(json: any): CollectionReference {
    return CollectionReferenceFromJSONTyped(json, false);
}

export function CollectionReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionReference {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'createdBy': json['createdBy'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
        'updatedBy': json['updatedBy'],
        'name': json['name'],
        'dataObjectId': json['dataObjectId'] == null ? undefined : json['dataObjectId'],
        'type': json['type'] == null ? undefined : json['type'],
        'referencedCollectionId': json['referencedCollectionId'],
        'relationship': json['relationship'] == null ? undefined : json['relationship'],
    };
}

export function CollectionReferenceToJSON(value?: Omit<CollectionReference, 'id'|'createdAt'|'createdBy'|'updatedAt'|'updatedBy'|'dataObjectId'|'type'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'referencedCollectionId': value['referencedCollectionId'],
        'relationship': value['relationship'],
    };
}

