/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Single time-bin row inside a CollectionTimelineLane.
 * @export
 * @interface CollectionTimelineBinIO
 */
export interface CollectionTimelineBinIO {
    /**
     * First day of the bin window (UTC ISO date, e.g. "2023-04-15").
     * @type {string}
     * @memberof CollectionTimelineBinIO
     */
    day?: string;
    /**
     * Total DataObjects whose anchor timestamp falls in this bin.
     * @type {number}
     * @memberof CollectionTimelineBinIO
     */
    count?: number;
    /**
     * DataObjects whose status is NCR-flavoured (NCR_OPEN, CONCESSION_PENDING). Counted from the same set as count — ncrCount <= count.
     * @type {number}
     * @memberof CollectionTimelineBinIO
     */
    ncrCount?: number;
    /**
     * DataObjects whose status is REJECTED. Counted from the same set as count — rejectCount <= count.
     * @type {number}
     * @memberof CollectionTimelineBinIO
     */
    rejectCount?: number;
}

/**
 * Check if a given object implements the CollectionTimelineBinIO interface.
 */
export function instanceOfCollectionTimelineBinIO(value: object): value is CollectionTimelineBinIO {
    return true;
}

export function CollectionTimelineBinIOFromJSON(json: any): CollectionTimelineBinIO {
    return CollectionTimelineBinIOFromJSONTyped(json, false);
}

export function CollectionTimelineBinIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionTimelineBinIO {
    if (json == null) {
        return json;
    }
    return {
        
        'day': json['day'] == null ? undefined : json['day'],
        'count': json['count'] == null ? undefined : json['count'],
        'ncrCount': json['ncrCount'] == null ? undefined : json['ncrCount'],
        'rejectCount': json['rejectCount'] == null ? undefined : json['rejectCount'],
    };
}

export function CollectionTimelineBinIOToJSON(value?: CollectionTimelineBinIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'day': value['day'],
        'count': value['count'],
        'ncrCount': value['ncrCount'],
        'rejectCount': value['rejectCount'],
    };
}

