/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A runtime-configurable feature exposed under /v2/admin/config/{feature}.
 * @export
 * @interface ConfigFeature
 */
export interface ConfigFeature {
    /**
     * The {feature} path segment, e.g. 'semantic'.
     * @type {string}
     * @memberof ConfigFeature
     */
    feature?: string;
    /**
     * Human-readable description of what this config controls.
     * @type {string}
     * @memberof ConfigFeature
     */
    description?: string;
}

/**
 * Check if a given object implements the ConfigFeature interface.
 */
export function instanceOfConfigFeature(value: object): value is ConfigFeature {
    return true;
}

export function ConfigFeatureFromJSON(json: any): ConfigFeature {
    return ConfigFeatureFromJSONTyped(json, false);
}

export function ConfigFeatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigFeature {
    if (json == null) {
        return json;
    }
    return {
        
        'feature': json['feature'] == null ? undefined : json['feature'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ConfigFeatureToJSON(value?: ConfigFeature | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'feature': value['feature'],
        'description': value['description'],
    };
}

