/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Compact link from a DataObject reference node to its container.
 * @export
 * @interface ContainerRef
 */
export interface ContainerRef {
    /**
     * appId of the container (UUID v7).
     * @type {string}
     * @memberof ContainerRef
     */
    readonly containerAppId?: string;
    /**
     * Human-readable name of the container.
     * @type {string}
     * @memberof ContainerRef
     */
    readonly containerName?: string;
    /**
     * Legacy long OGM id of the container node. Used by /v2/timeseries-containers/{containerId}/stats and /shepard/api/timeseriesContainers/{containerId}/available.
     * @type {number}
     * @memberof ContainerRef
     */
    readonly containerId?: number;
    /**
     * Legacy long id of the reference node (upstream-compat). Used by /shepard/api/.../timeseriesReferences/{referenceId}/payload.
     * @type {number}
     * @memberof ContainerRef
     */
    readonly referenceId?: number;
    /**
     * UUID v7 of the reference node. Null on pre-L2a rows.
     * @type {string}
     * @memberof ContainerRef
     */
    readonly referenceAppId?: string | null;
}

/**
 * Check if a given object implements the ContainerRef interface.
 */
export function instanceOfContainerRef(value: object): value is ContainerRef {
    return true;
}

export function ContainerRefFromJSON(json: any): ContainerRef {
    return ContainerRefFromJSONTyped(json, false);
}

export function ContainerRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerRef {
    if (json == null) {
        return json;
    }
    return {
        
        'containerAppId': json['containerAppId'] == null ? undefined : json['containerAppId'],
        'containerName': json['containerName'] == null ? undefined : json['containerName'],
        'containerId': json['containerId'] == null ? undefined : json['containerId'],
        'referenceId': json['referenceId'] == null ? undefined : json['referenceId'],
        'referenceAppId': json['referenceAppId'] == null ? undefined : json['referenceAppId'],
    };
}

export function ContainerRefToJSON(value?: Omit<ContainerRef, 'containerAppId'|'containerName'|'containerId'|'referenceId'|'referenceAppId'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

