/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFileGroup
 */
export interface CreateFileGroup {
    /**
     * Display name; need not be unique within the bundle.
     * @type {string}
     * @memberof CreateFileGroup
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFileGroup
     */
    description?: string | null;
    /**
     * 0-based index. Server-assigned when absent.
     * @type {number}
     * @memberof CreateFileGroup
     */
    index?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof CreateFileGroup
     */
    startedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof CreateFileGroup
     */
    endedAt?: Date | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CreateFileGroup
     */
    attributes?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the CreateFileGroup interface.
 */
export function instanceOfCreateFileGroup(value: object): value is CreateFileGroup {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateFileGroupFromJSON(json: any): CreateFileGroup {
    return CreateFileGroupFromJSONTyped(json, false);
}

export function CreateFileGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFileGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'index': json['index'] == null ? undefined : json['index'],
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
        'endedAt': json['endedAt'] == null ? undefined : (new Date(json['endedAt'])),
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
    };
}

export function CreateFileGroupToJSON(value?: CreateFileGroup | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
        'index': value['index'],
        'startedAt': value['startedAt'] == null ? undefined : ((value['startedAt'] as any).toISOString()),
        'endedAt': value['endedAt'] == null ? undefined : ((value['endedAt'] as any).toISOString()),
        'attributes': value['attributes'],
    };
}

