/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * SEMA-V6-004 — request body for creating a semantic annotation.
 * @export
 * @interface CreateAnnotationV2
 */
export interface CreateAnnotationV2 {
    /**
     * appId of the entity to annotate (DataObject, Collection, etc.).
     * @type {string}
     * @memberof CreateAnnotationV2
     */
    subjectAppId: string;
    /**
     * Kind of the entity to annotate (e.g. 'DataObject', 'Collection').
     * @type {string}
     * @memberof CreateAnnotationV2
     */
    subjectKind: string;
    /**
     * IRI of the predicate (from a registered vocabulary).
     * @type {string}
     * @memberof CreateAnnotationV2
     */
    predicateIri: string;
    /**
     * Human-readable label for the predicate (snapshot; resolved if null).
     * @type {string}
     * @memberof CreateAnnotationV2
     */
    predicateLabel?: string | null;
    /**
     * Literal text value. Exactly one of objectLiteral / objectIri must be non-null.
     * @type {string}
     * @memberof CreateAnnotationV2
     */
    objectLiteral?: string | null;
    /**
     * IRI-typed object value. Exactly one of objectLiteral / objectIri must be non-null.
     * @type {string}
     * @memberof CreateAnnotationV2
     */
    objectIri?: string | null;
    /**
     * QA-1 numeric value (for quantitative annotations).
     * @type {number}
     * @memberof CreateAnnotationV2
     */
    numericValue?: number | null;
    /**
     * QA-1 unit IRI (for quantitative annotations).
     * @type {string}
     * @memberof CreateAnnotationV2
     */
    unitIri?: string | null;
    /**
     * appId of the Vocabulary supplying this predicate.
     * @type {string}
     * @memberof CreateAnnotationV2
     */
    vocabularyId?: string | null;
    /**
     * f(ai)²r source mode: 'human', 'ai', or 'collaborative'. Defaults to 'human'.
     * @type {string}
     * @memberof CreateAnnotationV2
     */
    sourceMode?: string | null;
    /**
     * appId of the Activity that triggered this annotation (for AI/collaborative modes).
     * @type {string}
     * @memberof CreateAnnotationV2
     */
    sourceActivityAppId?: string | null;
    /**
     * Epoch-millis start of temporal validity. Null = valid from creation.
     * @type {number}
     * @memberof CreateAnnotationV2
     */
    validFromMillis?: number | null;
    /**
     * Epoch-millis end of temporal validity. Null = currently asserted.
     * @type {number}
     * @memberof CreateAnnotationV2
     */
    validUntilMillis?: number | null;
    /**
     * Confidence score [0.0, 1.0]. Defaults to 1.0 for human writes.
     * @type {number}
     * @memberof CreateAnnotationV2
     */
    confidence?: number | null;
}

/**
 * Check if a given object implements the CreateAnnotationV2 interface.
 */
export function instanceOfCreateAnnotationV2(value: object): value is CreateAnnotationV2 {
    if (!('subjectAppId' in value) || value['subjectAppId'] === undefined) return false;
    if (!('subjectKind' in value) || value['subjectKind'] === undefined) return false;
    if (!('predicateIri' in value) || value['predicateIri'] === undefined) return false;
    return true;
}

export function CreateAnnotationV2FromJSON(json: any): CreateAnnotationV2 {
    return CreateAnnotationV2FromJSONTyped(json, false);
}

export function CreateAnnotationV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAnnotationV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'subjectAppId': json['subjectAppId'],
        'subjectKind': json['subjectKind'],
        'predicateIri': json['predicateIri'],
        'predicateLabel': json['predicateLabel'] == null ? undefined : json['predicateLabel'],
        'objectLiteral': json['objectLiteral'] == null ? undefined : json['objectLiteral'],
        'objectIri': json['objectIri'] == null ? undefined : json['objectIri'],
        'numericValue': json['numericValue'] == null ? undefined : json['numericValue'],
        'unitIri': json['unitIri'] == null ? undefined : json['unitIri'],
        'vocabularyId': json['vocabularyId'] == null ? undefined : json['vocabularyId'],
        'sourceMode': json['sourceMode'] == null ? undefined : json['sourceMode'],
        'sourceActivityAppId': json['sourceActivityAppId'] == null ? undefined : json['sourceActivityAppId'],
        'validFromMillis': json['validFromMillis'] == null ? undefined : json['validFromMillis'],
        'validUntilMillis': json['validUntilMillis'] == null ? undefined : json['validUntilMillis'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
    };
}

export function CreateAnnotationV2ToJSON(value?: CreateAnnotationV2 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'subjectAppId': value['subjectAppId'],
        'subjectKind': value['subjectKind'],
        'predicateIri': value['predicateIri'],
        'predicateLabel': value['predicateLabel'],
        'objectLiteral': value['objectLiteral'],
        'objectIri': value['objectIri'],
        'numericValue': value['numericValue'],
        'unitIri': value['unitIri'],
        'vocabularyId': value['vocabularyId'],
        'sourceMode': value['sourceMode'],
        'sourceActivityAppId': value['sourceActivityAppId'],
        'validFromMillis': value['validFromMillis'],
        'validUntilMillis': value['validUntilMillis'],
        'confidence': value['confidence'],
    };
}

