/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypedPredecessor } from './TypedPredecessor';
import {
    TypedPredecessorFromJSON,
    TypedPredecessorFromJSONTyped,
    TypedPredecessorToJSON,
} from './TypedPredecessor';

/**
 * v2 DataObject create request body. Extends DataObjectIO with the optional `provenanceMode` field (EU AI Act Art. 50 per-artefact visibility). When omitted, the server auto-detects from the X-AI-Agent request header.
 * @export
 * @interface CreateDataObjectV2
 */
export interface CreateDataObjectV2 {
    /**
     * 
     * @type {number}
     * @memberof CreateDataObjectV2
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof CreateDataObjectV2
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateDataObjectV2
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateDataObjectV2
     */
    readonly updatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CreateDataObjectV2
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateDataObjectV2
     */
    name: string;
    /**
     * Application-level UUID v7 identifier.
     * @type {string}
     * @memberof CreateDataObjectV2
     */
    readonly appId?: string | null;
    /**
     * Write counter (V2a revision). 0 for non-versionable entities.
     * @type {number}
     * @memberof CreateDataObjectV2
     */
    readonly revision?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateDataObjectV2
     */
    description?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CreateDataObjectV2
     */
    attributes?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof CreateDataObjectV2
     */
    status?: CreateDataObjectV2StatusEnum | null;
    /**
     * 
     * @type {string}
     * @memberof CreateDataObjectV2
     */
    license?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateDataObjectV2
     */
    accessRights?: CreateDataObjectV2AccessRightsEnum | null;
    /**
     * FAIR2: ORCID of the creator, stamped server-side at creation. Read-only — not accepted as input. Absent when null or creator had no ORCID set.
     * @type {string}
     * @memberof CreateDataObjectV2
     */
    readonly createdByOrcid?: string | null;
    /**
     * ISO-8601 date (e.g. '2027-12-31') after which the embargo lifts; only meaningful when accessRights=EMBARGOED.
     * @type {string}
     * @memberof CreateDataObjectV2
     */
    embargoEndDate?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateDataObjectV2
     */
    readonly collectionId: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateDataObjectV2
     */
    readonly referenceIds: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateDataObjectV2
     */
    readonly successorIds: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateDataObjectV2
     */
    predecessorIds?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateDataObjectV2
     */
    readonly childrenIds: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof CreateDataObjectV2
     */
    parentId: number | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateDataObjectV2
     */
    readonly incomingIds: Array<number>;
    /**
     * Deprecated — use `timeseriesCount` on the /v2/ DataObjectListItemV2 shape instead. This int includes soft-deleted references; the v2 long field counts non-deleted only.
     * @type {number}
     * @memberof CreateDataObjectV2
     * @deprecated
     */
    readonly timeseriesReferenceCount: number;
    /**
     * Deprecated — use `fileCount` on the /v2/ DataObjectListItemV2 shape instead. This int counts only FileBundleReference nodes (FR1a); the v2 long also counts SingletonFileReference (FR1b) and excludes soft-deleted references.
     * @type {number}
     * @memberof CreateDataObjectV2
     * @deprecated
     */
    readonly fileBundleCount: number;
    /**
     * Deprecated — use `structuredDataCount` on the /v2/ DataObjectListItemV2 shape instead. This int includes soft-deleted references; the v2 long field counts non-deleted only.
     * @type {number}
     * @memberof CreateDataObjectV2
     * @deprecated
     */
    readonly structuredDataReferenceCount: number;
    /**
     * TOOLS-CONTEXT-DO-TEMPLATE-DETECT-1: appId of the :ShepardTemplate this DataObject was created from. Stamped server-side at create time; read-only. Absent from the wire when null.
     * @type {string}
     * @memberof CreateDataObjectV2
     */
    readonly attachedTemplateAppId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateDataObjectV2
     */
    readonly videoStreamReferenceCount: number;
    /**
     * EU AI Act Art. 50 provenance mode: 'human', 'ai', or 'collaborative'. When omitted, auto-detected from the X-AI-Agent request header. Null in the response means human-authored (default).
     * @type {string}
     * @memberof CreateDataObjectV2
     */
    provenanceMode?: CreateDataObjectV2ProvenanceModeEnum | null;
    /**
     * PROV1k — typed predecessor relationships. When provided, overrides predecessorIds. Each entry must name a predecessorAppId (UUID v7, same collection) and an optional relationshipType ('prov:wasInformedBy' default, 'prov:wasRevisionOf', 'fair2r:repairs').
     * @type {Array<TypedPredecessor>}
     * @memberof CreateDataObjectV2
     */
    typedPredecessors?: Array<TypedPredecessor> | null;
}


/**
 * @export
 */
export const CreateDataObjectV2StatusEnum = {
    Draft: 'DRAFT',
    InReview: 'IN_REVIEW',
    Ready: 'READY',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED',
    NcrOpen: 'NCR_OPEN',
    OnHold: 'ON_HOLD',
    Rejected: 'REJECTED',
    Certified: 'CERTIFIED',
    ConcessionPending: 'CONCESSION_PENDING'
} as const;
export type CreateDataObjectV2StatusEnum = typeof CreateDataObjectV2StatusEnum[keyof typeof CreateDataObjectV2StatusEnum];

/**
 * @export
 */
export const CreateDataObjectV2AccessRightsEnum = {
    Open: 'OPEN',
    Restricted: 'RESTRICTED',
    Closed: 'CLOSED',
    Embargoed: 'EMBARGOED'
} as const;
export type CreateDataObjectV2AccessRightsEnum = typeof CreateDataObjectV2AccessRightsEnum[keyof typeof CreateDataObjectV2AccessRightsEnum];

/**
 * @export
 */
export const CreateDataObjectV2ProvenanceModeEnum = {
    Human: 'human',
    Ai: 'ai',
    Collaborative: 'collaborative'
} as const;
export type CreateDataObjectV2ProvenanceModeEnum = typeof CreateDataObjectV2ProvenanceModeEnum[keyof typeof CreateDataObjectV2ProvenanceModeEnum];


/**
 * Check if a given object implements the CreateDataObjectV2 interface.
 */
export function instanceOfCreateDataObjectV2(value: object): value is CreateDataObjectV2 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('collectionId' in value) || value['collectionId'] === undefined) return false;
    if (!('referenceIds' in value) || value['referenceIds'] === undefined) return false;
    if (!('successorIds' in value) || value['successorIds'] === undefined) return false;
    if (!('childrenIds' in value) || value['childrenIds'] === undefined) return false;
    if (!('parentId' in value) || value['parentId'] === undefined) return false;
    if (!('incomingIds' in value) || value['incomingIds'] === undefined) return false;
    if (!('timeseriesReferenceCount' in value) || value['timeseriesReferenceCount'] === undefined) return false;
    if (!('fileBundleCount' in value) || value['fileBundleCount'] === undefined) return false;
    if (!('structuredDataReferenceCount' in value) || value['structuredDataReferenceCount'] === undefined) return false;
    if (!('videoStreamReferenceCount' in value) || value['videoStreamReferenceCount'] === undefined) return false;
    return true;
}

export function CreateDataObjectV2FromJSON(json: any): CreateDataObjectV2 {
    return CreateDataObjectV2FromJSONTyped(json, false);
}

export function CreateDataObjectV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDataObjectV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'createdBy': json['createdBy'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
        'updatedBy': json['updatedBy'],
        'name': json['name'],
        'appId': json['appId'] == null ? undefined : json['appId'],
        'revision': json['revision'] == null ? undefined : json['revision'],
        'description': json['description'] == null ? undefined : json['description'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'status': json['status'] == null ? undefined : json['status'],
        'license': json['license'] == null ? undefined : json['license'],
        'accessRights': json['accessRights'] == null ? undefined : json['accessRights'],
        'createdByOrcid': json['createdByOrcid'] == null ? undefined : json['createdByOrcid'],
        'embargoEndDate': json['embargoEndDate'] == null ? undefined : json['embargoEndDate'],
        'collectionId': json['collectionId'],
        'referenceIds': json['referenceIds'],
        'successorIds': json['successorIds'],
        'predecessorIds': json['predecessorIds'] == null ? undefined : json['predecessorIds'],
        'childrenIds': json['childrenIds'],
        'parentId': json['parentId'],
        'incomingIds': json['incomingIds'],
        'timeseriesReferenceCount': json['timeseriesReferenceCount'],
        'fileBundleCount': json['fileBundleCount'],
        'structuredDataReferenceCount': json['structuredDataReferenceCount'],
        'attachedTemplateAppId': json['attachedTemplateAppId'] == null ? undefined : json['attachedTemplateAppId'],
        'videoStreamReferenceCount': json['videoStreamReferenceCount'],
        'provenanceMode': json['provenanceMode'] == null ? undefined : json['provenanceMode'],
        'typedPredecessors': json['typedPredecessors'] == null ? undefined : ((json['typedPredecessors'] as Array<any>).map(TypedPredecessorFromJSON)),
    };
}

export function CreateDataObjectV2ToJSON(value?: Omit<CreateDataObjectV2, 'id'|'createdAt'|'createdBy'|'updatedAt'|'updatedBy'|'appId'|'revision'|'createdByOrcid'|'collectionId'|'referenceIds'|'successorIds'|'childrenIds'|'incomingIds'|'timeseriesReferenceCount'|'fileBundleCount'|'structuredDataReferenceCount'|'attachedTemplateAppId'|'videoStreamReferenceCount'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
        'attributes': value['attributes'],
        'status': value['status'],
        'license': value['license'],
        'accessRights': value['accessRights'],
        'embargoEndDate': value['embargoEndDate'],
        'predecessorIds': value['predecessorIds'],
        'parentId': value['parentId'],
        'provenanceMode': value['provenanceMode'],
        'typedPredecessors': value['typedPredecessors'] == null ? undefined : ((value['typedPredecessors'] as Array<any>).map(TypedPredecessorToJSON)),
    };
}

