/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataObjectReference
 */
export interface DataObjectReference {
    /**
     * 
     * @type {number}
     * @memberof DataObjectReference
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof DataObjectReference
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof DataObjectReference
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof DataObjectReference
     */
    readonly updatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof DataObjectReference
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataObjectReference
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof DataObjectReference
     */
    readonly dataObjectId?: number;
    /**
     * 
     * @type {string}
     * @memberof DataObjectReference
     */
    readonly type?: string;
    /**
     * 
     * @type {number}
     * @memberof DataObjectReference
     */
    referencedDataObjectId: number;
    /**
     * 
     * @type {string}
     * @memberof DataObjectReference
     */
    relationship?: string | null;
}

/**
 * Check if a given object implements the DataObjectReference interface.
 */
export function instanceOfDataObjectReference(value: object): value is DataObjectReference {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('referencedDataObjectId' in value) || value['referencedDataObjectId'] === undefined) return false;
    return true;
}

export function DataObjectReferenceFromJSON(json: any): DataObjectReference {
    return DataObjectReferenceFromJSONTyped(json, false);
}

export function DataObjectReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataObjectReference {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'createdBy': json['createdBy'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
        'updatedBy': json['updatedBy'],
        'name': json['name'],
        'dataObjectId': json['dataObjectId'] == null ? undefined : json['dataObjectId'],
        'type': json['type'] == null ? undefined : json['type'],
        'referencedDataObjectId': json['referencedDataObjectId'],
        'relationship': json['relationship'] == null ? undefined : json['relationship'],
    };
}

export function DataObjectReferenceToJSON(value?: Omit<DataObjectReference, 'id'|'createdAt'|'createdBy'|'updatedAt'|'updatedBy'|'dataObjectId'|'type'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'referencedDataObjectId': value['referencedDataObjectId'],
        'relationship': value['relationship'],
    };
}

