/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DQRResultIO
 */
export interface DQRResultIO {
    /**
     * 
     * @type {string}
     * @memberof DQRResultIO
     */
    dqrAppId?: string;
    /**
     * 
     * @type {string}
     * @memberof DQRResultIO
     */
    dataObjectAppId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DQRResultIO
     */
    passed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DQRResultIO
     */
    message?: string;
}

/**
 * Check if a given object implements the DQRResultIO interface.
 */
export function instanceOfDQRResultIO(value: object): value is DQRResultIO {
    return true;
}

export function DQRResultIOFromJSON(json: any): DQRResultIO {
    return DQRResultIOFromJSONTyped(json, false);
}

export function DQRResultIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DQRResultIO {
    if (json == null) {
        return json;
    }
    return {
        
        'dqrAppId': json['dqrAppId'] == null ? undefined : json['dqrAppId'],
        'dataObjectAppId': json['dataObjectAppId'] == null ? undefined : json['dataObjectAppId'],
        'passed': json['passed'] == null ? undefined : json['passed'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function DQRResultIOToJSON(value?: DQRResultIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'dqrAppId': value['dqrAppId'],
        'dataObjectAppId': value['dataObjectAppId'],
        'passed': value['passed'],
        'message': value['message'],
    };
}

