/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EpicTestConnectionIO
 */
export interface EpicTestConnectionIO {
    /**
     *
     * @type {boolean}
     * @memberof EpicTestConnectionIO
     */
    reachable?: boolean;
    /**
     *
     * @type {number}
     * @memberof EpicTestConnectionIO
     */
    statusCode?: number;
    /**
     * ISO 8601 duration of the round-trip probe, e.g. PT0.123S.
     * @type {string}
     * @memberof EpicTestConnectionIO
     */
    latency?: string;
    /**
     *
     * @type {string}
     * @memberof EpicTestConnectionIO
     */
    apiBaseUrl?: string;
    /**
     *
     * @type {string}
     * @memberof EpicTestConnectionIO
     */
    detail?: string;
}

/**
 * Check if a given object implements the EpicTestConnectionIO interface.
 */
export function instanceOfEpicTestConnectionIO(value: object): value is EpicTestConnectionIO {
    return true;
}

export function EpicTestConnectionIOFromJSON(json: any): EpicTestConnectionIO {
    return EpicTestConnectionIOFromJSONTyped(json, false);
}

export function EpicTestConnectionIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EpicTestConnectionIO {
    if (json == null) {
        return json;
    }
    return {

        'reachable': json['reachable'] == null ? undefined : json['reachable'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'latency': json['latency'] == null ? undefined : json['latency'],
        'apiBaseUrl': json['apiBaseUrl'] == null ? undefined : json['apiBaseUrl'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function EpicTestConnectionIOToJSON(value?: EpicTestConnectionIO | null): any {
    if (value == null) {
        return value;
    }
    return {

        'reachable': value['reachable'],
        'statusCode': value['statusCode'],
        'latency': value['latency'],
        'apiBaseUrl': value['apiBaseUrl'],
        'detail': value['detail'],
    };
}
