/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExportSelectionMetadata } from './ExportSelectionMetadata';
import {
    ExportSelectionMetadataFromJSON,
    ExportSelectionMetadataFromJSONTyped,
    ExportSelectionMetadataToJSON,
} from './ExportSelectionMetadata';
import type { ExportSelectionPayloads } from './ExportSelectionPayloads';
import {
    ExportSelectionPayloadsFromJSON,
    ExportSelectionPayloadsFromJSONTyped,
    ExportSelectionPayloadsToJSON,
} from './ExportSelectionPayloads';

/**
 * Optional filter for what payloads and metadata bundle into the RO-Crate export.
 * @export
 * @interface ExportSelection
 */
export interface ExportSelection {
    /**
     * When set, only DataObjects captured in this snapshot are included in the export. Reproducible by construction.
     * @type {string}
     * @memberof ExportSelection
     */
    snapshotAppId?: string | null;
    /**
     * 
     * @type {ExportSelectionPayloads}
     * @memberof ExportSelection
     */
    payloads?: ExportSelectionPayloads;
    /**
     * 
     * @type {ExportSelectionMetadata}
     * @memberof ExportSelection
     */
    metadata?: ExportSelectionMetadata;
    /**
     * 
     * @type {boolean}
     * @memberof ExportSelection
     */
    empty?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExportSelection
     */
    strictPerPayload?: boolean;
}

/**
 * Check if a given object implements the ExportSelection interface.
 */
export function instanceOfExportSelection(value: object): value is ExportSelection {
    return true;
}

export function ExportSelectionFromJSON(json: any): ExportSelection {
    return ExportSelectionFromJSONTyped(json, false);
}

export function ExportSelectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportSelection {
    if (json == null) {
        return json;
    }
    return {
        
        'snapshotAppId': json['snapshotAppId'] == null ? undefined : json['snapshotAppId'],
        'payloads': json['payloads'] == null ? undefined : ExportSelectionPayloadsFromJSON(json['payloads']),
        'metadata': json['metadata'] == null ? undefined : ExportSelectionMetadataFromJSON(json['metadata']),
        'empty': json['empty'] == null ? undefined : json['empty'],
        'strictPerPayload': json['strictPerPayload'] == null ? undefined : json['strictPerPayload'],
    };
}

export function ExportSelectionToJSON(value?: ExportSelection | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'snapshotAppId': value['snapshotAppId'],
        'payloads': ExportSelectionPayloadsToJSON(value['payloads']),
        'metadata': ExportSelectionMetadataToJSON(value['metadata']),
        'empty': value['empty'],
        'strictPerPayload': value['strictPerPayload'],
    };
}

