/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeatureToggle
 */
export interface FeatureToggle {
    /**
     * Stable identifier for the feature toggle.
     * @type {string}
     * @memberof FeatureToggle
     */
    name: string;
    /**
     * Whether the feature is currently enabled.
     * @type {boolean}
     * @memberof FeatureToggle
     */
    enabled: boolean;
    /**
     * Human-readable description of what the toggle controls.
     * @type {string}
     * @memberof FeatureToggle
     */
    description: string;
    /**
     * Origin of the current value: 'runtime' (PATCH-overridden, reverts on restart), 'config' (from application.properties / env), or 'default' (hardcoded default, no explicit config key).
     * @type {string}
     * @memberof FeatureToggle
     */
    source: string;
}

/**
 * Check if a given object implements the FeatureToggle interface.
 */
export function instanceOfFeatureToggle(value: object): value is FeatureToggle {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function FeatureToggleFromJSON(json: any): FeatureToggle {
    return FeatureToggleFromJSONTyped(json, false);
}

export function FeatureToggleFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureToggle {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'enabled': json['enabled'],
        'description': json['description'],
        'source': json['source'],
    };
}

export function FeatureToggleToJSON(value?: FeatureToggle | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'enabled': value['enabled'],
        'description': value['description'],
        'source': value['source'],
    };
}

