/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileGroup } from './FileGroup';
import {
    FileGroupFromJSON,
    FileGroupFromJSONTyped,
    FileGroupToJSON,
} from './FileGroup';

/**
 * 
 * @export
 * @interface FileBundleReference
 */
export interface FileBundleReference {
    /**
     * 
     * @type {number}
     * @memberof FileBundleReference
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof FileBundleReference
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof FileBundleReference
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof FileBundleReference
     */
    readonly updatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof FileBundleReference
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileBundleReference
     */
    name: string;
    /**
     * Write counter (V2a revision). 0 for non-versionable entities.
     * @type {number}
     * @memberof FileBundleReference
     */
    readonly revision?: number;
    /**
     * 
     * @type {number}
     * @memberof FileBundleReference
     */
    readonly dataObjectId?: number;
    /**
     * 
     * @type {string}
     * @memberof FileBundleReference
     */
    readonly type?: string;
    /**
     * Application identifier (UUID v7).
     * @type {string}
     * @memberof FileBundleReference
     */
    readonly appId?: string | null;
    /**
     * Mongo ObjectId of the underlying FileContainer.
     * @type {string}
     * @memberof FileBundleReference
     */
    readonly containerMongoId?: string | null;
    /**
     * Sub-Reference grouping — at least one (the default group, named 'default') for every bundle.
     * @type {Array<FileGroup>}
     * @memberof FileBundleReference
     */
    readonly groups?: Array<FileGroup>;
}

/**
 * Check if a given object implements the FileBundleReference interface.
 */
export function instanceOfFileBundleReference(value: object): value is FileBundleReference {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FileBundleReferenceFromJSON(json: any): FileBundleReference {
    return FileBundleReferenceFromJSONTyped(json, false);
}

export function FileBundleReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileBundleReference {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'createdBy': json['createdBy'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
        'updatedBy': json['updatedBy'],
        'name': json['name'],
        'revision': json['revision'] == null ? undefined : json['revision'],
        'dataObjectId': json['dataObjectId'] == null ? undefined : json['dataObjectId'],
        'type': json['type'] == null ? undefined : json['type'],
        'appId': json['appId'] == null ? undefined : json['appId'],
        'containerMongoId': json['containerMongoId'] == null ? undefined : json['containerMongoId'],
        'groups': json['groups'] == null ? undefined : ((json['groups'] as Array<any>).map(FileGroupFromJSON)),
    };
}

export function FileBundleReferenceToJSON(value?: Omit<FileBundleReference, 'id'|'createdAt'|'createdBy'|'updatedAt'|'updatedBy'|'revision'|'dataObjectId'|'type'|'appId'|'containerMongoId'|'groups'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

