/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FileMigrationStatus = {
    Idle: 'IDLE',
    Running: 'RUNNING',
    Done: 'DONE',
    Failed: 'FAILED'
} as const;
export type FileMigrationStatus = typeof FileMigrationStatus[keyof typeof FileMigrationStatus];


export function instanceOfFileMigrationStatus(value: any): boolean {
    for (const key in FileMigrationStatus) {
        if (Object.prototype.hasOwnProperty.call(FileMigrationStatus, key)) {
            if (FileMigrationStatus[key as keyof typeof FileMigrationStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FileMigrationStatusFromJSON(json: any): FileMigrationStatus {
    return FileMigrationStatusFromJSONTyped(json, false);
}

export function FileMigrationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileMigrationStatus {
    return json as FileMigrationStatus;
}

export function FileMigrationStatusToJSON(value?: FileMigrationStatus | null): any {
    return value as any;
}

