/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileMigrationTriggerIO
 */
export interface FileMigrationTriggerIO {
    /**
     * Id of the storage adapter to migrate files away from.
     * @type {string}
     * @memberof FileMigrationTriggerIO
     */
    sourceProviderId: string;
    /**
     * Id of the storage adapter to migrate files to.
     * @type {string}
     * @memberof FileMigrationTriggerIO
     */
    targetProviderId: string;
}

/**
 * Check if a given object implements the FileMigrationTriggerIO interface.
 */
export function instanceOfFileMigrationTriggerIO(value: object): value is FileMigrationTriggerIO {
    if (!('sourceProviderId' in value) || value['sourceProviderId'] === undefined) return false;
    if (!('targetProviderId' in value) || value['targetProviderId'] === undefined) return false;
    return true;
}

export function FileMigrationTriggerIOFromJSON(json: any): FileMigrationTriggerIO {
    return FileMigrationTriggerIOFromJSONTyped(json, false);
}

export function FileMigrationTriggerIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileMigrationTriggerIO {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceProviderId': json['sourceProviderId'],
        'targetProviderId': json['targetProviderId'],
    };
}

export function FileMigrationTriggerIOToJSON(value?: FileMigrationTriggerIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sourceProviderId': value['sourceProviderId'],
        'targetProviderId': value['targetProviderId'],
    };
}

