/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileReference
 */
export interface FileReference {
    /**
     *
     * @type {number}
     * @memberof FileReference
     */
    readonly id: number;
    /**
     * Application-level UUID v7 identifier. See TimeseriesReference for the
     * full reason this is included on the patched client.
     * @type {string}
     * @memberof FileReference
     */
    readonly appId?: string;
    /**
     * 
     * @type {Date}
     * @memberof FileReference
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof FileReference
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof FileReference
     */
    readonly updatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof FileReference
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileReference
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof FileReference
     */
    readonly dataObjectId?: number;
    /**
     * 
     * @type {string}
     * @memberof FileReference
     */
    readonly type?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FileReference
     */
    fileOids: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof FileReference
     */
    fileContainerId: number;
}

/**
 * Check if a given object implements the FileReference interface.
 */
export function instanceOfFileReference(value: object): value is FileReference {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('fileOids' in value) || value['fileOids'] === undefined) return false;
    if (!('fileContainerId' in value) || value['fileContainerId'] === undefined) return false;
    return true;
}

export function FileReferenceFromJSON(json: any): FileReference {
    return FileReferenceFromJSONTyped(json, false);
}

export function FileReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileReference {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'appId': json['appId'] == null ? undefined : json['appId'],
        'createdAt': (new Date(json['createdAt'])),
        'createdBy': json['createdBy'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
        'updatedBy': json['updatedBy'],
        'name': json['name'],
        'dataObjectId': json['dataObjectId'] == null ? undefined : json['dataObjectId'],
        'type': json['type'] == null ? undefined : json['type'],
        'fileOids': json['fileOids'],
        'fileContainerId': json['fileContainerId'],
    };
}

export function FileReferenceToJSON(value?: Omit<FileReference, 'id'|'createdAt'|'createdBy'|'updatedAt'|'updatedBy'|'dataObjectId'|'type'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'fileOids': value['fileOids'],
        'fileContainerId': value['fileContainerId'],
    };
}

