/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContainerType } from './ContainerType';
import {
    ContainerTypeFromJSON,
    ContainerTypeFromJSONTyped,
    ContainerTypeToJSON,
} from './ContainerType';

/**
 * 
 * @export
 * @interface FileContainer
 */
export interface FileContainer {
    /**
     * 
     * @type {number}
     * @memberof FileContainer
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof FileContainer
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof FileContainer
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof FileContainer
     */
    readonly updatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof FileContainer
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileContainer
     */
    name: string;
    /**
     * 
     * @type {ContainerType}
     * @memberof FileContainer
     */
    readonly type: ContainerType;
    /**
     * 
     * @type {string}
     * @memberof FileContainer
     */
    readonly oid: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof FileContainer
     */
    readonly defaultCollectionIdList?: Array<number> | null;
}



/**
 * Check if a given object implements the FileContainer interface.
 */
export function instanceOfFileContainer(value: object): value is FileContainer {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('oid' in value) || value['oid'] === undefined) return false;
    return true;
}

export function FileContainerFromJSON(json: any): FileContainer {
    return FileContainerFromJSONTyped(json, false);
}

export function FileContainerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileContainer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'createdBy': json['createdBy'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
        'updatedBy': json['updatedBy'],
        'name': json['name'],
        'type': ContainerTypeFromJSON(json['type']),
        'oid': json['oid'],
        'defaultCollectionIdList': json['defaultCollectionIdList'] == null ? undefined : json['defaultCollectionIdList'],
    };
}

export function FileContainerToJSON(value?: Omit<FileContainer, 'id'|'createdAt'|'createdBy'|'updatedAt'|'updatedBy'|'type'|'oid'|'defaultCollectionIdList'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

