/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One SHACL violation.
 * @export
 * @interface FindingIO
 */
export interface FindingIO {
    /**
     * IRI (or blank-node label) of the node the violation is attached to.
     * @type {string}
     * @memberof FindingIO
     */
    focusNode?: string | null;
    /**
     * SHACL property path that triggered the violation, stringified. Null for node-level violations.
     * @type {string}
     * @memberof FindingIO
     */
    resultPath?: string | null;
    /**
     * Offending value (lexical form for literals, IRI for resources).
     * @type {string}
     * @memberof FindingIO
     */
    value?: string | null;
    /**
     * Severity: Violation | Warning | Info.
     * @type {string}
     * @memberof FindingIO
     */
    severity?: string;
    /**
     * sh:resultMessage where the shape supplies one; empty string otherwise.
     * @type {string}
     * @memberof FindingIO
     */
    message?: string;
}

/**
 * Check if a given object implements the FindingIO interface.
 */
export function instanceOfFindingIO(value: object): value is FindingIO {
    return true;
}

export function FindingIOFromJSON(json: any): FindingIO {
    return FindingIOFromJSONTyped(json, false);
}

export function FindingIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindingIO {
    if (json == null) {
        return json;
    }
    return {
        
        'focusNode': json['focusNode'] == null ? undefined : json['focusNode'],
        'resultPath': json['resultPath'] == null ? undefined : json['resultPath'],
        'value': json['value'] == null ? undefined : json['value'],
        'severity': json['severity'] == null ? undefined : json['severity'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function FindingIOToJSON(value?: FindingIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'focusNode': value['focusNode'],
        'resultPath': value['resultPath'],
        'value': value['value'],
        'severity': value['severity'],
        'message': value['message'],
    };
}

