/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One decoded frame descriptor.
 * @export
 * @interface FrameInfo
 */
export interface FrameInfo {
    /**
     * Zero-based frame index (scrubber position).
     * @type {number}
     * @memberof FrameInfo
     */
    index?: number;
    /**
     * Frame kind — `lockin` (amplitude+phase) or `raw` (temperature).
     * @type {string}
     * @memberof FrameInfo
     */
    kind?: string;
    /**
     * Channels available for this frame, e.g. [amplitude, phase].
     * @type {Array<string>}
     * @memberof FrameInfo
     */
    channels?: Array<string>;
    /**
     * Channel to default the viewer to — `phase` for lock-in (less sensitive to emissivity/uneven heating; the canonical NDT defect channel), `temperature` for raw.
     * @type {string}
     * @memberof FrameInfo
     */
    defaultChannel?: string;
}

/**
 * Check if a given object implements the FrameInfo interface.
 */
export function instanceOfFrameInfo(value: object): value is FrameInfo {
    return true;
}

export function FrameInfoFromJSON(json: any): FrameInfo {
    return FrameInfoFromJSONTyped(json, false);
}

export function FrameInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FrameInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'] == null ? undefined : json['index'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'channels': json['channels'] == null ? undefined : json['channels'],
        'defaultChannel': json['defaultChannel'] == null ? undefined : json['defaultChannel'],
    };
}

export function FrameInfoToJSON(value?: FrameInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'index': value['index'],
        'kind': value['kind'],
        'channels': value['channels'],
        'defaultChannel': value['defaultChannel'],
    };
}

