/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CellMappingIO } from './CellMappingIO';
import {
    CellMappingIOFromJSON,
    CellMappingIOFromJSONTyped,
    CellMappingIOToJSON,
} from './CellMappingIO';

/**
 * Non-validating form hints on one property shape (doc 125 §4).
 * @export
 * @interface HintsIO
 */
export interface HintsIO {
    /**
     * Field label (sh:name).
     * @type {string}
     * @memberof HintsIO
     */
    name?: string | null;
    /**
     * Help text (sh:description).
     * @type {string}
     * @memberof HintsIO
     */
    description?: string | null;
    /**
     * Field order (sh:order).
     * @type {number}
     * @memberof HintsIO
     */
    order?: number | null;
    /**
     * IRI of the sh:PropertyGroup this field belongs to (sh:group).
     * @type {string}
     * @memberof HintsIO
     */
    group?: string | null;
    /**
     * Pre-filled value (sh:defaultValue).
     * @type {string}
     * @memberof HintsIO
     */
    defaultValue?: string | null;
    /**
     * Explicit editor IRI (dash:editor).
     * @type {string}
     * @memberof HintsIO
     */
    editor?: string | null;
    /**
     * dash:singleLine — false hints a textarea.
     * @type {boolean}
     * @memberof HintsIO
     */
    singleLine?: boolean | null;
    /**
     * Input placeholder text (urn:shepard:form:placeholder).
     * @type {string}
     * @memberof HintsIO
     */
    placeholder?: string | null;
    /**
     * Conditional-visibility JSON (urn:shepard:form:visibleWhen).
     * @type {string}
     * @memberof HintsIO
     */
    visibleWhen?: string | null;
    /**
     * Excel cell mapping (urn:btkvs:cell-mapping + urn:btkvs:sheet).
     * @type {CellMappingIO}
     * @memberof HintsIO
     */
    cellMapping?: CellMappingIO | null;
}

/**
 * Check if a given object implements the HintsIO interface.
 */
export function instanceOfHintsIO(value: object): value is HintsIO {
    return true;
}

export function HintsIOFromJSON(json: any): HintsIO {
    return HintsIOFromJSONTyped(json, false);
}

export function HintsIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): HintsIO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'order': json['order'] == null ? undefined : json['order'],
        'group': json['group'] == null ? undefined : json['group'],
        'defaultValue': json['defaultValue'] == null ? undefined : json['defaultValue'],
        'editor': json['editor'] == null ? undefined : json['editor'],
        'singleLine': json['singleLine'] == null ? undefined : json['singleLine'],
        'placeholder': json['placeholder'] == null ? undefined : json['placeholder'],
        'visibleWhen': json['visibleWhen'] == null ? undefined : json['visibleWhen'],
        'cellMapping': json['cellMapping'] == null ? undefined : CellMappingIOFromJSON(json['cellMapping']),
    };
}

export function HintsIOToJSON(value?: HintsIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
        'order': value['order'],
        'group': value['group'],
        'defaultValue': value['defaultValue'],
        'editor': value['editor'],
        'singleLine': value['singleLine'],
        'placeholder': value['placeholder'],
        'visibleWhen': value['visibleWhen'],
        'cellMapping': CellMappingIOToJSON(value['cellMapping']),
    };
}

