/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const InfluxFillOption = {
    Linear: 'LINEAR',
    None: 'NONE',
    Null: 'NULL',
    Previous: 'PREVIOUS'
} as const;
export type InfluxFillOption = typeof InfluxFillOption[keyof typeof InfluxFillOption];


export function instanceOfInfluxFillOption(value: any): boolean {
    for (const key in InfluxFillOption) {
        if (Object.prototype.hasOwnProperty.call(InfluxFillOption, key)) {
            if (InfluxFillOption[key as keyof typeof InfluxFillOption] === value) {
                return true;
            }
        }
    }
    return false;
}

export function InfluxFillOptionFromJSON(json: any): InfluxFillOption {
    return InfluxFillOptionFromJSONTyped(json, false);
}

export function InfluxFillOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfluxFillOption {
    return json as InfluxFillOption;
}

export function InfluxFillOptionToJSON(value?: InfluxFillOption | null): any {
    return value as any;
}

