/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const InfluxSingleValuedUnaryFunction = {
    Mean: 'MEAN',
    Median: 'MEDIAN',
    Count: 'COUNT',
    Sum: 'SUM',
    Min: 'MIN',
    Max: 'MAX',
    Last: 'LAST',
    Integral: 'INTEGRAL',
    Mode: 'MODE',
    Spread: 'SPREAD',
    Stddev: 'STDDEV',
    First: 'FIRST'
} as const;
export type InfluxSingleValuedUnaryFunction = typeof InfluxSingleValuedUnaryFunction[keyof typeof InfluxSingleValuedUnaryFunction];


export function instanceOfInfluxSingleValuedUnaryFunction(value: any): boolean {
    for (const key in InfluxSingleValuedUnaryFunction) {
        if (Object.prototype.hasOwnProperty.call(InfluxSingleValuedUnaryFunction, key)) {
            if (InfluxSingleValuedUnaryFunction[key as keyof typeof InfluxSingleValuedUnaryFunction] === value) {
                return true;
            }
        }
    }
    return false;
}

export function InfluxSingleValuedUnaryFunctionFromJSON(json: any): InfluxSingleValuedUnaryFunction {
    return InfluxSingleValuedUnaryFunctionFromJSONTyped(json, false);
}

export function InfluxSingleValuedUnaryFunctionFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfluxSingleValuedUnaryFunction {
    return json as InfluxSingleValuedUnaryFunction;
}

export function InfluxSingleValuedUnaryFunctionToJSON(value?: InfluxSingleValuedUnaryFunction | null): any {
    return value as any;
}

