/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * KIP record body.
 * @export
 * @interface KernelInformationProfile
 */
export interface KernelInformationProfile {
    /**
     * PID — same value as the parent KipRecordIO#id.
     * @type {string}
     * @memberof KernelInformationProfile
     */
    id: string;
    /**
     * Fully-qualified URL of the published entity at this shepard instance.
     * @type {string}
     * @memberof KernelInformationProfile
     */
    landingPage: string;
    /**
     * KIP digitalObjectType IRI — see aidocs/66 §3.
     * @type {string}
     * @memberof KernelInformationProfile
     */
    digitalObjectType: string;
    /**
     * Server-side wall-clock at the moment the PID was minted (ISO-8601).
     * @type {string}
     * @memberof KernelInformationProfile
     */
    dateCreated?: string;
    /**
     * Server-side wall-clock of the entity's last update (ISO-8601). May equal dateCreated for unchanged entities.
     * @type {string}
     * @memberof KernelInformationProfile
     */
    dateModified?: string;
    /**
     * Username of the publisher — KIP rightsHolder.
     * @type {string}
     * @memberof KernelInformationProfile
     */
    rightsHolder?: string;
    /**
     * License string ('CC-BY-4.0', etc.). Null unless an operator sets a default or the caller supplies one (KIP1e).
     * @type {string}
     * @memberof KernelInformationProfile
     */
    license?: string;
    /**
     * KIP1h Phase-1 version segment of the published entity ('v1', 'v2', ...).
     * @type {string}
     * @memberof KernelInformationProfile
     */
    digitalObjectVersion?: string;
}

/**
 * Check if a given object implements the KernelInformationProfile interface.
 */
export function instanceOfKernelInformationProfile(value: object): value is KernelInformationProfile {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('landingPage' in value) || value['landingPage'] === undefined) return false;
    if (!('digitalObjectType' in value) || value['digitalObjectType'] === undefined) return false;
    return true;
}

export function KernelInformationProfileFromJSON(json: any): KernelInformationProfile {
    return KernelInformationProfileFromJSONTyped(json, false);
}

export function KernelInformationProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): KernelInformationProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'landingPage': json['landingPage'],
        'digitalObjectType': json['digitalObjectType'],
        'dateCreated': json['dateCreated'] == null ? undefined : json['dateCreated'],
        'dateModified': json['dateModified'] == null ? undefined : json['dateModified'],
        'rightsHolder': json['rightsHolder'] == null ? undefined : json['rightsHolder'],
        'license': json['license'] == null ? undefined : json['license'],
        'digitalObjectVersion': json['digitalObjectVersion'] == null ? undefined : json['digitalObjectVersion'],
    };
}

export function KernelInformationProfileToJSON(value?: KernelInformationProfile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'landingPage': value['landingPage'],
        'digitalObjectType': value['digitalObjectType'],
        'dateCreated': value['dateCreated'],
        'dateModified': value['dateModified'],
        'rightsHolder': value['rightsHolder'],
        'license': value['license'],
        'digitalObjectVersion': value['digitalObjectVersion'],
    };
}

