/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LabJournalRevision
 */
export interface LabJournalRevision {
    /**
     * 
     * @type {string}
     * @memberof LabJournalRevision
     */
    readonly appId?: string;
    /**
     * Content of the entry as it existed before the edit.
     * @type {string}
     * @memberof LabJournalRevision
     */
    content?: string;
    /**
     * When the revision was captured (ISO 8601 UTC).
     * @type {string}
     * @memberof LabJournalRevision
     */
    readonly revisedAt?: string;
    /**
     * Display name of the user who made the edit.
     * @type {string}
     * @memberof LabJournalRevision
     */
    readonly revisedBy?: string;
    /**
     * 1-based revision counter (1 = first edit).
     * @type {number}
     * @memberof LabJournalRevision
     */
    readonly revisionNumber?: number;
}

/**
 * Check if a given object implements the LabJournalRevision interface.
 */
export function instanceOfLabJournalRevision(value: object): value is LabJournalRevision {
    return true;
}

export function LabJournalRevisionFromJSON(json: any): LabJournalRevision {
    return LabJournalRevisionFromJSONTyped(json, false);
}

export function LabJournalRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabJournalRevision {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['appId'] == null ? undefined : json['appId'],
        'content': json['content'] == null ? undefined : json['content'],
        'revisedAt': json['revisedAt'] == null ? undefined : json['revisedAt'],
        'revisedBy': json['revisedBy'] == null ? undefined : json['revisedBy'],
        'revisionNumber': json['revisionNumber'] == null ? undefined : json['revisionNumber'],
    };
}

export function LabJournalRevisionToJSON(value?: Omit<LabJournalRevision, 'appId'|'revisedAt'|'revisedBy'|'revisionNumber'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'],
    };
}

