/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LedgerAnchorJob
 */
export interface LedgerAnchorJob {
    /**
     * Stable UUID v7 identifier for this anchor job.
     * @type {string}
     * @memberof LedgerAnchorJob
     */
    jobId: string;
    /**
     * Current state of the job.
     * @type {string}
     * @memberof LedgerAnchorJob
     */
    status: LedgerAnchorJobStatusEnum;
    /**
     * Human-readable summary, e.g. '3/3 activities anchored via bloxberg.'.
     * @type {string}
     * @memberof LedgerAnchorJob
     */
    message: string;
}


/**
 * @export
 */
export const LedgerAnchorJobStatusEnum = {
    Queued: 'queued',
    Running: 'running',
    Complete: 'complete',
    Failed: 'failed'
} as const;
export type LedgerAnchorJobStatusEnum = typeof LedgerAnchorJobStatusEnum[keyof typeof LedgerAnchorJobStatusEnum];


/**
 * Check if a given object implements the LedgerAnchorJob interface.
 */
export function instanceOfLedgerAnchorJob(value: object): value is LedgerAnchorJob {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function LedgerAnchorJobFromJSON(json: any): LedgerAnchorJob {
    return LedgerAnchorJobFromJSONTyped(json, false);
}

export function LedgerAnchorJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): LedgerAnchorJob {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'],
        'status': json['status'],
        'message': json['message'],
    };
}

export function LedgerAnchorJobToJSON(value?: LedgerAnchorJob | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jobId': value['jobId'],
        'status': value['status'],
        'message': value['message'],
    };
}

