/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiveWindowPointIO
 */
export interface LiveWindowPointIO {
    /**
     * ISO 8601 UTC timestamp of this data point.
     * @type {string}
     * @memberof LiveWindowPointIO
     */
    timestamp?: string;
    /**
     * The channel value at this timestamp.
     * @type {any}
     * @memberof LiveWindowPointIO
     */
    value?: any | null;
    /**
     * true when this point was linearly interpolated at the window boundary; false for raw data.
     * @type {boolean}
     * @memberof LiveWindowPointIO
     */
    interpolated?: boolean;
}

/**
 * Check if a given object implements the LiveWindowPointIO interface.
 */
export function instanceOfLiveWindowPointIO(value: object): value is LiveWindowPointIO {
    return true;
}

export function LiveWindowPointIOFromJSON(json: any): LiveWindowPointIO {
    return LiveWindowPointIOFromJSONTyped(json, false);
}

export function LiveWindowPointIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveWindowPointIO {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'value': json['value'] == null ? undefined : json['value'],
        'interpolated': json['interpolated'] == null ? undefined : json['interpolated'],
    };
}

export function LiveWindowPointIOToJSON(value?: LiveWindowPointIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'timestamp': value['timestamp'],
        'value': value['value'],
        'interpolated': value['interpolated'],
    };
}

