/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LockStatusIO
 */
export interface LockStatusIO {
    /**
     * 
     * @type {string}
     * @memberof LockStatusIO
     */
    lockId?: string;
    /**
     * 
     * @type {string}
     * @memberof LockStatusIO
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof LockStatusIO
     */
    startedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof LockStatusIO
     */
    startedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof LockStatusIO
     */
    targetCollectionAppId?: string;
    /**
     * 
     * @type {string}
     * @memberof LockStatusIO
     */
    lastHeartbeatAt?: string;
    /**
     * 
     * @type {string}
     * @memberof LockStatusIO
     */
    errorMessage?: string;
}

/**
 * Check if a given object implements the LockStatusIO interface.
 */
export function instanceOfLockStatusIO(value: object): value is LockStatusIO {
    return true;
}

export function LockStatusIOFromJSON(json: any): LockStatusIO {
    return LockStatusIOFromJSONTyped(json, false);
}

export function LockStatusIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockStatusIO {
    if (json == null) {
        return json;
    }
    return {
        
        'lockId': json['lockId'] == null ? undefined : json['lockId'],
        'status': json['status'] == null ? undefined : json['status'],
        'startedAt': json['startedAt'] == null ? undefined : json['startedAt'],
        'startedBy': json['startedBy'] == null ? undefined : json['startedBy'],
        'targetCollectionAppId': json['targetCollectionAppId'] == null ? undefined : json['targetCollectionAppId'],
        'lastHeartbeatAt': json['lastHeartbeatAt'] == null ? undefined : json['lastHeartbeatAt'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
    };
}

export function LockStatusIOToJSON(value?: LockStatusIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'lockId': value['lockId'],
        'status': value['status'],
        'startedAt': value['startedAt'],
        'startedBy': value['startedBy'],
        'targetCollectionAppId': value['targetCollectionAppId'],
        'lastHeartbeatAt': value['lastHeartbeatAt'],
        'errorMessage': value['errorMessage'],
    };
}

