/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Result of a MAPPING_RECIPE materialization.
 * @export
 * @interface MaterializeResponseIO
 */
export interface MaterializeResponseIO {
    /**
     * appId of the MAPPING_RECIPE template that was materialized.
     * @type {string}
     * @memberof MaterializeResponseIO
     */
    templateAppId?: string;
    /**
     * REFERENCE when a derived reference appId is returned; VIEW for a played/rendered projection.
     * @type {string}
     * @memberof MaterializeResponseIO
     */
    outputKind?: string;
    /**
     * appId of the derived reference (set when outputKind=REFERENCE).
     * @type {string}
     * @memberof MaterializeResponseIO
     */
    derivedReferenceAppId?: string | null;
    /**
     * JSON-serialisable view-model (set when outputKind=VIEW).
     * @type {{ [key: string]: any; }}
     * @memberof MaterializeResponseIO
     */
    viewModel?: { [key: string]: any; } | null;
    /**
     * Name of the TransformExecutor that produced this result.
     * @type {string}
     * @memberof MaterializeResponseIO
     */
    executor?: string;
}

/**
 * Check if a given object implements the MaterializeResponseIO interface.
 */
export function instanceOfMaterializeResponseIO(value: object): value is MaterializeResponseIO {
    return true;
}

export function MaterializeResponseIOFromJSON(json: any): MaterializeResponseIO {
    return MaterializeResponseIOFromJSONTyped(json, false);
}

export function MaterializeResponseIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaterializeResponseIO {
    if (json == null) {
        return json;
    }
    return {
        
        'templateAppId': json['templateAppId'] == null ? undefined : json['templateAppId'],
        'outputKind': json['outputKind'] == null ? undefined : json['outputKind'],
        'derivedReferenceAppId': json['derivedReferenceAppId'] == null ? undefined : json['derivedReferenceAppId'],
        'viewModel': json['viewModel'] == null ? undefined : json['viewModel'],
        'executor': json['executor'] == null ? undefined : json['executor'],
    };
}

export function MaterializeResponseIOToJSON(value?: MaterializeResponseIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'templateAppId': value['templateAppId'],
        'outputKind': value['outputKind'],
        'derivedReferenceAppId': value['derivedReferenceAppId'],
        'viewModel': value['viewModel'],
        'executor': value['executor'],
    };
}

