/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeIO
 */
export interface MeIO {
    /**
     * 
     * @type {string}
     * @memberof MeIO
     */
    readonly username: string;
    /**
     * 
     * @type {string}
     * @memberof MeIO
     */
    readonly appId: string;
    /**
     * 
     * @type {string}
     * @memberof MeIO
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MeIO
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MeIO
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MeIO
     */
    orcid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MeIO
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MeIO
     */
    readonly effectiveDisplayName: string;
    /**
     * Number of collections the caller is currently watching (CW1).
     * @type {number}
     * @memberof MeIO
     */
    readonly watchedCollectionCount: number;
    /**
     * PROV1l — when true, identity is omitted from :Activity records (GDPR opt-out). Default false.
     * @type {boolean}
     * @memberof MeIO
     */
    anonymizeInProvenance: boolean;
}

/**
 * Check if a given object implements the MeIO interface.
 */
export function instanceOfMeIO(value: object): value is MeIO {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('appId' in value) || value['appId'] === undefined) return false;
    if (!('effectiveDisplayName' in value) || value['effectiveDisplayName'] === undefined) return false;
    if (!('watchedCollectionCount' in value) || value['watchedCollectionCount'] === undefined) return false;
    if (!('anonymizeInProvenance' in value) || value['anonymizeInProvenance'] === undefined) return false;
    return true;
}

export function MeIOFromJSON(json: any): MeIO {
    return MeIOFromJSONTyped(json, false);
}

export function MeIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeIO {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'appId': json['appId'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'email': json['email'] == null ? undefined : json['email'],
        'orcid': json['orcid'] == null ? undefined : json['orcid'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'effectiveDisplayName': json['effectiveDisplayName'],
        'watchedCollectionCount': json['watchedCollectionCount'],
        'anonymizeInProvenance': json['anonymizeInProvenance'],
    };
}

export function MeIOToJSON(value?: Omit<MeIO, 'username'|'appId'|'effectiveDisplayName'|'watchedCollectionCount'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
        'orcid': value['orcid'],
        'displayName': value['displayName'],
        'anonymizeInProvenance': value['anonymizeInProvenance'],
    };
}

