/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeRoleIn
 */
export interface MeRoleIn {
    /**
     * Collection appId the role applies to.
     * @type {string}
     * @memberof MeRoleIn
     */
    collectionAppId: string;
    /**
     * Caller can read entities under this Collection.
     * @type {boolean}
     * @memberof MeRoleIn
     */
    read: boolean;
    /**
     * Caller can create / update entities under this Collection.
     * @type {boolean}
     * @memberof MeRoleIn
     */
    write: boolean;
    /**
     * Caller can edit permissions / delete on this Collection (also implies an owner-like UX role).
     * @type {boolean}
     * @memberof MeRoleIn
     */
    manage: boolean;
    /**
     * Caller carries the `instance-admin` role (dual-sourced from IdP claim AND/OR `:HAS_ROLE` edge, deduped on the JWT principal). The role chip surfaces this as a side-by-side chip so admins can tell they're operating in an elevated context.
     * @type {boolean}
     * @memberof MeRoleIn
     */
    isInstanceAdmin: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MeRoleIn
     */
    instanceAdmin?: boolean;
}

/**
 * Check if a given object implements the MeRoleIn interface.
 */
export function instanceOfMeRoleIn(value: object): value is MeRoleIn {
    if (!('collectionAppId' in value) || value['collectionAppId'] === undefined) return false;
    if (!('read' in value) || value['read'] === undefined) return false;
    if (!('write' in value) || value['write'] === undefined) return false;
    if (!('manage' in value) || value['manage'] === undefined) return false;
    if (!('isInstanceAdmin' in value) || value['isInstanceAdmin'] === undefined) return false;
    return true;
}

export function MeRoleInFromJSON(json: any): MeRoleIn {
    return MeRoleInFromJSONTyped(json, false);
}

export function MeRoleInFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeRoleIn {
    if (json == null) {
        return json;
    }
    return {
        
        'collectionAppId': json['collectionAppId'],
        'read': json['read'],
        'write': json['write'],
        'manage': json['manage'],
        'isInstanceAdmin': json['isInstanceAdmin'],
        'instanceAdmin': json['instanceAdmin'] == null ? undefined : json['instanceAdmin'],
    };
}

export function MeRoleInToJSON(value?: MeRoleIn | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'collectionAppId': value['collectionAppId'],
        'read': value['read'],
        'write': value['write'],
        'manage': value['manage'],
        'isInstanceAdmin': value['isInstanceAdmin'],
        'instanceAdmin': value['instanceAdmin'],
    };
}

