/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AggregateFunction } from './AggregateFunction';
import {
    AggregateFunctionFromJSON,
    AggregateFunctionFromJSONTyped,
    AggregateFunctionToJSON,
} from './AggregateFunction';

/**
 * 
 * @export
 * @interface MetricsIO
 */
export interface MetricsIO {
    /**
     * 
     * @type {AggregateFunction}
     * @memberof MetricsIO
     */
    _function?: AggregateFunction;
    /**
     * 
     * @type {any}
     * @memberof MetricsIO
     */
    value?: any | null;
}



/**
 * Check if a given object implements the MetricsIO interface.
 */
export function instanceOfMetricsIO(value: object): value is MetricsIO {
    return true;
}

export function MetricsIOFromJSON(json: any): MetricsIO {
    return MetricsIOFromJSONTyped(json, false);
}

export function MetricsIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsIO {
    if (json == null) {
        return json;
    }
    return {
        
        '_function': json['function'] == null ? undefined : AggregateFunctionFromJSON(json['function']),
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function MetricsIOToJSON(value?: MetricsIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'function': AggregateFunctionToJSON(value['_function']),
        'value': value['value'],
    };
}

