/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MigrationProgressStatus = {
    Pending: 'PENDING',
    Running: 'RUNNING',
    Completed: 'COMPLETED',
    Failed: 'FAILED'
} as const;
export type MigrationProgressStatus = typeof MigrationProgressStatus[keyof typeof MigrationProgressStatus];


export function instanceOfMigrationProgressStatus(value: any): boolean {
    for (const key in MigrationProgressStatus) {
        if (Object.prototype.hasOwnProperty.call(MigrationProgressStatus, key)) {
            if (MigrationProgressStatus[key as keyof typeof MigrationProgressStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MigrationProgressStatusFromJSON(json: any): MigrationProgressStatus {
    return MigrationProgressStatusFromJSONTyped(json, false);
}

export function MigrationProgressStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): MigrationProgressStatus {
    return json as MigrationProgressStatus;
}

export function MigrationProgressStatusToJSON(value?: MigrationProgressStatus | null): any {
    return value as any;
}

