/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationTestDeliveryIO
 */
export interface NotificationTestDeliveryIO {
    /**
     * 
     * @type {string}
     * @memberof NotificationTestDeliveryIO
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationTestDeliveryIO
     */
    transport?: string;
}

/**
 * Check if a given object implements the NotificationTestDeliveryIO interface.
 */
export function instanceOfNotificationTestDeliveryIO(value: object): value is NotificationTestDeliveryIO {
    return true;
}

export function NotificationTestDeliveryIOFromJSON(json: any): NotificationTestDeliveryIO {
    return NotificationTestDeliveryIOFromJSONTyped(json, false);
}

export function NotificationTestDeliveryIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationTestDeliveryIO {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'transport': json['transport'] == null ? undefined : json['transport'],
    };
}

export function NotificationTestDeliveryIOToJSON(value?: NotificationTestDeliveryIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'transport': value['transport'],
    };
}

