/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShepardFile } from './ShepardFile';
import {
    ShepardFileFromJSON,
    ShepardFileFromJSONTyped,
    ShepardFileToJSON,
} from './ShepardFile';

/**
 * 
 * @export
 * @interface PagedFiles
 */
export interface PagedFiles {
    /**
     * The files on this page, ordered by their position in the group's files[] list.
     * @type {Array<ShepardFile>}
     * @memberof PagedFiles
     */
    items?: Array<ShepardFile>;
    /**
     * 0-based page index that was returned.
     * @type {number}
     * @memberof PagedFiles
     */
    page?: number;
    /**
     * Maximum items per page that was honoured by the server.
     * @type {number}
     * @memberof PagedFiles
     */
    size?: number;
    /**
     * Total number of files in the group (across all pages).
     * @type {number}
     * @memberof PagedFiles
     */
    totalElements?: number;
    /**
     * Total number of pages at the current `size`.
     * @type {number}
     * @memberof PagedFiles
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PagedFiles interface.
 */
export function instanceOfPagedFiles(value: object): value is PagedFiles {
    return true;
}

export function PagedFilesFromJSON(json: any): PagedFiles {
    return PagedFilesFromJSONTyped(json, false);
}

export function PagedFilesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedFiles {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ShepardFileFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PagedFilesToJSON(value?: PagedFiles | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ShepardFileToJSON)),
        'page': value['page'],
        'size': value['size'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

