/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchGitCredential
 */
export interface PatchGitCredential {
    /**
     * Updated human-readable label. Null = leave unchanged.
     * @type {string}
     * @memberof PatchGitCredential
     */
    displayName?: string | null;
    /**
     * Updated git username. Null = leave unchanged.
     * @type {string}
     * @memberof PatchGitCredential
     */
    username?: string | null;
    /**
     * Updated PAT. Write-only — never returned. Null = leave unchanged.
     * @type {string}
     * @memberof PatchGitCredential
     */
    pat?: string | null;
}

/**
 * Check if a given object implements the PatchGitCredential interface.
 */
export function instanceOfPatchGitCredential(value: object): value is PatchGitCredential {
    return true;
}

export function PatchGitCredentialFromJSON(json: any): PatchGitCredential {
    return PatchGitCredentialFromJSONTyped(json, false);
}

export function PatchGitCredentialFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchGitCredential {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'username': json['username'] == null ? undefined : json['username'],
        'pat': json['pat'] == null ? undefined : json['pat'],
    };
}

export function PatchGitCredentialToJSON(value?: PatchGitCredential | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'displayName': value['displayName'],
        'username': value['username'],
        'pat': value['pat'],
    };
}

