/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermissionAuditEntry
 */
export interface PermissionAuditEntry {
    /**
     * Neo4j-side numeric id of the orphan entity.
     * @type {number}
     * @memberof PermissionAuditEntry
     */
    id: number;
    /**
     * appId (UUID v7) if populated by L2a/L2b.
     * @type {string}
     * @memberof PermissionAuditEntry
     */
    appId?: string | null;
    /**
     * The :BasicEntity sub-label list (e.g. ['Collection', 'BasicEntity']) — useful for triage.
     * @type {Array<string>}
     * @memberof PermissionAuditEntry
     */
    labels: Array<string>;
    /**
     * Entity name if any — passed through from the Named mixin.
     * @type {string}
     * @memberof PermissionAuditEntry
     */
    name?: string | null;
}

/**
 * Check if a given object implements the PermissionAuditEntry interface.
 */
export function instanceOfPermissionAuditEntry(value: object): value is PermissionAuditEntry {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('labels' in value) || value['labels'] === undefined) return false;
    return true;
}

export function PermissionAuditEntryFromJSON(json: any): PermissionAuditEntry {
    return PermissionAuditEntryFromJSONTyped(json, false);
}

export function PermissionAuditEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionAuditEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'appId': json['appId'] == null ? undefined : json['appId'],
        'labels': json['labels'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function PermissionAuditEntryToJSON(value?: PermissionAuditEntry | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'appId': value['appId'],
        'labels': value['labels'],
        'name': value['name'],
    };
}

