/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectByAnnotationItemIO } from './ProjectByAnnotationItemIO';
import {
    ProjectByAnnotationItemIOFromJSON,
    ProjectByAnnotationItemIOFromJSONTyped,
    ProjectByAnnotationItemIOToJSON,
} from './ProjectByAnnotationItemIO';

/**
 * Cross-Collection by-annotation roll-up for a Project.
 * @export
 * @interface ProjectByAnnotationIO
 */
export interface ProjectByAnnotationIO {
    /**
     * appId of the parent Project.
     * @type {string}
     * @memberof ProjectByAnnotationIO
     */
    projectAppId: string;
    /**
     * Predicate IRI used for the filter.
     * @type {string}
     * @memberof ProjectByAnnotationIO
     */
    predicate: string;
    /**
     * Value to match.
     * @type {string}
     * @memberof ProjectByAnnotationIO
     */
    value: string;
    /**
     * Total number of matching DataObjects across the Project.
     * @type {number}
     * @memberof ProjectByAnnotationIO
     */
    totalCount?: number;
    /**
     * Current page (zero-based).
     * @type {number}
     * @memberof ProjectByAnnotationIO
     */
    page?: number;
    /**
     * Page size.
     * @type {number}
     * @memberof ProjectByAnnotationIO
     */
    pageSize?: number;
    /**
     * Matching DataObjects on this page.
     * @type {Array<ProjectByAnnotationItemIO>}
     * @memberof ProjectByAnnotationIO
     */
    results?: Array<ProjectByAnnotationItemIO>;
}

/**
 * Check if a given object implements the ProjectByAnnotationIO interface.
 */
export function instanceOfProjectByAnnotationIO(value: object): value is ProjectByAnnotationIO {
    if (!('projectAppId' in value) || value['projectAppId'] === undefined) return false;
    if (!('predicate' in value) || value['predicate'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ProjectByAnnotationIOFromJSON(json: any): ProjectByAnnotationIO {
    return ProjectByAnnotationIOFromJSONTyped(json, false);
}

export function ProjectByAnnotationIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectByAnnotationIO {
    if (json == null) {
        return json;
    }
    return {
        
        'projectAppId': json['projectAppId'],
        'predicate': json['predicate'],
        'value': json['value'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ProjectByAnnotationItemIOFromJSON)),
    };
}

export function ProjectByAnnotationIOToJSON(value?: ProjectByAnnotationIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'projectAppId': value['projectAppId'],
        'predicate': value['predicate'],
        'value': value['value'],
        'totalCount': value['totalCount'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(ProjectByAnnotationItemIOToJSON)),
    };
}

