/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Lifecycle state flip for a Collection or Container.
 * @export
 * @interface PublicationState
 */
export interface PublicationState {
    /**
     * 
     * @type {string}
     * @memberof PublicationState
     */
    state: PublicationStateStateEnum;
    /**
     * True when state == ARCHIVED (frozen, prune-only).
     * @type {boolean}
     * @memberof PublicationState
     */
    readonly archived?: boolean;
}


/**
 * @export
 */
export const PublicationStateStateEnum = {
    Draft: 'DRAFT',
    InReview: 'IN_REVIEW',
    Ready: 'READY',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;
export type PublicationStateStateEnum = typeof PublicationStateStateEnum[keyof typeof PublicationStateStateEnum];


/**
 * Check if a given object implements the PublicationState interface.
 */
export function instanceOfPublicationState(value: object): value is PublicationState {
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function PublicationStateFromJSON(json: any): PublicationState {
    return PublicationStateFromJSONTyped(json, false);
}

export function PublicationStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicationState {
    if (json == null) {
        return json;
    }
    return {
        
        'state': json['state'],
        'archived': json['archived'] == null ? undefined : json['archived'],
    };
}

export function PublicationStateToJSON(value?: Omit<PublicationState, 'archived'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'state': value['state'],
    };
}

