/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepExportIO
 */
export interface RepExportIO {
    /**
     * 
     * @type {string}
     * @memberof RepExportIO
     */
    exportId?: string;
    /**
     * 
     * @type {string}
     * @memberof RepExportIO
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof RepExportIO
     */
    bagBase64?: string;
    /**
     * 
     * @type {string}
     * @memberof RepExportIO
     */
    downloadUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof RepExportIO
     */
    fileName?: string;
    /**
     * 
     * @type {Date}
     * @memberof RepExportIO
     */
    exportedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof RepExportIO
     */
    dataObjectCount?: number;
    /**
     * 
     * @type {number}
     * @memberof RepExportIO
     */
    bagSizeBytes?: number;
}

/**
 * Check if a given object implements the RepExportIO interface.
 */
export function instanceOfRepExportIO(value: object): value is RepExportIO {
    return true;
}

export function RepExportIOFromJSON(json: any): RepExportIO {
    return RepExportIOFromJSONTyped(json, false);
}

export function RepExportIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepExportIO {
    if (json == null) {
        return json;
    }
    return {
        
        'exportId': json['exportId'] == null ? undefined : json['exportId'],
        'status': json['status'] == null ? undefined : json['status'],
        'bagBase64': json['bagBase64'] == null ? undefined : json['bagBase64'],
        'downloadUrl': json['downloadUrl'] == null ? undefined : json['downloadUrl'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'exportedAt': json['exportedAt'] == null ? undefined : (new Date(json['exportedAt'])),
        'dataObjectCount': json['dataObjectCount'] == null ? undefined : json['dataObjectCount'],
        'bagSizeBytes': json['bagSizeBytes'] == null ? undefined : json['bagSizeBytes'],
    };
}

export function RepExportIOToJSON(value?: RepExportIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'exportId': value['exportId'],
        'status': value['status'],
        'bagBase64': value['bagBase64'],
        'downloadUrl': value['downloadUrl'],
        'fileName': value['fileName'],
        'exportedAt': value['exportedAt'] == null ? undefined : ((value['exportedAt']).toISOString()),
        'dataObjectCount': value['dataObjectCount'],
        'bagSizeBytes': value['bagSizeBytes'],
    };
}

