/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Resolved timeseries channel reference. Null in beta.
 * @export
 * @interface ResolvedChannelIO
 */
export interface ResolvedChannelIO {
    /**
     * appId of the TimeseriesReference node whose channel list satisfies this binding.
     * @type {string}
     * @memberof ResolvedChannelIO
     */
    channelRef?: string;
}

/**
 * Check if a given object implements the ResolvedChannelIO interface.
 */
export function instanceOfResolvedChannelIO(value: object): value is ResolvedChannelIO {
    return true;
}

export function ResolvedChannelIOFromJSON(json: any): ResolvedChannelIO {
    return ResolvedChannelIOFromJSONTyped(json, false);
}

export function ResolvedChannelIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolvedChannelIO {
    if (json == null) {
        return json;
    }
    return {
        
        'channelRef': json['channelRef'] == null ? undefined : json['channelRef'],
    };
}

export function ResolvedChannelIOToJSON(value?: ResolvedChannelIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'channelRef': value['channelRef'],
    };
}

