/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchV2Item
 */
export interface SearchV2Item {
    /**
     * UUID v7 application-level identifier.
     * @type {string}
     * @memberof SearchV2Item
     */
    readonly appId: string;
    /**
     * 
     * @type {string}
     * @memberof SearchV2Item
     */
    readonly name: string;
    /**
     * 
     * @type {string}
     * @memberof SearchV2Item
     */
    readonly kind: SearchV2ItemKindEnum;
    /**
     * AppId of the owning Collection — populated for kind=dataobject, null for kind=collection. Enables the frontend to construct the navigation route without a secondary collection-lookup.
     * @type {string}
     * @memberof SearchV2Item
     */
    readonly parentCollectionAppId?: string | null;
}


/**
 * @export
 */
export const SearchV2ItemKindEnum = {
    Collection: 'collection',
    Dataobject: 'dataobject'
} as const;
export type SearchV2ItemKindEnum = typeof SearchV2ItemKindEnum[keyof typeof SearchV2ItemKindEnum];


/**
 * Check if a given object implements the SearchV2Item interface.
 */
export function instanceOfSearchV2Item(value: object): value is SearchV2Item {
    if (!('appId' in value) || value['appId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    return true;
}

export function SearchV2ItemFromJSON(json: any): SearchV2Item {
    return SearchV2ItemFromJSONTyped(json, false);
}

export function SearchV2ItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchV2Item {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['appId'],
        'name': json['name'],
        'kind': json['kind'],
        'parentCollectionAppId': json['parentCollectionAppId'] == null ? undefined : json['parentCollectionAppId'],
    };
}

export function SearchV2ItemToJSON(value?: Omit<SearchV2Item, 'appId'|'name'|'kind'|'parentCollectionAppId'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

