/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SemanticAnnotation
 */
export interface SemanticAnnotation {
    /**
     * 
     * @type {number}
     * @memberof SemanticAnnotation
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof SemanticAnnotation
     */
    readonly name: string;
    /**
     * 
     * @type {string}
     * @memberof SemanticAnnotation
     */
    propertyIRI: string;
    /**
     * 
     * @type {string}
     * @memberof SemanticAnnotation
     */
    valueIRI: string;
    /**
     * 
     * @type {number}
     * @memberof SemanticAnnotation
     */
    propertyRepositoryId: number;
    /**
     * 
     * @type {number}
     * @memberof SemanticAnnotation
     */
    valueRepositoryId: number;
}

/**
 * Check if a given object implements the SemanticAnnotation interface.
 */
export function instanceOfSemanticAnnotation(value: object): value is SemanticAnnotation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('propertyIRI' in value) || value['propertyIRI'] === undefined) return false;
    if (!('valueIRI' in value) || value['valueIRI'] === undefined) return false;
    if (!('propertyRepositoryId' in value) || value['propertyRepositoryId'] === undefined) return false;
    if (!('valueRepositoryId' in value) || value['valueRepositoryId'] === undefined) return false;
    return true;
}

export function SemanticAnnotationFromJSON(json: any): SemanticAnnotation {
    return SemanticAnnotationFromJSONTyped(json, false);
}

export function SemanticAnnotationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SemanticAnnotation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'propertyIRI': json['propertyIRI'],
        'valueIRI': json['valueIRI'],
        'propertyRepositoryId': json['propertyRepositoryId'],
        'valueRepositoryId': json['valueRepositoryId'],
    };
}

export function SemanticAnnotationToJSON(value?: Omit<SemanticAnnotation, 'id'|'name'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'propertyIRI': value['propertyIRI'],
        'valueIRI': value['valueIRI'],
        'propertyRepositoryId': value['propertyRepositoryId'],
        'valueRepositoryId': value['valueRepositoryId'],
    };
}

