/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SemanticRepositoryType } from './SemanticRepositoryType';
import {
    SemanticRepositoryTypeFromJSON,
    SemanticRepositoryTypeFromJSONTyped,
    SemanticRepositoryTypeToJSON,
} from './SemanticRepositoryType';

/**
 * 
 * @export
 * @interface SemanticRepository
 */
export interface SemanticRepository {
    /**
     * 
     * @type {number}
     * @memberof SemanticRepository
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof SemanticRepository
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof SemanticRepository
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof SemanticRepository
     */
    readonly updatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof SemanticRepository
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof SemanticRepository
     */
    name: string;
    /**
     * 
     * @type {SemanticRepositoryType}
     * @memberof SemanticRepository
     */
    type: SemanticRepositoryType;
    /**
     * 
     * @type {string}
     * @memberof SemanticRepository
     */
    endpoint: string;
}



/**
 * Check if a given object implements the SemanticRepository interface.
 */
export function instanceOfSemanticRepository(value: object): value is SemanticRepository {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('endpoint' in value) || value['endpoint'] === undefined) return false;
    return true;
}

export function SemanticRepositoryFromJSON(json: any): SemanticRepository {
    return SemanticRepositoryFromJSONTyped(json, false);
}

export function SemanticRepositoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SemanticRepository {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'createdBy': json['createdBy'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
        'updatedBy': json['updatedBy'],
        'name': json['name'],
        'type': SemanticRepositoryTypeFromJSON(json['type']),
        'endpoint': json['endpoint'],
    };
}

export function SemanticRepositoryToJSON(value?: Omit<SemanticRepository, 'id'|'createdAt'|'createdBy'|'updatedAt'|'updatedBy'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'type': SemanticRepositoryTypeToJSON(value['type']),
        'endpoint': value['endpoint'],
    };
}

