/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChannelBindingProjectionIO } from './ChannelBindingProjectionIO';
import {
    ChannelBindingProjectionIOFromJSON,
    ChannelBindingProjectionIOFromJSONTyped,
    ChannelBindingProjectionIOToJSON,
} from './ChannelBindingProjectionIO';

/**
 * VIEW_RECIPE render projection response.
 * @export
 * @interface ShapesRenderResponseIO
 */
export interface ShapesRenderResponseIO {
    /**
     * Echoes the templateAppId from the request.
     * @type {string}
     * @memberof ShapesRenderResponseIO
     */
    templateAppId?: string;
    /**
     * Echoes the focusShepardId from the request.
     * @type {string}
     * @memberof ShapesRenderResponseIO
     */
    focusShepardId?: string;
    /**
     * Renderer hint from the template body (e.g. 'tresjs', 'echarts', 'plotly'). The frontend uses this to select the correct Vue renderer component.
     * @type {string}
     * @memberof ShapesRenderResponseIO
     */
    renderer?: string;
    /**
     * Projected channel bindings — one entry per binding declared in the template.
     * @type {Array<ChannelBindingProjectionIO>}
     * @memberof ShapesRenderResponseIO
     */
    channelBindings?: Array<ChannelBindingProjectionIO>;
}

/**
 * Check if a given object implements the ShapesRenderResponseIO interface.
 */
export function instanceOfShapesRenderResponseIO(value: object): value is ShapesRenderResponseIO {
    return true;
}

export function ShapesRenderResponseIOFromJSON(json: any): ShapesRenderResponseIO {
    return ShapesRenderResponseIOFromJSONTyped(json, false);
}

export function ShapesRenderResponseIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShapesRenderResponseIO {
    if (json == null) {
        return json;
    }
    return {
        
        'templateAppId': json['templateAppId'] == null ? undefined : json['templateAppId'],
        'focusShepardId': json['focusShepardId'] == null ? undefined : json['focusShepardId'],
        'renderer': json['renderer'] == null ? undefined : json['renderer'],
        'channelBindings': json['channelBindings'] == null ? undefined : ((json['channelBindings'] as Array<any>).map(ChannelBindingProjectionIOFromJSON)),
    };
}

export function ShapesRenderResponseIOToJSON(value?: ShapesRenderResponseIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'templateAppId': value['templateAppId'],
        'focusShepardId': value['focusShepardId'],
        'renderer': value['renderer'],
        'channelBindings': value['channelBindings'] == null ? undefined : ((value['channelBindings'] as Array<any>).map(ChannelBindingProjectionIOToJSON)),
    };
}

