/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PropertyIO } from './PropertyIO';
import {
    PropertyIOFromJSON,
    PropertyIOFromJSONTyped,
    PropertyIOToJSON,
} from './PropertyIO';

/**
 * JSON DSL for a SHACL NodeShape. Compiled to canonical Turtle by POST /v2/shapes/build.
 * @export
 * @interface ShapeBuildRequestIO
 */
export interface ShapeBuildRequestIO {
    /**
     * IRI of the sh:NodeShape. When null/blank the builder mints a deterministic local IRI.
     * @type {string}
     * @memberof ShapeBuildRequestIO
     */
    shapeIri?: string | null;
    /**
     * sh:targetClass IRI. Nullable — a shape may target by other means or be referenced via sh:node.
     * @type {string}
     * @memberof ShapeBuildRequestIO
     */
    targetClass?: string | null;
    /**
     * sh:closed — when true, emits sh:closed true.
     * @type {boolean}
     * @memberof ShapeBuildRequestIO
     */
    closed?: boolean;
    /**
     * The property constraints. Null/empty = a shape with no property constraints.
     * @type {Array<PropertyIO>}
     * @memberof ShapeBuildRequestIO
     */
    properties?: Array<PropertyIO> | null;
}

/**
 * Check if a given object implements the ShapeBuildRequestIO interface.
 */
export function instanceOfShapeBuildRequestIO(value: object): value is ShapeBuildRequestIO {
    return true;
}

export function ShapeBuildRequestIOFromJSON(json: any): ShapeBuildRequestIO {
    return ShapeBuildRequestIOFromJSONTyped(json, false);
}

export function ShapeBuildRequestIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShapeBuildRequestIO {
    if (json == null) {
        return json;
    }
    return {
        
        'shapeIri': json['shapeIri'] == null ? undefined : json['shapeIri'],
        'targetClass': json['targetClass'] == null ? undefined : json['targetClass'],
        'closed': json['closed'] == null ? undefined : json['closed'],
        'properties': json['properties'] == null ? undefined : ((json['properties'] as Array<any>).map(PropertyIOFromJSON)),
    };
}

export function ShapeBuildRequestIOToJSON(value?: ShapeBuildRequestIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'shapeIri': value['shapeIri'],
        'targetClass': value['targetClass'],
        'closed': value['closed'],
        'properties': value['properties'] == null ? undefined : ((value['properties'] as Array<any>).map(PropertyIOToJSON)),
    };
}

