/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SnapshotDiffEntry
 */
export interface SnapshotDiffEntry {
    /**
     * appId of the entity that changed revision between snapshots.
     * @type {string}
     * @memberof SnapshotDiffEntry
     */
    entityAppId?: string;
    /**
     * Revision the entity held in snapshot A (base).
     * @type {number}
     * @memberof SnapshotDiffEntry
     */
    revisionA?: number;
    /**
     * Revision the entity held in snapshot B (head).
     * @type {number}
     * @memberof SnapshotDiffEntry
     */
    revisionB?: number;
}

/**
 * Check if a given object implements the SnapshotDiffEntry interface.
 */
export function instanceOfSnapshotDiffEntry(value: object): value is SnapshotDiffEntry {
    return true;
}

export function SnapshotDiffEntryFromJSON(json: any): SnapshotDiffEntry {
    return SnapshotDiffEntryFromJSONTyped(json, false);
}

export function SnapshotDiffEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnapshotDiffEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'entityAppId': json['entityAppId'] == null ? undefined : json['entityAppId'],
        'revisionA': json['revisionA'] == null ? undefined : json['revisionA'],
        'revisionB': json['revisionB'] == null ? undefined : json['revisionB'],
    };
}

export function SnapshotDiffEntryToJSON(value?: SnapshotDiffEntry | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'entityAppId': value['entityAppId'],
        'revisionA': value['revisionA'],
        'revisionB': value['revisionB'],
    };
}

