/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AbstractGeometryFilter } from './AbstractGeometryFilter';
import {
    AbstractGeometryFilterFromJSON,
    AbstractGeometryFilterFromJSONTyped,
    AbstractGeometryFilterToJSON,
} from './AbstractGeometryFilter';
import type { FilterCondition } from './FilterCondition';
import {
    FilterConditionFromJSON,
    FilterConditionFromJSONTyped,
    FilterConditionToJSON,
} from './FilterCondition';

/**
 * 
 * @export
 * @interface SpatialDataReference
 */
export interface SpatialDataReference {
    /**
     * 
     * @type {number}
     * @memberof SpatialDataReference
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof SpatialDataReference
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof SpatialDataReference
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof SpatialDataReference
     */
    readonly updatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof SpatialDataReference
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpatialDataReference
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof SpatialDataReference
     */
    readonly dataObjectId?: number;
    /**
     * 
     * @type {string}
     * @memberof SpatialDataReference
     */
    readonly type?: string;
    /**
     * 
     * @type {number}
     * @memberof SpatialDataReference
     */
    spatialDataContainerId: number;
    /**
     * 
     * @type {AbstractGeometryFilter}
     * @memberof SpatialDataReference
     */
    geometryFilter?: AbstractGeometryFilter;
    /**
     * 
     * @type {Array<FilterCondition>}
     * @memberof SpatialDataReference
     */
    measurementsFilter?: Array<FilterCondition>;
    /**
     * 
     * @type {number}
     * @memberof SpatialDataReference
     */
    startTime?: number;
    /**
     * 
     * @type {number}
     * @memberof SpatialDataReference
     */
    endTime?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SpatialDataReference
     */
    metadataFilter?: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof SpatialDataReference
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof SpatialDataReference
     */
    skip?: number;
}

/**
 * Check if a given object implements the SpatialDataReference interface.
 */
export function instanceOfSpatialDataReference(value: object): value is SpatialDataReference {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('spatialDataContainerId' in value) || value['spatialDataContainerId'] === undefined) return false;
    return true;
}

export function SpatialDataReferenceFromJSON(json: any): SpatialDataReference {
    return SpatialDataReferenceFromJSONTyped(json, false);
}

export function SpatialDataReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpatialDataReference {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'createdBy': json['createdBy'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
        'updatedBy': json['updatedBy'],
        'name': json['name'],
        'dataObjectId': json['dataObjectId'] == null ? undefined : json['dataObjectId'],
        'type': json['type'] == null ? undefined : json['type'],
        'spatialDataContainerId': json['spatialDataContainerId'],
        'geometryFilter': json['geometryFilter'] == null ? undefined : AbstractGeometryFilterFromJSON(json['geometryFilter']),
        'measurementsFilter': json['measurementsFilter'] == null ? undefined : ((json['measurementsFilter'] as Array<any>).map(FilterConditionFromJSON)),
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
        'metadataFilter': json['metadataFilter'] == null ? undefined : json['metadataFilter'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'skip': json['skip'] == null ? undefined : json['skip'],
    };
}

export function SpatialDataReferenceToJSON(value?: Omit<SpatialDataReference, 'id'|'createdAt'|'createdBy'|'updatedAt'|'updatedBy'|'dataObjectId'|'type'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'spatialDataContainerId': value['spatialDataContainerId'],
        'geometryFilter': AbstractGeometryFilterToJSON(value['geometryFilter']),
        'measurementsFilter': value['measurementsFilter'] == null ? undefined : ((value['measurementsFilter'] as Array<any>).map(FilterConditionToJSON)),
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'metadataFilter': value['metadataFilter'],
        'limit': value['limit'],
        'skip': value['skip'],
    };
}

