/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StructuredDataReference
 */
export interface StructuredDataReference {
    /**
     *
     * @type {number}
     * @memberof StructuredDataReference
     */
    readonly id: number;
    /**
     * Application-level UUID v7 identifier. See TimeseriesReference for the
     * full reason this is included on the patched client.
     * @type {string}
     * @memberof StructuredDataReference
     */
    readonly appId?: string;
    /**
     * 
     * @type {Date}
     * @memberof StructuredDataReference
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof StructuredDataReference
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof StructuredDataReference
     */
    readonly updatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof StructuredDataReference
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructuredDataReference
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof StructuredDataReference
     */
    readonly dataObjectId?: number;
    /**
     * 
     * @type {string}
     * @memberof StructuredDataReference
     */
    readonly type?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StructuredDataReference
     */
    structuredDataOids: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof StructuredDataReference
     */
    structuredDataContainerId: number;
}

/**
 * Check if a given object implements the StructuredDataReference interface.
 */
export function instanceOfStructuredDataReference(value: object): value is StructuredDataReference {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('structuredDataOids' in value) || value['structuredDataOids'] === undefined) return false;
    if (!('structuredDataContainerId' in value) || value['structuredDataContainerId'] === undefined) return false;
    return true;
}

export function StructuredDataReferenceFromJSON(json: any): StructuredDataReference {
    return StructuredDataReferenceFromJSONTyped(json, false);
}

export function StructuredDataReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructuredDataReference {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'appId': json['appId'] == null ? undefined : json['appId'],
        'createdAt': (new Date(json['createdAt'])),
        'createdBy': json['createdBy'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
        'updatedBy': json['updatedBy'],
        'name': json['name'],
        'dataObjectId': json['dataObjectId'] == null ? undefined : json['dataObjectId'],
        'type': json['type'] == null ? undefined : json['type'],
        'structuredDataOids': json['structuredDataOids'],
        'structuredDataContainerId': json['structuredDataContainerId'],
    };
}

export function StructuredDataReferenceToJSON(value?: Omit<StructuredDataReference, 'id'|'createdAt'|'createdBy'|'updatedAt'|'updatedBy'|'dataObjectId'|'type'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'structuredDataOids': value['structuredDataOids'],
        'structuredDataContainerId': value['structuredDataContainerId'],
    };
}

