/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeseriesAnnotationIO
 */
export interface TimeseriesAnnotationIO {
    /**
     * 
     * @type {string}
     * @memberof TimeseriesAnnotationIO
     */
    readonly appId?: string;
    /**
     * Start of the annotated interval in nanoseconds since Unix epoch.
     * @type {number}
     * @memberof TimeseriesAnnotationIO
     */
    startNs: number;
    /**
     * End of the annotated interval in nanoseconds since Unix epoch. Null for point annotations.
     * @type {number}
     * @memberof TimeseriesAnnotationIO
     */
    endNs?: number;
    /**
     * Annotation label / tag, e.g. 'anomaly', 'event-start'.
     * @type {string}
     * @memberof TimeseriesAnnotationIO
     */
    label: string;
    /**
     * Optional longer description.
     * @type {string}
     * @memberof TimeseriesAnnotationIO
     */
    description?: string;
    /**
     * True when created by the anomaly-detection pipeline, false for user-created annotations.
     * @type {boolean}
     * @memberof TimeseriesAnnotationIO
     */
    aiGenerated?: boolean;
    /**
     * Confidence score [0.0, 1.0] from anomaly detection. Null for human-created annotations.
     * @type {number}
     * @memberof TimeseriesAnnotationIO
     */
    confidence?: number;
}

/**
 * Check if a given object implements the TimeseriesAnnotationIO interface.
 */
export function instanceOfTimeseriesAnnotationIO(value: object): value is TimeseriesAnnotationIO {
    if (!('startNs' in value) || value['startNs'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function TimeseriesAnnotationIOFromJSON(json: any): TimeseriesAnnotationIO {
    return TimeseriesAnnotationIOFromJSONTyped(json, false);
}

export function TimeseriesAnnotationIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesAnnotationIO {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['appId'] == null ? undefined : json['appId'],
        'startNs': json['startNs'],
        'endNs': json['endNs'] == null ? undefined : json['endNs'],
        'label': json['label'],
        'description': json['description'] == null ? undefined : json['description'],
        'aiGenerated': json['aiGenerated'] == null ? undefined : json['aiGenerated'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
    };
}

export function TimeseriesAnnotationIOToJSON(value?: Omit<TimeseriesAnnotationIO, 'appId'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'startNs': value['startNs'],
        'endNs': value['endNs'],
        'label': value['label'],
        'description': value['description'],
        'aiGenerated': value['aiGenerated'],
        'confidence': value['confidence'],
    };
}

