/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimescaleStats
 */
export interface TimescaleStats {
    /**
     * Total on-disk bytes for the timeseries_data_points hypertable (all chunks, compressed + uncompressed).
     * @type {number}
     * @memberof TimescaleStats
     */
    hypertableSizeBytes: number;
    /**
     * Number of distinct timeseries channels registered across all containers.
     * @type {number}
     * @memberof TimescaleStats
     */
    channelCount: number;
    /**
     * Number of distinct containers that have at least one channel.
     * @type {number}
     * @memberof TimescaleStats
     */
    containerCount: number;
    /**
     * Approximate uncompressed size bytes (channelCount × avg-bytes-per-point estimate is not used here; this is the sum of before_compression_total_bytes across all compressed chunks).
     * @type {number}
     * @memberof TimescaleStats
     */
    uncompressedChunkBytes: number;
    /**
     * Compression ratio estimate (uncompressedChunkBytes / hypertableSizeBytes). Null when no chunks have been compressed yet.
     * @type {number}
     * @memberof TimescaleStats
     */
    compressionRatio?: number | null;
}

/**
 * Check if a given object implements the TimescaleStats interface.
 */
export function instanceOfTimescaleStats(value: object): value is TimescaleStats {
    if (!('hypertableSizeBytes' in value) || value['hypertableSizeBytes'] === undefined) return false;
    if (!('channelCount' in value) || value['channelCount'] === undefined) return false;
    if (!('containerCount' in value) || value['containerCount'] === undefined) return false;
    if (!('uncompressedChunkBytes' in value) || value['uncompressedChunkBytes'] === undefined) return false;
    return true;
}

export function TimescaleStatsFromJSON(json: any): TimescaleStats {
    return TimescaleStatsFromJSONTyped(json, false);
}

export function TimescaleStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimescaleStats {
    if (json == null) {
        return json;
    }
    return {
        
        'hypertableSizeBytes': json['hypertableSizeBytes'],
        'channelCount': json['channelCount'],
        'containerCount': json['containerCount'],
        'uncompressedChunkBytes': json['uncompressedChunkBytes'],
        'compressionRatio': json['compressionRatio'] == null ? undefined : json['compressionRatio'],
    };
}

export function TimescaleStatsToJSON(value?: TimescaleStats | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hypertableSizeBytes': value['hypertableSizeBytes'],
        'channelCount': value['channelCount'],
        'containerCount': value['containerCount'],
        'uncompressedChunkBytes': value['uncompressedChunkBytes'],
        'compressionRatio': value['compressionRatio'],
    };
}

