/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataPointValueType } from './DataPointValueType';
import {
    DataPointValueTypeFromJSON,
    DataPointValueTypeFromJSONTyped,
    DataPointValueTypeToJSON,
} from './DataPointValueType';

/**
 * 
 * @export
 * @interface TimeseriesEntity
 */
export interface TimeseriesEntity {
    /**
     * 
     * @type {number}
     * @memberof TimeseriesEntity
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeseriesEntity
     */
    containerId?: number;
    /**
     * 
     * @type {DataPointValueType}
     * @memberof TimeseriesEntity
     */
    valueType: DataPointValueType;
    /**
     * 
     * @type {string}
     * @memberof TimeseriesEntity
     */
    measurement: string;
    /**
     * 
     * @type {string}
     * @memberof TimeseriesEntity
     */
    device: string;
    /**
     * 
     * @type {string}
     * @memberof TimeseriesEntity
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof TimeseriesEntity
     */
    symbolicName: string;
    /**
     * 
     * @type {string}
     * @memberof TimeseriesEntity
     */
    field: string;
}



/**
 * Check if a given object implements the TimeseriesEntity interface.
 */
export function instanceOfTimeseriesEntity(value: object): value is TimeseriesEntity {
    if (!('valueType' in value) || value['valueType'] === undefined) return false;
    if (!('measurement' in value) || value['measurement'] === undefined) return false;
    if (!('device' in value) || value['device'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('symbolicName' in value) || value['symbolicName'] === undefined) return false;
    if (!('field' in value) || value['field'] === undefined) return false;
    return true;
}

export function TimeseriesEntityFromJSON(json: any): TimeseriesEntity {
    return TimeseriesEntityFromJSONTyped(json, false);
}

export function TimeseriesEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'containerId': json['containerId'] == null ? undefined : json['containerId'],
        'valueType': DataPointValueTypeFromJSON(json['valueType']),
        'measurement': json['measurement'],
        'device': json['device'],
        'location': json['location'],
        'symbolicName': json['symbolicName'],
        'field': json['field'],
    };
}

export function TimeseriesEntityToJSON(value?: TimeseriesEntity | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'containerId': value['containerId'],
        'valueType': DataPointValueTypeToJSON(value['valueType']),
        'measurement': value['measurement'],
        'device': value['device'],
        'location': value['location'],
        'symbolicName': value['symbolicName'],
        'field': value['field'],
    };
}

