/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeBetween
 */
export interface TimeBetween {
    /**
     * 
     * @type {string}
     * @memberof TimeBetween
     */
    start: string;
    /**
     * 
     * @type {string}
     * @memberof TimeBetween
     */
    end: string;
}

/**
 * Check if a given object implements the TimeBetween interface.
 */
export function instanceOfTimeBetween(value: object): value is TimeBetween {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function TimeBetweenFromJSON(json: any): TimeBetween {
    return TimeBetweenFromJSONTyped(json, false);
}

export function TimeBetweenFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeBetween {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'],
        'end': json['end'],
    };
}

export function TimeBetweenToJSON(value?: TimeBetween | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'start': value['start'],
        'end': value['end'],
    };
}

