/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * PROV1k read-side — compact predecessor DataObject summary plus the PROV-O / FAIR²R relationship type under which it was linked. relationshipType is always non-null; defaults to 'prov:wasInformedBy' for predecessors created before PROV1k.
 * @export
 * @interface TypedPredecessorSummary
 */
export interface TypedPredecessorSummary {
    /**
     * appId (UUID v7) of the predecessor DataObject.
     * @type {string}
     * @memberof TypedPredecessorSummary
     */
    readonly predecessorAppId?: string;
    /**
     * Numeric shepardId of the predecessor DataObject.
     * @type {number}
     * @memberof TypedPredecessorSummary
     */
    readonly predecessorId?: number;
    /**
     * Display name of the predecessor DataObject.
     * @type {string}
     * @memberof TypedPredecessorSummary
     */
    readonly predecessorName?: string;
    /**
     * Lifecycle status of the predecessor DataObject.
     * @type {string}
     * @memberof TypedPredecessorSummary
     */
    readonly predecessorStatus?: string | null;
    /**
     * PROV-O or FAIR²R relationship type: 'prov:wasInformedBy' (default / generic), 'prov:wasRevisionOf' (direct revision/correction), 'fair2r:repairs' (rework/NCR-repair).
     * @type {string}
     * @memberof TypedPredecessorSummary
     */
    readonly relationshipType?: TypedPredecessorSummaryRelationshipTypeEnum;
}


/**
 * @export
 */
export const TypedPredecessorSummaryRelationshipTypeEnum = {
    ProvwasInformedBy: 'prov:wasInformedBy',
    ProvwasRevisionOf: 'prov:wasRevisionOf',
    Fair2rrepairs: 'fair2r:repairs'
} as const;
export type TypedPredecessorSummaryRelationshipTypeEnum = typeof TypedPredecessorSummaryRelationshipTypeEnum[keyof typeof TypedPredecessorSummaryRelationshipTypeEnum];


/**
 * Check if a given object implements the TypedPredecessorSummary interface.
 */
export function instanceOfTypedPredecessorSummary(value: object): value is TypedPredecessorSummary {
    return true;
}

export function TypedPredecessorSummaryFromJSON(json: any): TypedPredecessorSummary {
    return TypedPredecessorSummaryFromJSONTyped(json, false);
}

export function TypedPredecessorSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypedPredecessorSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'predecessorAppId': json['predecessorAppId'] == null ? undefined : json['predecessorAppId'],
        'predecessorId': json['predecessorId'] == null ? undefined : json['predecessorId'],
        'predecessorName': json['predecessorName'] == null ? undefined : json['predecessorName'],
        'predecessorStatus': json['predecessorStatus'] == null ? undefined : json['predecessorStatus'],
        'relationshipType': json['relationshipType'] == null ? undefined : json['relationshipType'],
    };
}

export function TypedPredecessorSummaryToJSON(value?: Omit<TypedPredecessorSummary, 'predecessorAppId'|'predecessorId'|'predecessorName'|'predecessorStatus'|'relationshipType'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

