/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One unresolved selector in the YAML — operator follow-up checklist row.
 * @export
 * @interface UnresolvedEntryIO
 */
export interface UnresolvedEntryIO {
    /**
     * 1-based line number in the YAML payload (best-effort).
     * @type {number}
     * @memberof UnresolvedEntryIO
     */
    line?: number;
    /**
     * "source" or "target" — which side of the entry did not resolve.
     * @type {string}
     * @memberof UnresolvedEntryIO
     */
    side?: string;
    /**
     * Why the selector did not match — typically zero DataObjects.
     * @type {string}
     * @memberof UnresolvedEntryIO
     */
    reason?: string;
}

/**
 * Check if a given object implements the UnresolvedEntryIO interface.
 */
export function instanceOfUnresolvedEntryIO(value: object): value is UnresolvedEntryIO {
    return true;
}

export function UnresolvedEntryIOFromJSON(json: any): UnresolvedEntryIO {
    return UnresolvedEntryIOFromJSONTyped(json, false);
}

export function UnresolvedEntryIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnresolvedEntryIO {
    if (json == null) {
        return json;
    }
    return {
        
        'line': json['line'] == null ? undefined : json['line'],
        'side': json['side'] == null ? undefined : json['side'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function UnresolvedEntryIOToJSON(value?: UnresolvedEntryIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'line': value['line'],
        'side': value['side'],
        'reason': value['reason'],
    };
}

