/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface URIReference
 */
export interface URIReference {
    /**
     * 
     * @type {number}
     * @memberof URIReference
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof URIReference
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof URIReference
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof URIReference
     */
    readonly updatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof URIReference
     */
    readonly updatedBy: string | null;
    /**
     * 
     * @type {string}
     * @memberof URIReference
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof URIReference
     */
    readonly dataObjectId?: number;
    /**
     * 
     * @type {string}
     * @memberof URIReference
     */
    readonly type?: string;
    /**
     * 
     * @type {string}
     * @memberof URIReference
     */
    uri: string;
}

/**
 * Check if a given object implements the URIReference interface.
 */
export function instanceOfURIReference(value: object): value is URIReference {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('uri' in value) || value['uri'] === undefined) return false;
    return true;
}

export function URIReferenceFromJSON(json: any): URIReference {
    return URIReferenceFromJSONTyped(json, false);
}

export function URIReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): URIReference {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'createdBy': json['createdBy'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
        'updatedBy': json['updatedBy'],
        'name': json['name'],
        'dataObjectId': json['dataObjectId'] == null ? undefined : json['dataObjectId'],
        'type': json['type'] == null ? undefined : json['type'],
        'uri': json['uri'],
    };
}

export function URIReferenceToJSON(value?: Omit<URIReference, 'id'|'createdAt'|'createdBy'|'updatedAt'|'updatedBy'|'dataObjectId'|'type'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'uri': value['uri'],
    };
}

