/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    readonly username: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof User
     */
    readonly subscriptionIds: Array<number>;
    /**
     *
     * @type {Array<string>}
     * @memberof User
     */
    readonly apiKeyIds: Array<string>;
    /**
     * ORCID identifier (16-digit ISO 7064 checked). Null until set via PATCH /v2/users/me.
     * @type {string}
     * @memberof User
     */
    orcid?: string | null;
    /**
     * Optional display-name override set via PATCH /v2/users/me.
     * @type {string}
     * @memberof User
     */
    displayName?: string | null;
    /**
     * Computed display name: displayName override → firstName+lastName → redacted username.
     * @type {string}
     * @memberof User
     */
    readonly effectiveDisplayName?: string;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('subscriptionIds' in value) || value['subscriptionIds'] === undefined) return false;
    if (!('apiKeyIds' in value) || value['apiKeyIds'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'email': json['email'] == null ? undefined : json['email'],
        'subscriptionIds': json['subscriptionIds'],
        'apiKeyIds': json['apiKeyIds'],
        'orcid': json['orcid'] == null ? undefined : json['orcid'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'effectiveDisplayName': json['effectiveDisplayName'] == null ? undefined : json['effectiveDisplayName'],
    };
}

export function UserToJSON(value?: Omit<User, 'username'|'subscriptionIds'|'apiKeyIds'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
    };
}

