/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Vocabulary
 */
export interface Vocabulary {
    /**
     * UUID v7 application-level identifier.
     * @type {string}
     * @memberof Vocabulary
     */
    readonly appId?: string;
    /**
     * Canonical namespace URI / IRI prefix.
     * @type {string}
     * @memberof Vocabulary
     */
    uri?: string;
    /**
     * Human-readable label.
     * @type {string}
     * @memberof Vocabulary
     */
    label?: string;
    /**
     * Short namespace prefix (e.g. 'dcterms').
     * @type {string}
     * @memberof Vocabulary
     */
    prefix?: string | null;
    /**
     * Optional free-text description of the vocabulary's scope.
     * @type {string}
     * @memberof Vocabulary
     */
    description?: string | null;
    /**
     * When false, this vocabulary is hidden from autocomplete and predicate lookup.
     * @type {boolean}
     * @memberof Vocabulary
     */
    enabled?: boolean;
    /**
     * Vocabulary kind: null = system/operator vocabulary; 'PERSONAL' = user-minted personal vocabulary.
     * @type {string}
     * @memberof Vocabulary
     */
    type?: string | null;
    /**
     * appId of the owning User. Only set when type is 'PERSONAL'.
     * @type {string}
     * @memberof Vocabulary
     */
    ownedByUserAppId?: string | null;
}

/**
 * Check if a given object implements the Vocabulary interface.
 */
export function instanceOfVocabulary(value: object): value is Vocabulary {
    return true;
}

export function VocabularyFromJSON(json: any): Vocabulary {
    return VocabularyFromJSONTyped(json, false);
}

export function VocabularyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Vocabulary {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['appId'] == null ? undefined : json['appId'],
        'uri': json['uri'] == null ? undefined : json['uri'],
        'label': json['label'] == null ? undefined : json['label'],
        'prefix': json['prefix'] == null ? undefined : json['prefix'],
        'description': json['description'] == null ? undefined : json['description'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'type': json['type'] == null ? undefined : json['type'],
        'ownedByUserAppId': json['ownedByUserAppId'] == null ? undefined : json['ownedByUserAppId'],
    };
}

export function VocabularyToJSON(value?: Omit<Vocabulary, 'appId'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'uri': value['uri'],
        'label': value['label'],
        'prefix': value['prefix'],
        'description': value['description'],
        'enabled': value['enabled'],
        'type': value['type'],
        'ownedByUserAppId': value['ownedByUserAppId'],
    };
}

