/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FilterItem } from './FilterItem';
import {
    FilterItemFromJSON,
    FilterItemFromJSONTyped,
    FilterItemToJSON,
} from './FilterItem';
import type { TimeBetween } from './TimeBetween';
import {
    TimeBetweenFromJSON,
    TimeBetweenFromJSONTyped,
    TimeBetweenToJSON,
} from './TimeBetween';

/**
 * 
 * @export
 * @interface WhereClause
 */
export interface WhereClause {
    /**
     * 
     * @type {TimeBetween}
     * @memberof WhereClause
     */
    timeBetween: TimeBetween;
    /**
     * 
     * @type {Array<number>}
     * @memberof WhereClause
     */
    containerIdIn?: Array<number>;
    /**
     * 
     * @type {Array<FilterItem>}
     * @memberof WhereClause
     */
    filters?: Array<FilterItem>;
}

/**
 * Check if a given object implements the WhereClause interface.
 */
export function instanceOfWhereClause(value: object): value is WhereClause {
    if (!('timeBetween' in value) || value['timeBetween'] === undefined) return false;
    return true;
}

export function WhereClauseFromJSON(json: any): WhereClause {
    return WhereClauseFromJSONTyped(json, false);
}

export function WhereClauseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WhereClause {
    if (json == null) {
        return json;
    }
    return {
        
        'timeBetween': TimeBetweenFromJSON(json['time_between']),
        'containerIdIn': json['container_id_in'] == null ? undefined : json['container_id_in'],
        'filters': json['filters'] == null ? undefined : ((json['filters'] as Array<any>).map(FilterItemFromJSON)),
    };
}

export function WhereClauseToJSON(value?: WhereClause | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'time_between': TimeBetweenToJSON(value['timeBetween']),
        'container_id_in': value['containerIdIn'],
        'filters': value['filters'] == null ? undefined : ((value['filters'] as Array<any>).map(FilterItemToJSON)),
    };
}

