/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WikiWriteResponseIO
 */
export interface WikiWriteResponseIO {
    /**
     * 
     * @type {number}
     * @memberof WikiWriteResponseIO
     */
    labJournalEntryId?: number;
    /**
     * 
     * @type {string}
     * @memberof WikiWriteResponseIO
     */
    generatedSummary?: string;
    /**
     * 
     * @type {string}
     * @memberof WikiWriteResponseIO
     */
    activityAppId?: string;
    /**
     * 
     * @type {number}
     * @memberof WikiWriteResponseIO
     */
    inputTokens?: number;
    /**
     * 
     * @type {number}
     * @memberof WikiWriteResponseIO
     */
    outputTokens?: number;
}

/**
 * Check if a given object implements the WikiWriteResponseIO interface.
 */
export function instanceOfWikiWriteResponseIO(value: object): value is WikiWriteResponseIO {
    return true;
}

export function WikiWriteResponseIOFromJSON(json: any): WikiWriteResponseIO {
    return WikiWriteResponseIOFromJSONTyped(json, false);
}

export function WikiWriteResponseIOFromJSONTyped(json: any, ignoreDiscriminator: boolean): WikiWriteResponseIO {
    if (json == null) {
        return json;
    }
    return {
        
        'labJournalEntryId': json['labJournalEntryId'] == null ? undefined : json['labJournalEntryId'],
        'generatedSummary': json['generatedSummary'] == null ? undefined : json['generatedSummary'],
        'activityAppId': json['activityAppId'] == null ? undefined : json['activityAppId'],
        'inputTokens': json['inputTokens'] == null ? undefined : json['inputTokens'],
        'outputTokens': json['outputTokens'] == null ? undefined : json['outputTokens'],
    };
}

export function WikiWriteResponseIOToJSON(value?: WikiWriteResponseIO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'labJournalEntryId': value['labJournalEntryId'],
        'generatedSummary': value['generatedSummary'],
        'activityAppId': value['activityAppId'],
        'inputTokens': value['inputTokens'],
        'outputTokens': value['outputTokens'],
    };
}

