oidc.public=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqT+Rq//jyApkki/ShMTRTqsWPnOl/7Uku7E8pvwVXvrom41bI6joQVVMMm8TpZ7il/eZcWqef2gHf1xvsox9FSq2tbkNdTcpCVBg5/U/JvNJfyzd5oWXIihf072HrMHhnziMBCJHMo9cE2SJsCu/F0xDs+6Pw/+f5dhlP20Tk2quYKpEc9I8FbcJQwNfg5+dQERhYND5sU1l6K0Ubx3DJQRcklyyfCavQ2Rok/lVLSA7J36aJYoyc16j8Tv53txkMljdCWO3pAsw7edayBDN00FCgZocWiVO/XIBYe+L7zZ/YkROw9+xEh4RLdaHWFHds6iNhB5fOYhRa2LDg4MFmQIDAQAB
influx.host=localhost:8086
influx.username=influx
influx.password=shepard
neo4j.host=localhost:7687
neo4j.username=neo4j
neo4j.password=shepard
mongo.host=localhost:27017
mongo.username=mongo
mongo.password=shepard
mongo.authDB=admin
logging.appender=Console
