oidc.public=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAriUyhqz1q29DbYu9zqHZTkxcepIkYKY6FzK0aVMy5kWtUfpOYihO3yw9N0sqsgDTGg7nO9FcCFEtvK3ucPk349aRH5yftscF6lquWnWPA9odDePSBWv4kDL0BpJ5HTvNrkoBkG73rypfY7vItM9IWE9laV4PEVWRoEnVYotc2aHjIfRWrdHtyB33Paulfmb6wn1m2NJOY3WZWSgauOiVhfre48TTxsaS+lQbl0F23q+qFhhp33ZYhWP7hHhSRbBoQKVedYzUg7RdP0h0pIKiAAc9zIuIimDjJcLjJVx+/OLxKjHlnFZ5DyGgVLJw7HSY7CsMDMlV1+6LiIsb5I+jMQIDAQAB
oidc.authority=https://keycloak.bt-au-k8s.intra.dlr.de/realms/master/
oidc.role=
influx.host=[::1]:8086
influx.username=influx
influx.password=shepard
neo4j.host=[::1]:7687
neo4j.username=neo4j
neo4j.password=shepard
mongo.host=[::1]:27017
mongo.username=mongo
mongo.password=shepard
mongo.authDB=admin
