services:
  backend:
    extends:
      file: docker-compose.yml
      service: frontend

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend

  neo4j:
    extends:
      file: docker-compose.yml
      service: neo4j

  mongodb:
    extends:
      file: docker-compose.yml
      service: mongodb

  mongoexpress:
    extends:
      file: docker-compose.yml
      service: mongoexpress

  influxdb:
    extends:
      file: docker-compose.yml
      service: influxdb

  chronograf:
    extends:
      file: docker-compose.yml
      service: chronograf

  caddy:
    extends:
      file: docker-compose.yml
      service: caddy

  timescaledb:
    extends:
      file: docker-compose.yml
      service: timescaledb

  nuxtend:
    image: registry.gitlab.com/dlr-shepard/shepard/nuxtend:dev
    restart: unless-stopped
    environment:
      NUXT_PUBLIC_BACKEND_API_URL: ${BACKEND_URL}shepard/api
      AUTH_ORIGIN: ${FRONTEND_URL}/api/auth
      NUXT_AUTH_SECRET: ${FRONTEND_AUTH_SECRET}
      NUXT_OIDC_CLIENT_ID: ${CLIENT_ID}
      NUXT_OIDC_ISSUER: ${OIDC_AUTHORITY}
      SESSION_REFRESH_INTERVAL: ${SESSION_REFRESH_INTERVAL}
    depends_on:
      - backend
    networks:
      - frontend

  postgis:
    image: postgis/postgis:16-3.5
    container_name: postgis
    environment:
      POSTGRES_DB: ${POSTGRES_DB-postgres}
      POSTGRES_USER: ${POSTGRES_USER-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-password}
      POSTGRES_SHEPARD_USER: ${POSTGRES_SHEPARD_USER-shepard}
      POSTGRES_SHEPARD_USER_PW: ${POSTGRES_SHEPARD_USER_PW-shepard_secret}
    shm_size: "6GB"
    ports:
      - "5433:5432"
    volumes:
      - ./docker-entrypoint-initdb.d/postgis/00-init-postgis-db.sh:/docker-entrypoint-initdb.d/00-init-postgis-db.sh
      - postgis_data:/var/lib/postgresql/data
    networks:
      - shepard
    restart: unless-stopped

networks:
  shepard:
  mongo:
  influxdata:
  frontend:
