services:
  backend:
    extends:
      file: docker-compose.yml
      service: frontend

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend

  neo4j:
    extends:
      file: docker-compose.yml
      service: neo4j

  mongodb:
    extends:
      file: docker-compose.yml
      service: mongodb

  mongoexpress:
    extends:
      file: docker-compose.yml
      service: mongoexpress

  influxdb:
    extends:
      file: docker-compose.yml
      service: influxdb

  chronograf:
    extends:
      file: docker-compose.yml
      service: chronograf

  caddy:
    extends:
      file: docker-compose.yml
      service: caddy

  timescaledb:
    extends:
      file: docker-compose.yml
      service: timescaledb

  nuxtend:
    image: registry.gitlab.com/dlr-shepard/shepard/nuxtend:dev
    restart: unless-stopped
    environment:
      NUXT_PUBLIC_BACKEND_API_URL: ${BACKEND_URL}shepard/api
      AUTH_ORIGIN: ${FRONTEND_URL}/api/auth
      NUXT_AUTH_SECRET: ${FRONTEND_AUTH_SECRET}
      NUXT_OIDC_CLIENT_ID: ${CLIENT_ID}
      NUXT_OIDC_ISSUER: ${OIDC_AUTHORITY}
      SESSION_REFRESH_INTERVAL: ${SESSION_REFRESH_INTERVAL}
    depends_on:
      - backend
    networks:
      - frontend

networks:
  shepard:
  mongo:
  influxdata:
  timescaledata:
  frontend:
