services:
  backend:
    image: registry.gitlab.com/dlr-shepard/shepard/backend:5.1.2
    restart: unless-stopped
    environment:
      JAVA_OPTS: "-Xms2G -Xmx2G"
      OIDC_PUBLIC: ${OIDC_PUBLIC}
      OIDC_AUTHORITY: ${OIDC_AUTHORITY}
      OIDC_ROLE: ${OIDC_ROLE}
      INFLUX_HOST: influxdb:8086
      INFLUX_USERNAME: admin
      INFLUX_PASSWORD: ${INFLUX_PW}
      NEO4J_HOST: neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: ${NEO4J_PW}
      QUARKUS_MONGODB_CONNECTION_STRING: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://timescaledb:5432/${POSTGRES_DB}
      QUARKUS_DATASOURCE_USERNAME: ${POSTGRES_SHEPARD_USER}
      QUARKUS_DATASOURCE_PASSWORD: ${POSTGRES_SHEPARD_USER_PW}
      QUARKUS_DATASOURCE_SPATIAL_JDBC_URL: jdbc:postgresql://postgis:5432/${POSTGRES_DB}
      QUARKUS_DATASOURCE_SPATIAL_USERNAME: ${POSTGRES_SHEPARD_USER}
      QUARKUS_DATASOURCE_SPATIAL_PASSWORD: ${POSTGRES_SHEPARD_USER_PW}
      SHEPARD_MIGRATION_MODE_ENABLED: ${SHEPARD_MIGRATION_MODE_ENABLED}
      SHEPARD_SPATIAL_DATA_ENABLED: ${SHEPARD_SPATIAL_DATA_ENABLED}
      SHEPARD_AUTOCONVERT_INT: ${SHEPARD_AUTOCONVERT_INT}
    volumes:
      - /opt/shepard/backend/logs:/deployments/logs
      - /opt/shepard/backend/config:/home/jboss/.shepard
    depends_on:
      - neo4j
      - mongodb
      - timescaledb
    networks:
      - shepard

  frontend-old:
    image: registry.gitlab.com/dlr-shepard/shepard/frontend:4.0.0
    environment:
      VUE_APP_BACKEND: ${BACKEND_URL}shepard/api
      VUE_APP_OIDC_AUTHORITY: ${OIDC_AUTHORITY}
      VUE_APP_CLIENT_ID: ${CLIENT_ID}
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - frontend
    profiles:
      - frontend-old

  frontend:
    image: registry.gitlab.com/dlr-shepard/shepard/frontend:5.1.2
    restart: unless-stopped
    environment:
      NUXT_PUBLIC_BACKEND_API_URL: ${BACKEND_URL}shepard/api
      AUTH_ORIGIN: ${FRONTEND_URL}api/auth
      NUXT_AUTH_SECRET: ${FRONTEND_AUTH_SECRET}
      NUXT_OIDC_CLIENT_ID: ${CLIENT_ID}
      NUXT_OIDC_ISSUER: ${OIDC_AUTHORITY}
      SESSION_REFRESH_INTERVAL: ${SESSION_REFRESH_INTERVAL}
    depends_on:
      - backend
    networks:
      - frontend

  neo4j:
    # For instructions on how to update Neo4j from version 4.4 to 5.24, please read the migration guide at: https://gitlab.com/dlr-shepard/shepard/-/merge_requests/315#goal_net-description
    image: neo4j:5.24
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PW}
      NEO4J_server_memory_heap_initial__size: 2G
      NEO4J_server_memory_heap_max__size: 2G
      NEO4J_server_memory_pagecache_size: 3G
    ports:
      - "7687:7687"
    volumes:
      - /opt/shepard/neo4j/logs:/logs
      - /opt/shepard/neo4j/plugins:/plugins
      - /opt/shepard/neo4j/data:/var/lib/neo4j/data
    restart: unless-stopped
    networks:
      - shepard

  mongodb:
    # Please only update the MongoDB incrementally, follow this guide if you need help: https://gitlab.com/dlr-shepard/shepard/-/merge_requests/306
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - /opt/shepard/mongodb/db:/data/db
      - /opt/shepard/mongodb/configdb:/data/configdb
      - ./docker-entrypoint-initdb.d/mongodb/00-create-mongo-user.js:/docker-entrypoint-initdb.d/00-create-mongo-user.js
    restart: unless-stopped
    networks:
      - shepard
      - mongo
    command: --wiredTigerCacheSizeGB 2.0

  mongoexpress:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - mongo

  timescaledb:
    image: timescale/timescaledb:2.18.1-pg16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SHEPARD_USER: ${POSTGRES_SHEPARD_USER}
      POSTGRES_SHEPARD_USER_PW: ${POSTGRES_SHEPARD_USER_PW}
      PGDATA: /var/lib/postgres/data
    volumes:
      - /opt/shepard/timescaledb:/var/lib/postgres/data
      - ./docker-entrypoint-initdb.d/postgres/00-init-postgres-db.sh:/docker-entrypoint-initdb.d/00-init-postgres-db.sh
    restart: unless-stopped
    networks:
      - shepard

  postgis:
    image: postgis/postgis:16-3.5
    container_name: postgis
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SHEPARD_USER: ${POSTGRES_SHEPARD_USER}
      POSTGRES_SHEPARD_USER_PW: ${POSTGRES_SHEPARD_USER_PW}
    shm_size: "6GB"
    ports:
      - "5433:5432"
    volumes:
      - ./docker-entrypoint-initdb.d/postgis/00-init-postgis-db.sh:/docker-entrypoint-initdb.d/00-init-postgis-db.sh
      - /opt/shepard/postgis/db:/var/lib/postgresql/data
    networks:
      - shepard
    restart: unless-stopped
    profiles:
      - spatial

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./proxy/ssl:/etc/caddy/ssl:ro
      - ./proxy/shepard:/var/www/shepard:ro
      - /opt/shepard/caddy/data:/data
      - /opt/shepard/caddy/config:/config
    restart: unless-stopped
    networks:
      - shepard
      - mongo
      - influxdata
      - frontend

  timescale-migration-preparation:
    image: registry.gitlab.com/dlr-shepard/shepard/timescale-migration-preparation:5.0.0
    volumes:
      - ./log:/app/log
    env_file:
      - .env
    depends_on:
      - influxdb
      - neo4j
    networks:
      - shepard
    profiles:
      - timescale-migration-preparation

  prometheus:
    image: prom/prometheus:v3.3.0
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - shepard
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:11.3.0-security-01
    networks:
      - shepard
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_BASIC_ENABLED=true
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    profiles:
      - monitoring

networks:
  shepard:
  mongo:
  influxdata:
  frontend:

volumes:
  grafana-storage: {}
