quarkus.http.root-path=/shepard/api
quarkus.http.non-application-root-path=/shepard/doc
quarkus.shutdown.timeout=PT10S

# Health check
quarkus.smallrye-health.root-path=/shepard/api/healthz
quarkus.smallrye-health.openapi.included=true
# Disable the default health check from the JDBC
quarkus.datasource.health.enabled=false
# Disable default MongoDB extention health check
quarkus.mongodb.health.enabled=false

#version endpoint
shepard.version=${project.version}

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,HEAD,OPTIONS,DELETE,PUT
quarkus.http.cors.headers=Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization,X-API-KEY

# Logging
quarkus.console.color=true
quarkus.log.level=INFO
quarkus.log.min-level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss.SSS} [%p] [%c{5.}] (%t) %s%e%n
quarkus.log.file.enable=true
quarkus.log.file.path=logs/shepard.log
# https://docs.redhat.com/en/documentation/red_hat_build_of_quarkus/3.2/html/logging_configuration/logging-configuration#root-logger-configuration
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5p] [%c] (%t) %s%e%n
quarkus.log.file.level=INFO
quarkus.log.file.rotation.max-backup-index=10
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd

# Influx DB
influx.host=influxdb:8086

# Neo4j
neo4j.host=[::1]:7687

# MongoDB
quarkus.mongodb.connection-string=mongodb://mongo@mongodb:27017

# Disable hibernate, flyway & timeseries features by default
shepard.experimental-timeseries.enabled=false

quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.active=${shepard.experimental-timeseries.enabled}
quarkus.flyway.baseline-on-migrate=${shepard.experimental-timeseries.enabled}
quarkus.flyway.migrate-at-start=${shepard.experimental-timeseries.enabled}

# OpenAPI & Swagger
quarkus.swagger-ui.always-include=true
mp.openapi.extensions.smallrye.operationIdStrategy=METHOD
quarkus.smallrye-openapi.store-schema-directory=target/openapi/
quarkus.smallrye-openapi.open-api-version=3.0.1
quarkus.smallrye-openapi.info-title=${project.name}
quarkus.smallrye-openapi.info-version=${project.version}
# keep scanning for annotations, while also using static openapi.yml template
mp.openapi.scan.disable=false
quarkus.smallrye-openapi.ignore-static-document=false
quarkus.smallrye-openapi.path=openapi.json

# Quarkus File Uploads
# Set unlimited max-body size for file uploads
# https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.6
quarkus.http.limits.max-body-size=

# Quarkus Metrics
# Enable Micrometer metrics support in general.
quarkus.micrometer.enabled=true

# Provide metrics as json on /metrics endpoint
quarkus.micrometer.export.json.enabled=true

# Activate/Deactivate http server metrics.
quarkus.micrometer.binder.http-server.enabled=true

# Netty uses memory allocators to pool the memory buffers for reuse.
quarkus.micrometer.binder.netty.enabled=true

# Activates/Deactivates metrics for the java virtual machine.
quarkus.micrometer.binder.jvm=true

# Activates/Deactivates metrics for the system.
quarkus.micrometer.binder.system=true

# Activates/Deactivates metrics for vertx.
quarkus.micrometer.binder.vertx.enabled=true

# Activates/Deactivates metrics for Hibernate.
quarkus.hibernate-orm.metrics.enabled=true

# Activates/Deactivates metrics for MongoDB.
quarkus.mongodb.metrics.enabled=true

# Enable exporting of metrics
quarkus.micrometer.export.json.path=metrics/json
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=metrics/prometheus

# Dev Profile
%dev.quarkus.mongodb.connection-string=mongodb://username:password@[::1]:27017/database

%dev.influx.host=[::1]:8086
%dev.influx.username=influx
%dev.influx.password=shepard

%dev.neo4j.host=[::1]:7687
%dev.neo4j.username=neo4j
%dev.neo4j.password=shepardshepard

%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
%dev.quarkus.datasource.username=shepard
%dev.quarkus.datasource.password=shepard_secret

%dev.shepard.experimental-timeseries.enabled=true

# Define test Profile to Extend the dev profile
%test.quarkus.config.profile.parent=dev
