quarkus.http.root-path=/shepard/api
quarkus.http.non-application-root-path=/shepard/doc
quarkus.shutdown.timeout=PT10S

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,HEAD,OPTIONS,DELETE,PUT
quarkus.http.cors.headers=Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization,X-API-KEY

# Logging
quarkus.console.color=true
quarkus.log.level=INFO
quarkus.log.min-level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss.SSS} [%p] [%c{5.}] (%t) %s%e%n
quarkus.log.file.enable=true
quarkus.log.file.path=logs/shepard.log
# https://docs.redhat.com/en/documentation/red_hat_build_of_quarkus/3.2/html/logging_configuration/logging-configuration#root-logger-configuration
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5p] [%c] (%t) %s%e%n
quarkus.log.file.level=INFO
quarkus.log.file.rotation.max-backup-index=10
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd

# Influx DB
influx.host=influxdb:8086
influx.username=influx
influx.password=shepard

# Neo4j
neo4j.host=[::1]:7687
neo4j.username=neo4j
neo4j.password=shepard1234

# MongoDB
quarkus.mongodb.connection-string=mongodb://mongo@mongodb:27017

# PostgreSQL + timescaleDB
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.datasource.username=postgres
quarkus.datasource.password=password
quarkus.hibernate-orm.database.generation=drop-and-create

# OpenAPI & Swagger
quarkus.swagger-ui.always-include=true
mp.openapi.extensions.smallrye.operationIdStrategy=METHOD
quarkus.smallrye-openapi.store-schema-directory=target/openapi/
quarkus.smallrye-openapi.open-api-version=3.0.1
quarkus.smallrye-openapi.info-title=${project.name}
quarkus.smallrye-openapi.info-version=${project.version}
# keep scanning for annotations, while also using static openapi.yml template
mp.openapi.scan.disable=false
quarkus.smallrye-openapi.ignore-static-document=false
quarkus.smallrye-openapi.path=openapi.json

# Quarkus File Uploads
# Set unlimited max-body size for file uploads
# https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.6
quarkus.http.limits.max-body-size=
