oidc.public=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxEaUV7qV+I5OnnenzW20/QXx/yWElZYZcfjXT/gaAh6oq87AOmHh5weOFsRZVC7WU5sEjRKqH+C6kO/0xHoyGrngVTelteL1JYt/cZ9ynVd2A8nWpU+FCjQ8V174RgHuulyqiY4gGQR0lonLUGrShRv+blg9z8+ggm08U1ZOQh0spBpbcxpOoujyuxh2g1oM6RgKbNJv3dEPN1AtNEutOwXrqxELka2/d96iu9HKd2m6EAeOs3ylaTvPoeF1YQbOhoMooOlv0ToH5EMhc1mCyvsc0hXh3ggcFJeulB7ONXGfyeWeFZnL+PIuREY6OnGzD8xglsZjseBZtocD4SGNyQIDAQAB
oidc.authority=https://keycloak.desh.dev.xitaso.com/realms/shepard/
oidc.role=
influx.host=[::1]:8086
influx.username=influx
influx.password=shepard
neo4j.host=[::1]:7687
neo4j.username=neo4j
neo4j.password=shepard
mongo.host=[::1]:27017
mongo.username=mongo
mongo.password=shepard
mongo.authDB=admin
