/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AasServerSelfDescription,
  AasShell,
  PagedResponse,
} from '../models/index';
import {
    AasServerSelfDescriptionFromJSON,
    AasServerSelfDescriptionToJSON,
    AasShellFromJSON,
    AasShellToJSON,
    PagedResponseFromJSON,
    PagedResponseToJSON,
} from '../models/index';

export interface GetAasShellRequest {
    aasId: string;
}

export interface ListAasShellSubmodelsRequest {
    aasId: string;
    page?: number;
    pageSize?: number;
}

export interface ListAasShellsRequest {
    page?: number;
    pageSize?: number;
}

/**
 * 
 */
export class AASApi extends runtime.BaseAPI {

    /**
     * Discoverable JSON document describing this shepard\'s AAS integration: API profile, supported submodel templates, shell count, and outbound registry registrations. Unauthenticated. See `aidocs/52 §4a.5`.
     * [v2] AAS server self-description
     */
    async describeAasServerRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AasServerSelfDescription>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/aas/.well-known/aas-server`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AasServerSelfDescriptionFromJSON(jsonValue));
    }

    /**
     * Discoverable JSON document describing this shepard\'s AAS integration: API profile, supported submodel templates, shell count, and outbound registry registrations. Unauthenticated. See `aidocs/52 §4a.5`.
     * [v2] AAS server self-description
     */
    async describeAasServer(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AasServerSelfDescription> {
        const response = await this.describeAasServerRaw(initOverrides);
        return await response.value();
    }

    /**
     * Accepts `{aasId}` as (a) the base64url-encoded Shell IRI (`urn:shepard:collection:{appId}`) per IDTA-01002-3-2 §4.3, or (b) the bare shepard Collection appId. Returns 404 when the Shell does not exist or the caller lacks read access (404-on-no-read discipline — not 403). See `aidocs/integrations/52-aas-backend-integration.md §7`.
     * [v2] Get a single Collection as an IDTA AAS v3 Shell (AAS1b).
     */
    async getAasShellRaw(requestParameters: GetAasShellRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AasShell>> {
        if (requestParameters['aasId'] == null) {
            throw new runtime.RequiredError(
                'aasId',
                'Required parameter "aasId" was null or undefined when calling getAasShell().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/aas/shells/{aasId}`.replace(`{${"aasId"}}`, encodeURIComponent(String(requestParameters['aasId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AasShellFromJSON(jsonValue));
    }

    /**
     * Accepts `{aasId}` as (a) the base64url-encoded Shell IRI (`urn:shepard:collection:{appId}`) per IDTA-01002-3-2 §4.3, or (b) the bare shepard Collection appId. Returns 404 when the Shell does not exist or the caller lacks read access (404-on-no-read discipline — not 403). See `aidocs/integrations/52-aas-backend-integration.md §7`.
     * [v2] Get a single Collection as an IDTA AAS v3 Shell (AAS1b).
     */
    async getAasShell(requestParameters: GetAasShellRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AasShell> {
        const response = await this.getAasShellRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns one IDTA AAS v3 Reference per top-level DataObject of the Collection identified by `{aasId}` (base64url-encoded Shell IRI or bare appId). Each Reference has `type=ExternalReference` and a single Submodel key with value `urn:shepard:dataobject:{appId}`. Returns 404 when the Shell does not exist or the caller lacks read access (404-on-no-read discipline). See `aidocs/integrations/52-aas-backend-integration.md §4b`. Uses page-offset pagination (default page=0, pageSize=50, server cap 200).
     * [v2] List Submodel references for a Shell (AAS1b).
     */
    async listAasShellSubmodelsRaw(requestParameters: ListAasShellSubmodelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedResponse>> {
        if (requestParameters['aasId'] == null) {
            throw new runtime.RequiredError(
                'aasId',
                'Required parameter "aasId" was null or undefined when calling listAasShellSubmodels().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/aas/shells/{aasId}/submodels`.replace(`{${"aasId"}}`, encodeURIComponent(String(requestParameters['aasId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedResponseFromJSON(jsonValue));
    }

    /**
     * Returns one IDTA AAS v3 Reference per top-level DataObject of the Collection identified by `{aasId}` (base64url-encoded Shell IRI or bare appId). Each Reference has `type=ExternalReference` and a single Submodel key with value `urn:shepard:dataobject:{appId}`. Returns 404 when the Shell does not exist or the caller lacks read access (404-on-no-read discipline). See `aidocs/integrations/52-aas-backend-integration.md §4b`. Uses page-offset pagination (default page=0, pageSize=50, server cap 200).
     * [v2] List Submodel references for a Shell (AAS1b).
     */
    async listAasShellSubmodels(requestParameters: ListAasShellSubmodelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedResponse> {
        const response = await this.listAasShellSubmodelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns one AssetAdministrationShell per Collection the authenticated caller may read. Shells carry `id` (URN from appId), `idShort` (sanitised name), `assetInformation`, optional `description`, and an empty `submodels` list. Submodels are populated by AAS1b. See `aidocs/integrations/52-aas-backend-integration.md §4a`. Uses page-offset pagination (default page=0, pageSize=50, server cap 200).
     * [v2] List Collections as IDTA AAS v3 Shells (AAS1a).
     */
    async listAasShellsRaw(requestParameters: ListAasShellsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/aas/shells`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedResponseFromJSON(jsonValue));
    }

    /**
     * Returns one AssetAdministrationShell per Collection the authenticated caller may read. Shells carry `id` (URN from appId), `idShort` (sanitised name), `assetInformation`, optional `description`, and an empty `submodels` list. Submodels are populated by AAS1b. See `aidocs/integrations/52-aas-backend-integration.md §4a`. Uses page-offset pagination (default page=0, pageSize=50, server cap 200).
     * [v2] List Collections as IDTA AAS v3 Shells (AAS1a).
     */
    async listAasShells(requestParameters: ListAasShellsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedResponse> {
        const response = await this.listAasShellsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
