/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AasIdtaImportResult,
} from '../models/index';
import {
    AasIdtaImportResultFromJSON,
    AasIdtaImportResultToJSON,
} from '../models/index';

/**
 * 
 */
export class AASAdminApi extends runtime.BaseAPI {

    /**
     * Idempotently upserts the three bundled IDTA Submodel Templates (Digital Nameplate v3.0, Technical Data v2.0, Time Series Data v1.1) as ShepardTemplate entities with templateKind = AAS_SUBMODEL_TEMPLATE. An entry is skipped when the live record already has identical body, description, and tags. Returns the list of created/updated templates and the count of skipped entries.
     * [v2] Import bundled IDTA Submodel Templates (AAS1d).
     */
    async importAasIdtaTemplatesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AasIdtaImportResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/admin/aas/import-idta-templates`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AasIdtaImportResultFromJSON(jsonValue));
    }

    /**
     * Idempotently upserts the three bundled IDTA Submodel Templates (Digital Nameplate v3.0, Technical Data v2.0, Time Series Data v1.1) as ShepardTemplate entities with templateKind = AAS_SUBMODEL_TEMPLATE. An entry is skipped when the live record already has identical body, description, and tags. Returns the list of created/updated templates and the count of skipped entries.
     * [v2] Import bundled IDTA Submodel Templates (AAS1d).
     */
    async importAasIdtaTemplates(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AasIdtaImportResult> {
        const response = await this.importAasIdtaTemplatesRaw(initOverrides);
        return await response.value();
    }

}
