/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminMetricsSummary,
} from '../models/index';
import {
    AdminMetricsSummaryFromJSON,
    AdminMetricsSummaryToJSON,
} from '../models/index';

/**
 * 
 */
export class AdminMetricsApi extends runtime.BaseAPI {

    /**
     * Rolls up JVM heap / uptime / HTTP-request total + mean / permissions-cache hit ratio into one payload, read from the in-process Micrometer registry. Operator\'s browser never talks to Prometheus.
     * [v2] Instance-health summary for the admin pane.
     */
    async getMetricsSummaryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminMetricsSummary>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/admin/metrics-summary`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminMetricsSummaryFromJSON(jsonValue));
    }

    /**
     * Rolls up JVM heap / uptime / HTTP-request total + mean / permissions-cache hit ratio into one payload, read from the in-process Micrometer registry. Operator\'s browser never talks to Prometheus.
     * [v2] Instance-health summary for the admin pane.
     */
    async getMetricsSummary(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminMetricsSummary> {
        const response = await this.getMetricsSummaryRaw(initOverrides);
        return await response.value();
    }

}
