/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminOrcidPatchIO,
} from '../models/index';
import {
    AdminOrcidPatchIOFromJSON,
    AdminOrcidPatchIOToJSON,
} from '../models/index';

export interface PatchUserOrcidRequest {
    username: string;
    adminOrcidPatchIO: AdminOrcidPatchIO;
}

/**
 * 
 */
export class AdminUserORCIDPreseedApi extends runtime.BaseAPI {

    /**
     * Admin-only one-shot preseed for demo / migration scenarios. Passing null clears the orcid; a non-null value must be a valid ORCID (16 digits with mod 11-2 checksum) — same validation as the user\'s own self-PATCH. The target user must already exist (i.e. they have logged in at least once so the User node is minted).
     * [v2] Set or clear the ORCID id on another user\'s shepard record.
     */
    async patchUserOrcidRaw(requestParameters: PatchUserOrcidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling patchUserOrcid().'
            );
        }

        if (requestParameters['adminOrcidPatchIO'] == null) {
            throw new runtime.RequiredError(
                'adminOrcidPatchIO',
                'Required parameter "adminOrcidPatchIO" was null or undefined when calling patchUserOrcid().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/admin/users/{username}/orcid`.replace(`{${"username"}}`, encodeURIComponent(String(requestParameters['username']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AdminOrcidPatchIOToJSON(requestParameters['adminOrcidPatchIO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Admin-only one-shot preseed for demo / migration scenarios. Passing null clears the orcid; a non-null value must be a valid ORCID (16 digits with mod 11-2 checksum) — same validation as the user\'s own self-PATCH. The target user must already exist (i.e. they have logged in at least once so the User node is minted).
     * [v2] Set or clear the ORCID id on another user\'s shepard record.
     */
    async patchUserOrcid(requestParameters: PatchUserOrcidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.patchUserOrcidRaw(requestParameters, initOverrides);
    }

}
