/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CollectionWatcherIO,
} from '../models/index';
import {
    CollectionWatcherIOFromJSON,
    CollectionWatcherIOToJSON,
} from '../models/index';

export interface GetMyCollectionWatchRequest {
    collectionAppId: string;
}

export interface ListCollectionWatchesRequest {
    collectionAppId: string;
}

export interface UnwatchRequest {
    collectionAppId: string;
}

export interface WatchRequest {
    collectionAppId: string;
}

/**
 * 
 */
export class CollectionWatchesApi extends runtime.BaseAPI {

    /**
     * Returns 200 with the caller\'s watch record when they are subscribed to this Collection, or 404 when they are not. Use this endpoint to determine the initial state of the Watch button in the UI without fetching the full watcher list.  No Collection-level permission is required beyond authentication — any authenticated user can check their own watch status even for Collections they no longer have Read access to.
     * [v2] Check whether the caller is watching this Collection (CW1).
     */
    async getMyCollectionWatchRaw(requestParameters: GetMyCollectionWatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionWatcherIO>> {
        if (requestParameters['collectionAppId'] == null) {
            throw new runtime.RequiredError(
                'collectionAppId',
                'Required parameter "collectionAppId" was null or undefined when calling getMyCollectionWatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/collections/{collectionAppId}/watches/me`.replace(`{${"collectionAppId"}}`, encodeURIComponent(String(requestParameters['collectionAppId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionWatcherIOFromJSON(jsonValue));
    }

    /**
     * Returns 200 with the caller\'s watch record when they are subscribed to this Collection, or 404 when they are not. Use this endpoint to determine the initial state of the Watch button in the UI without fetching the full watcher list.  No Collection-level permission is required beyond authentication — any authenticated user can check their own watch status even for Collections they no longer have Read access to.
     * [v2] Check whether the caller is watching this Collection (CW1).
     */
    async getMyCollectionWatch(requestParameters: GetMyCollectionWatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionWatcherIO> {
        const response = await this.getMyCollectionWatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the complete list of users currently watching this Collection. Each item carries `username` and `since` (epoch millis when the watch was registered). The list is unordered and is not paginated — the number of watchers is expected to be small relative to the DataObject count.  Auth: Read permission on the Collection.
     * [v2] List all watchers for this Collection (CW1).
     */
    async listCollectionWatchesRaw(requestParameters: ListCollectionWatchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CollectionWatcherIO>>> {
        if (requestParameters['collectionAppId'] == null) {
            throw new runtime.RequiredError(
                'collectionAppId',
                'Required parameter "collectionAppId" was null or undefined when calling listCollectionWatches().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/collections/{collectionAppId}/watches`.replace(`{${"collectionAppId"}}`, encodeURIComponent(String(requestParameters['collectionAppId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CollectionWatcherIOFromJSON));
    }

    /**
     * Returns the complete list of users currently watching this Collection. Each item carries `username` and `since` (epoch millis when the watch was registered). The list is unordered and is not paginated — the number of watchers is expected to be small relative to the DataObject count.  Auth: Read permission on the Collection.
     * [v2] List all watchers for this Collection (CW1).
     */
    async listCollectionWatches(requestParameters: ListCollectionWatchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CollectionWatcherIO>> {
        const response = await this.listCollectionWatchesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unsubscribes the caller from notifications for this Collection. Idempotent: if the caller is not watching, 204 is returned without error.
     * [v2] Stop watching this Collection (CW1).
     */
    async unwatchRaw(requestParameters: UnwatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['collectionAppId'] == null) {
            throw new runtime.RequiredError(
                'collectionAppId',
                'Required parameter "collectionAppId" was null or undefined when calling unwatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/collections/{collectionAppId}/watches/me`.replace(`{${"collectionAppId"}}`, encodeURIComponent(String(requestParameters['collectionAppId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Unsubscribes the caller from notifications for this Collection. Idempotent: if the caller is not watching, 204 is returned without error.
     * [v2] Stop watching this Collection (CW1).
     */
    async unwatch(requestParameters: UnwatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.unwatchRaw(requestParameters, initOverrides);
    }

    /**
     * Subscribes the caller to notifications for this Collection. Idempotent: a second POST returns 200 carrying the existing record rather than erroring with 409.  Auth: Read permission on the Collection.
     * [v2] Start watching this Collection (CW1).
     */
    async watchRaw(requestParameters: WatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionWatcherIO>> {
        if (requestParameters['collectionAppId'] == null) {
            throw new runtime.RequiredError(
                'collectionAppId',
                'Required parameter "collectionAppId" was null or undefined when calling watch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/collections/{collectionAppId}/watches`.replace(`{${"collectionAppId"}}`, encodeURIComponent(String(requestParameters['collectionAppId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionWatcherIOFromJSON(jsonValue));
    }

    /**
     * Subscribes the caller to notifications for this Collection. Idempotent: a second POST returns 200 carrying the existing record rather than erroring with 409.  Auth: Read permission on the Collection.
     * [v2] Start watching this Collection (CW1).
     */
    async watch(requestParameters: WatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionWatcherIO> {
        const response = await this.watchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
