/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ImportJobRequestIO,
  ImportJobResultIO,
} from '../models/index';
import {
    ImportJobRequestIOFromJSON,
    ImportJobRequestIOToJSON,
    ImportJobResultIOFromJSON,
    ImportJobResultIOToJSON,
} from '../models/index';

export interface ExecuteImportRequest {
    importJobRequestIO: ImportJobRequestIO;
}

/**
 * 
 */
export class ImportJobsApi extends runtime.BaseAPI {

    /**
     * Consumes the commitId issued by POST /v2/import/validate and runs the import. Returns 201 on full success or 207 on partial failure (some entities failed to create). The commitId is one-shot — once executed (or attempted), the plan is marked USED. Returns 409 if the plan was already used, if a concurrent import is running, or if the collection changed since the plan was validated. Returns 410 if the plan expired (TTL 24 h) or is a pre-IMP2 plan (no stored manifest). Returns 422 if the plan was INVALIDATED (had hard validation errors).
     * [v2] Execute a validated import plan (IMP2)
     */
    async executeImportRaw(requestParameters: ExecuteImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportJobResultIO>> {
        if (requestParameters['importJobRequestIO'] == null) {
            throw new runtime.RequiredError(
                'importJobRequestIO',
                'Required parameter "importJobRequestIO" was null or undefined when calling executeImport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/import/jobs`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImportJobRequestIOToJSON(requestParameters['importJobRequestIO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportJobResultIOFromJSON(jsonValue));
    }

    /**
     * Consumes the commitId issued by POST /v2/import/validate and runs the import. Returns 201 on full success or 207 on partial failure (some entities failed to create). The commitId is one-shot — once executed (or attempted), the plan is marked USED. Returns 409 if the plan was already used, if a concurrent import is running, or if the collection changed since the plan was validated. Returns 410 if the plan expired (TTL 24 h) or is a pre-IMP2 plan (no stored manifest). Returns 422 if the plan was INVALIDATED (had hard validation errors).
     * [v2] Execute a validated import plan (IMP2)
     */
    async executeImport(requestParameters: ExecuteImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportJobResultIO> {
        const response = await this.executeImportRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
