/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LabJournalEntry,
  UpdateLabJournalRequest,
} from '../models/index';
import {
    LabJournalEntryFromJSON,
    LabJournalEntryToJSON,
    UpdateLabJournalRequestFromJSON,
    UpdateLabJournalRequestToJSON,
} from '../models/index';

export interface CreateLabJournalRequest {
    labJournalEntry: Omit<LabJournalEntry, 'dataObjectId'|'id'|'createdAt'|'createdBy'|'updatedAt'|'updatedBy'>;
    dataObjectId?: number;
}

export interface DeleteLabJournalRequest {
    labJournalEntryId: number;
}

export interface GetLabJournalByIdRequest {
    labJournalEntryId: number;
}

export interface GetLabJournalsByCollectionRequest {
    dataObjectId?: number;
}

export interface UpdateLabJournalOperationRequest {
    labJournalEntryId: number;
    updateLabJournalRequest: UpdateLabJournalRequest;
}

/**
 * 
 */
export class LabJournalEntryApi extends runtime.BaseAPI {

    /**
     * Create a lab journal in a data object
     */
    async createLabJournalRaw(requestParameters: CreateLabJournalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LabJournalEntry>> {
        if (requestParameters['labJournalEntry'] == null) {
            throw new runtime.RequiredError(
                'labJournalEntry',
                'Required parameter "labJournalEntry" was null or undefined when calling createLabJournal().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['dataObjectId'] != null) {
            queryParameters['dataObjectId'] = requestParameters['dataObjectId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/labJournalEntries`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LabJournalEntryToJSON(requestParameters['labJournalEntry']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LabJournalEntryFromJSON(jsonValue));
    }

    /**
     * Create a lab journal in a data object
     */
    async createLabJournal(requestParameters: CreateLabJournalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LabJournalEntry> {
        const response = await this.createLabJournalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a lab journal
     */
    async deleteLabJournalRaw(requestParameters: DeleteLabJournalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['labJournalEntryId'] == null) {
            throw new runtime.RequiredError(
                'labJournalEntryId',
                'Required parameter "labJournalEntryId" was null or undefined when calling deleteLabJournal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/labJournalEntries/{labJournalEntryId}`.replace(`{${"labJournalEntryId"}}`, encodeURIComponent(String(requestParameters['labJournalEntryId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a lab journal
     */
    async deleteLabJournal(requestParameters: DeleteLabJournalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteLabJournalRaw(requestParameters, initOverrides);
    }

    /**
     * Get a lab journal
     */
    async getLabJournalByIdRaw(requestParameters: GetLabJournalByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LabJournalEntry>> {
        if (requestParameters['labJournalEntryId'] == null) {
            throw new runtime.RequiredError(
                'labJournalEntryId',
                'Required parameter "labJournalEntryId" was null or undefined when calling getLabJournalById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/labJournalEntries/{labJournalEntryId}`.replace(`{${"labJournalEntryId"}}`, encodeURIComponent(String(requestParameters['labJournalEntryId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LabJournalEntryFromJSON(jsonValue));
    }

    /**
     * Get a lab journal
     */
    async getLabJournalById(requestParameters: GetLabJournalByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LabJournalEntry> {
        const response = await this.getLabJournalByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all lab journals in a data object
     */
    async getLabJournalsByCollectionRaw(requestParameters: GetLabJournalsByCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LabJournalEntry>>> {
        const queryParameters: any = {};

        if (requestParameters['dataObjectId'] != null) {
            queryParameters['dataObjectId'] = requestParameters['dataObjectId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/labJournalEntries`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LabJournalEntryFromJSON));
    }

    /**
     * Get all lab journals in a data object
     */
    async getLabJournalsByCollection(requestParameters: GetLabJournalsByCollectionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LabJournalEntry>> {
        const response = await this.getLabJournalsByCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a lab journal
     */
    async updateLabJournalRaw(requestParameters: UpdateLabJournalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LabJournalEntry>> {
        if (requestParameters['labJournalEntryId'] == null) {
            throw new runtime.RequiredError(
                'labJournalEntryId',
                'Required parameter "labJournalEntryId" was null or undefined when calling updateLabJournal().'
            );
        }

        if (requestParameters['updateLabJournalRequest'] == null) {
            throw new runtime.RequiredError(
                'updateLabJournalRequest',
                'Required parameter "updateLabJournalRequest" was null or undefined when calling updateLabJournal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/labJournalEntries/{labJournalEntryId}`.replace(`{${"labJournalEntryId"}}`, encodeURIComponent(String(requestParameters['labJournalEntryId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateLabJournalRequestToJSON(requestParameters['updateLabJournalRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LabJournalEntryFromJSON(jsonValue));
    }

    /**
     * Update a lab journal
     */
    async updateLabJournal(requestParameters: UpdateLabJournalOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LabJournalEntry> {
        const response = await this.updateLabJournalRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
