/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MigrationProgress,
} from '../models/index';
import {
    MigrationProgressFromJSON,
    MigrationProgressToJSON,
} from '../models/index';

export interface GetByContainerRequest {
    containerId: number;
}

/**
 * 
 */
export class MigrationApi extends runtime.BaseAPI {

    /**
     * Get progress for all migration tasks
     * [v1] Get All
     */
    async getAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MigrationProgress>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/temp/migrations/state`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MigrationProgressFromJSON));
    }

    /**
     * Get progress for all migration tasks
     * [v1] Get All
     */
    async getAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MigrationProgress>> {
        const response = await this.getAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get progress for a specific container migration
     * [v1] Get By Container
     */
    async getByContainerRaw(requestParameters: GetByContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MigrationProgress>> {
        if (requestParameters['containerId'] == null) {
            throw new runtime.RequiredError(
                'containerId',
                'Required parameter "containerId" was null or undefined when calling getByContainer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/temp/migrations/{containerId}`.replace(`{${"containerId"}}`, encodeURIComponent(String(requestParameters['containerId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MigrationProgressFromJSON(jsonValue));
    }

    /**
     * Get progress for a specific container migration
     * [v1] Get By Container
     */
    async getByContainer(requestParameters: GetByContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MigrationProgress> {
        const response = await this.getByContainerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
