/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface GetV1ShelfRequest {
    format?: string;
}

export interface GetV2ShelfRequest {
    format?: string;
}

/**
 * 
 */
export class OpenapiPerShelfApi extends runtime.BaseAPI {

    /**
     * OpenAPI document for the upstream-compatible /shepard/api/... shelf only.
     * [v1] Get V 1 Shelf
     */
    async getV1ShelfRaw(requestParameters: GetV1ShelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/shepard/doc/openapi/v1.json`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * OpenAPI document for the upstream-compatible /shepard/api/... shelf only.
     * [v1] Get V 1 Shelf
     */
    async getV1Shelf(requestParameters: GetV1ShelfRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getV1ShelfRaw(requestParameters, initOverrides);
    }

    /**
     * OpenAPI document for the /v2/... development shelf only. Paths under a disabled plugin/feature namespace (V2CONV-A5: e.g. /v2/aas/_* when the AAS plugin is disabled) are stripped so the spec reflects only enabled surfaces.
     * [v1] Get V 2 Shelf
     */
    async getV2ShelfRaw(requestParameters: GetV2ShelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/shepard/doc/openapi/v2.json`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * OpenAPI document for the /v2/... development shelf only. Paths under a disabled plugin/feature namespace (V2CONV-A5: e.g. /v2/aas/_* when the AAS plugin is disabled) are stripped so the spec reflects only enabled surfaces.
     * [v1] Get V 2 Shelf
     */
    async getV2Shelf(requestParameters: GetV2ShelfRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getV2ShelfRaw(requestParameters, initOverrides);
    }

}
