/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PagedResponse,
  Publication,
} from '../models/index';
import {
    PagedResponseFromJSON,
    PagedResponseToJSON,
    PublicationFromJSON,
    PublicationToJSON,
} from '../models/index';

export interface ListPublicationsRequest {
    appId: string;
    kind: string;
}

export interface ListPublicationsFlatRequest {
    entityAppId: string;
    page?: number;
    pageSize?: number;
}

export interface PublishRequest {
    appId: string;
    kind: string;
    force?: boolean;
}

export interface RetirePublicationRequest {
    appId: string;
    kind: string;
}

/**
 * 
 */
export class PublishApi extends runtime.BaseAPI {

    /**
     * Returns every :Publication row attached to the entity ordered by mintedAt DESC. Includes retired rows (digitalObjectMutability = \'retired\') so callers can render the full publication history. Clients wanting only active Publications should filter digitalObjectMutability != \'retired\' client-side. Auth: Read permission on the entity. No pagination — entities rarely have more than a handful of Publication rows.  DEPRECATED (APISIMP-PUBLICATIONS-KIND-PATH-SEGMENT): use the kind-agnostic alias GET /v2/publications?entityAppId={appId} instead — it does not require the caller to know the entity-kind URL segment. This path is kept for backward compatibility.
     * [v2] List Publications attached to an entity (most-recent first).
     * @deprecated
     */
    async listPublicationsRaw(requestParameters: ListPublicationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Publication>>> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling listPublications().'
            );
        }

        if (requestParameters['kind'] == null) {
            throw new runtime.RequiredError(
                'kind',
                'Required parameter "kind" was null or undefined when calling listPublications().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/{kind}/{appId}/publications`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters['appId']))).replace(`{${"kind"}}`, encodeURIComponent(String(requestParameters['kind']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PublicationFromJSON));
    }

    /**
     * Returns every :Publication row attached to the entity ordered by mintedAt DESC. Includes retired rows (digitalObjectMutability = \'retired\') so callers can render the full publication history. Clients wanting only active Publications should filter digitalObjectMutability != \'retired\' client-side. Auth: Read permission on the entity. No pagination — entities rarely have more than a handful of Publication rows.  DEPRECATED (APISIMP-PUBLICATIONS-KIND-PATH-SEGMENT): use the kind-agnostic alias GET /v2/publications?entityAppId={appId} instead — it does not require the caller to know the entity-kind URL segment. This path is kept for backward compatibility.
     * [v2] List Publications attached to an entity (most-recent first).
     * @deprecated
     */
    async listPublications(requestParameters: ListPublicationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Publication>> {
        const response = await this.listPublicationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the same list as GET /v2/{kind}/{appId}/publications without requiring the caller to know the entity-kind URL segment. Pass any publishable entity\'s appId; the server resolves the entity kind internally. Ordered mintedAt DESC (most-recent first). Includes retired rows (digitalObjectMutability = \'retired\'). Auth: Read permission on the entity.  Pagination: `page` (0-based, default 0) and `pageSize` (1–200, default 50). `X-Total-Count` header carries the total count before paging (kept during deprecation window).
     * [v2] List Publications by entityAppId (kind-agnostic).
     */
    async listPublicationsFlatRaw(requestParameters: ListPublicationsFlatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedResponse>> {
        if (requestParameters['entityAppId'] == null) {
            throw new runtime.RequiredError(
                'entityAppId',
                'Required parameter "entityAppId" was null or undefined when calling listPublicationsFlat().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['entityAppId'] != null) {
            queryParameters['entityAppId'] = requestParameters['entityAppId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/publications`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedResponseFromJSON(jsonValue));
    }

    /**
     * Returns the same list as GET /v2/{kind}/{appId}/publications without requiring the caller to know the entity-kind URL segment. Pass any publishable entity\'s appId; the server resolves the entity kind internally. Ordered mintedAt DESC (most-recent first). Includes retired rows (digitalObjectMutability = \'retired\'). Auth: Read permission on the entity.  Pagination: `page` (0-based, default 0) and `pageSize` (1–200, default 50). `X-Total-Count` header carries the total count before paging (kept during deprecation window).
     * [v2] List Publications by entityAppId (kind-agnostic).
     */
    async listPublicationsFlat(requestParameters: ListPublicationsFlatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedResponse> {
        const response = await this.listPublicationsFlatRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Idempotent on the first call: a re-POST without `?force=true` returns the existing Publication. With `?force=true`, a fresh PID is minted and attached as an additional row. The returned `resolverUrl` is the public `/v2/.well-known/kip/{pid-suffix}` URL clients use to dereference the PID at this shepard instance.
     * [v2] Publish an entity — mint a PID via the active Minter and attach a Publication row.
     */
    async publishRaw(requestParameters: PublishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Publication>> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling publish().'
            );
        }

        if (requestParameters['kind'] == null) {
            throw new runtime.RequiredError(
                'kind',
                'Required parameter "kind" was null or undefined when calling publish().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['force'] != null) {
            queryParameters['force'] = requestParameters['force'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/{kind}/{appId}/publish`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters['appId']))).replace(`{${"kind"}}`, encodeURIComponent(String(requestParameters['kind']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicationFromJSON(jsonValue));
    }

    /**
     * Idempotent on the first call: a re-POST without `?force=true` returns the existing Publication. With `?force=true`, a fresh PID is minted and attached as an additional row. The returned `resolverUrl` is the public `/v2/.well-known/kip/{pid-suffix}` URL clients use to dereference the PID at this shepard instance.
     * [v2] Publish an entity — mint a PID via the active Minter and attach a Publication row.
     */
    async publish(requestParameters: PublishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Publication> {
        const response = await this.publishRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sets `digitalObjectMutability = \'retired\'` on the most-recent `:Publication` row attached to the entity. The row is never deleted — KIP records are append-only per the HMC spec. Idempotent: retiring an already-retired Publication returns 204. Returns 404 when the entity has no Publication at all.
     * [v2] Retire a publication — mark the entity\'s most-recent :Publication as retired.
     */
    async retirePublicationRaw(requestParameters: RetirePublicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling retirePublication().'
            );
        }

        if (requestParameters['kind'] == null) {
            throw new runtime.RequiredError(
                'kind',
                'Required parameter "kind" was null or undefined when calling retirePublication().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/{kind}/{appId}/publish`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters['appId']))).replace(`{${"kind"}}`, encodeURIComponent(String(requestParameters['kind']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Sets `digitalObjectMutability = \'retired\'` on the most-recent `:Publication` row attached to the entity. The row is never deleted — KIP records are append-only per the HMC spec. Idempotent: retiring an already-retired Publication returns 204. Returns 404 when the entity has no Publication at all.
     * [v2] Retire a publication — mark the entity\'s most-recent :Publication as retired.
     */
    async retirePublication(requestParameters: RetirePublicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.retirePublicationRaw(requestParameters, initOverrides);
    }

}
