/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BasicReference,
  BasicReferenceAttributes,
} from '../models/index';
import {
    BasicReferenceFromJSON,
    BasicReferenceToJSON,
    BasicReferenceAttributesFromJSON,
    BasicReferenceAttributesToJSON,
} from '../models/index';

export interface DeleteBasicReferenceRequest {
    collectionId: number;
    dataObjectId: number;
    referenceId: number;
}

export interface GetAllReferencesRequest {
    collectionId: number;
    dataObjectId: number;
    name?: string;
    page?: number;
    size?: number;
    orderBy?: BasicReferenceAttributes;
    orderDesc?: boolean;
}

export interface GetBasicReferenceRequest {
    collectionId: number;
    dataObjectId: number;
    referenceId: number;
}

/**
 * 
 */
export class ReferenceApi extends runtime.BaseAPI {

    /**
     * Soft-deletes the reference identified by \'referenceId\' regardless of kind. The payload it points at (container, URI, etc.) is NOT deleted — only the reference edge. Returns 204 when removed (or already gone). Requires Write on the parent DataObject.
     * [v1] Delete any reference by id (polymorphic).
     */
    async deleteBasicReferenceRaw(requestParameters: DeleteBasicReferenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling deleteBasicReference().'
            );
        }

        if (requestParameters['dataObjectId'] == null) {
            throw new runtime.RequiredError(
                'dataObjectId',
                'Required parameter "dataObjectId" was null or undefined when calling deleteBasicReference().'
            );
        }

        if (requestParameters['referenceId'] == null) {
            throw new runtime.RequiredError(
                'referenceId',
                'Required parameter "referenceId" was null or undefined when calling deleteBasicReference().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/collections/{collectionId}/dataObjects/{dataObjectId}/references/{referenceId}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))).replace(`{${"dataObjectId"}}`, encodeURIComponent(String(requestParameters['dataObjectId']))).replace(`{${"referenceId"}}`, encodeURIComponent(String(requestParameters['referenceId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft-deletes the reference identified by \'referenceId\' regardless of kind. The payload it points at (container, URI, etc.) is NOT deleted — only the reference edge. Returns 204 when removed (or already gone). Requires Write on the parent DataObject.
     * [v1] Delete any reference by id (polymorphic).
     */
    async deleteBasicReference(requestParameters: DeleteBasicReferenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteBasicReferenceRaw(requestParameters, initOverrides);
    }

    /**
     * Returns the union of all reference kinds — Timeseries, File, StructuredData, URI, Git, DataObject, Collection — attached to the DataObject. Use the kind-specific endpoints (e.g. /timeseriesReferences) when you only want one kind. Pagination: \'page\' / \'size\'. Requires Read on the parent DataObject.
     * [v1] List all references on a DataObject (any kind).
     */
    async getAllReferencesRaw(requestParameters: GetAllReferencesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BasicReference>>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling getAllReferences().'
            );
        }

        if (requestParameters['dataObjectId'] == null) {
            throw new runtime.RequiredError(
                'dataObjectId',
                'Required parameter "dataObjectId" was null or undefined when calling getAllReferences().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['orderBy'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderDesc'] != null) {
            queryParameters['orderDesc'] = requestParameters['orderDesc'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/collections/{collectionId}/dataObjects/{dataObjectId}/references`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))).replace(`{${"dataObjectId"}}`, encodeURIComponent(String(requestParameters['dataObjectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BasicReferenceFromJSON));
    }

    /**
     * Returns the union of all reference kinds — Timeseries, File, StructuredData, URI, Git, DataObject, Collection — attached to the DataObject. Use the kind-specific endpoints (e.g. /timeseriesReferences) when you only want one kind. Pagination: \'page\' / \'size\'. Requires Read on the parent DataObject.
     * [v1] List all references on a DataObject (any kind).
     */
    async getAllReferences(requestParameters: GetAllReferencesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BasicReference>> {
        const response = await this.getAllReferencesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns one reference identified by \'referenceId\' regardless of kind. The response is the common BasicReference shape (id, name, description, attributes, createdBy/createdAt, …); kind-specific fields are returned by the kind-specific GET endpoints. Requires Read on the parent DataObject.
     * [v1] Get any reference by id (polymorphic).
     */
    async getBasicReferenceRaw(requestParameters: GetBasicReferenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BasicReference>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling getBasicReference().'
            );
        }

        if (requestParameters['dataObjectId'] == null) {
            throw new runtime.RequiredError(
                'dataObjectId',
                'Required parameter "dataObjectId" was null or undefined when calling getBasicReference().'
            );
        }

        if (requestParameters['referenceId'] == null) {
            throw new runtime.RequiredError(
                'referenceId',
                'Required parameter "referenceId" was null or undefined when calling getBasicReference().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // apikey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/collections/{collectionId}/dataObjects/{dataObjectId}/references/{referenceId}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))).replace(`{${"dataObjectId"}}`, encodeURIComponent(String(requestParameters['dataObjectId']))).replace(`{${"referenceId"}}`, encodeURIComponent(String(requestParameters['referenceId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BasicReferenceFromJSON(jsonValue));
    }

    /**
     * Returns one reference identified by \'referenceId\' regardless of kind. The response is the common BasicReference shape (id, name, description, attributes, createdBy/createdAt, …); kind-specific fields are returned by the kind-specific GET endpoints. Requires Read on the parent DataObject.
     * [v1] Get any reference by id (polymorphic).
     */
    async getBasicReference(requestParameters: GetBasicReferenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BasicReference> {
        const response = await this.getBasicReferenceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
