/* tslint:disable */
/* eslint-disable */
/**
 * shepard backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TimeseriesContainerChartViewIO,
} from '../models/index';
import {
    TimeseriesContainerChartViewIOFromJSON,
    TimeseriesContainerChartViewIOToJSON,
} from '../models/index';

export interface GetChartViewRequest {
    containerAppId: string;
}

export interface PatchChartViewRequest {
    containerAppId: string;
    timeseriesContainerChartViewIO: TimeseriesContainerChartViewIO;
}

/**
 * 
 */
export class TimeseriesContainerChartViewApi extends runtime.BaseAPI {

    /**
     * Returns the curated channel-selection list shared by all users viewing this container. An empty list (or no persisted view yet) means \"no curated view — show all channels\" (the frontend default).  Each entry in selectedChannels is a 5-tuple key `measurement|device|location|symbolicName|field` (pipe-separated).
     * [v2] Read the persisted chart-view configuration for this container.
     */
    async getChartViewRaw(requestParameters: GetChartViewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeseriesContainerChartViewIO>> {
        if (requestParameters['containerAppId'] == null) {
            throw new runtime.RequiredError(
                'containerAppId',
                'Required parameter "containerAppId" was null or undefined when calling getChartView().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/timeseries-containers/{containerAppId}/chart-view`.replace(`{${"containerAppId"}}`, encodeURIComponent(String(requestParameters['containerAppId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeseriesContainerChartViewIOFromJSON(jsonValue));
    }

    /**
     * Returns the curated channel-selection list shared by all users viewing this container. An empty list (or no persisted view yet) means \"no curated view — show all channels\" (the frontend default).  Each entry in selectedChannels is a 5-tuple key `measurement|device|location|symbolicName|field` (pipe-separated).
     * [v2] Read the persisted chart-view configuration for this container.
     */
    async getChartView(requestParameters: GetChartViewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeseriesContainerChartViewIO> {
        const response = await this.getChartViewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Replaces the persisted selectedChannels list. Mutation requires Write permission on the container — anyone who can upload data can also reshape what other users see in the Channel Overview chart. The mutation is captured in the audit trail (PROV1a).
     * [v2] RFC 7396 merge-patch the chart-view configuration.
     */
    async patchChartViewRaw(requestParameters: PatchChartViewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeseriesContainerChartViewIO>> {
        if (requestParameters['containerAppId'] == null) {
            throw new runtime.RequiredError(
                'containerAppId',
                'Required parameter "containerAppId" was null or undefined when calling patchChartView().'
            );
        }

        if (requestParameters['timeseriesContainerChartViewIO'] == null) {
            throw new runtime.RequiredError(
                'timeseriesContainerChartViewIO',
                'Required parameter "timeseriesContainerChartViewIO" was null or undefined when calling patchChartView().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v2/timeseries-containers/{containerAppId}/chart-view`.replace(`{${"containerAppId"}}`, encodeURIComponent(String(requestParameters['containerAppId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TimeseriesContainerChartViewIOToJSON(requestParameters['timeseriesContainerChartViewIO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeseriesContainerChartViewIOFromJSON(jsonValue));
    }

    /**
     * Replaces the persisted selectedChannels list. Mutation requires Write permission on the container — anyone who can upload data can also reshape what other users see in the Channel Overview chart. The mutation is captured in the audit trail (PROV1a).
     * [v2] RFC 7396 merge-patch the chart-view configuration.
     */
    async patchChartView(requestParameters: PatchChartViewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeseriesContainerChartViewIO> {
        const response = await this.patchChartViewRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
