"""Idempotent seeder for the MFFD RDK→URDF showcase.

Bootstraps a Collection on a running Shepard backend demonstrating the
end-to-end RDK→URDF pipeline shipped by URDF-WEBVIEW-1 (phase 1) and
RDK-PARSE-1:

  1. The real DLR MFZ.rdk RoboDK station file (12.1 MB at
     ``../mffd-showcase/raw-data/mffd-data/cell/MFZ.rdk``) is uploaded
     as a FileReference. The RDK-PARSE-1 plugin scrapes tier-1
     ``urn:shepard:rdk:*`` annotations on upload (appVersion, platform,
     programSource, robotController, apiEndpoint, cadRef×3, stepRef×2).

  2. A KUKA KR210 R2700/2 URDF + its 7 binary STL meshes are uploaded as
     FileReferences for provenance. (The runtime fetch path is
     ``/urdf-samples/kr210_r2700_2/...`` from the frontend public dir — see
     ``urdf/SOURCES.md``.)

  3. A synthetic 30-second 6-joint trajectory (generated by
     ``trajectory/generate.py``) lands as a TimeseriesReference. Each
     channel is annotated with ``urn:shepard:urdf:joint = <jointName>``
     per the URDF-WEBVIEW-1 contract — the UrdfChannelPicker uses this
     annotation for auto-preselection (the channel→joint binding
     becomes one-click instead of manual).

  4. A VIEW_RECIPE :ShepardTemplate is best-effort created pointing at
     the KR210 URDF + joint-channel map. (Requires the instance-admin
     role — when running as a regular user, the template step is
     skipped with a clear log line; users can still launch the URDF
     view directly via the shapes/render URL printed at the end.)

Usage
-----
    python3 seed.py --host https://shepard-api.nuclide.systems --apikey XXX
    python3 seed.py --host http://localhost:8080 --apikey XXX --reset

The seeder is idempotent — re-running it detects existing entities by
name and skips work that's already done. ``--reset`` deletes the
showcase Collection and shared containers first.

Engineering context
-------------------
This showcase routes around the missing ``RdkToUrdfExporter`` sidecar
(phase 2, queued — RoboDK SDK licence required) by sourcing the URDF
from the open-source kroshu/kuka_robot_descriptions package
(Apache-2.0) — the **real** KR210 R2700/2 model used in the MFFD AFP
cell (per ``examples/mffd-showcase/seed.py`` line 114). See
``SHOWCASE.md`` for the honest caveats: tier-1 scrape is metadata-only
(no kinematics); the trajectory is synthetic but joint-limit-respecting
and plausible.
"""
from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

import requests as _http

from shepard_client import (  # type: ignore
    ApiClient,
    Collection,
    CollectionApi,
    CollectionSearchBody,
    CollectionSearchParams,
    Configuration,
    ContainerType,
    DataObject,
    DataObjectApi,
    FileContainer,
    FileContainerApi,
    FileReference,
    FileReferenceApi,
    Permissions,
    PermissionType,
    SearchApi,
    Timeseries,
    TimeseriesContainer,
    TimeseriesContainerApi,
    TimeseriesDataPoint,
    TimeseriesReference,
    TimeseriesReferenceApi,
    TimeseriesWithDataPoints,
)

# ---------------------------------------------------------------------------
# Constants

COLLECTION_NAME = "MFFD RDK → URDF Viewer Showcase"
COLLECTION_DESCRIPTION = (
    "End-to-end demonstrator of the **RDK→URDF→animator** pipeline. "
    "Wires together: (a) the real DLR MFZ.rdk RoboDK station file "
    "(12.1 MB; uploaded as a FileReference so RDK-PARSE-1 scrapes tier-1 "
    "`urn:shepard:rdk:*` annotations automatically); (b) the **real** KUKA "
    "KR210 R2700/2 URDF + visual STL meshes sourced from the open-source "
    "kroshu/kuka_robot_descriptions package (Apache-2.0) — the actual "
    "MFFD AFP cell robot; (c) a synthetic 30-second 6-joint AFP-ply-layup "
    "trajectory with `urn:shepard:urdf:joint` annotations the "
    "UrdfChannelPicker auto-binds to. **Phase 2** (`RdkToUrdfExporter` "
    "sidecar — RoboDK SDK licence required) would re-derive the URDF "
    "from the RDK directly; queued in the URDF-WEBVIEW-1 backlog."
)

COLLECTION_ATTRIBUTES = {
    "topic": "RDK→URDF→animator end-to-end",
    "robot": "KUKA KR210 R2700/2 (MFFD AFP cell)",
    "url:urdf-samples": "/urdf-samples/kr210_r2700_2/kuka_quantec_support/urdf/kr210_r2700_2.urdf",
    "url:source-rdk": "examples/mffd-showcase/raw-data/mffd-data/cell/MFZ.rdk",
    "license:urdf": "Apache-2.0 (kroshu/kuka_robot_descriptions)",
    "phase": "1 (in-tree renderer); phase 2 RdkToUrdfExporter queued",
    "rdk-tier1-annotations": "8 predicates per RdkAnnotations.java",
}

# Shared containers
FC_RDK_NAME = "mffd-rdk-urdf-files"
TSC_NAME    = "mffd-rdk-urdf-trajectory"

# DataObject names
DO_RDK    = "MFFD AFP Cell — MFZ.rdk source"
DO_URDF   = "R10 (KR210 R2700/2) — kinematic model"
DO_TRAJ   = "AFP Ply 5 layup — joint trajectory"
DO_KRL    = "AFP Ply 5 layup — KRL program"

# URDF served from frontend public dir (relative to backend host)
URDF_PUBLIC_URL  = "/urdf-samples/kr210_r2700_2/kuka_quantec_support/urdf/kr210_r2700_2.urdf"
URDF_PACKAGE_DIR = "/urdf-samples/kr210_r2700_2"

# The 6 movable KR210 R2700/2 joints, in URDF declaration order.
JOINTS = ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6"]
URDF_JOINT_PREDICATE = "urn:shepard:urdf:joint"

# Timeseries chunk size for bulk upload
TIMESERIES_CHUNK = 1000

# Template
TEMPLATE_NAME = "MFFD RDK→URDF AFP Layup (KR210 R2700/2 + joint-trajectory)"
TEMPLATE_KIND = "VIEW_RECIPE"

# Paths in the seeder
SEED_DIR        = Path(__file__).parent
URDF_DIR        = SEED_DIR / "urdf"
TRAJECTORY_DIR  = SEED_DIR / "trajectory"
KRL_DIR         = SEED_DIR / "krl"
KRL_SRC_PATH    = KRL_DIR / "ply5_layup.src"
MFZ_RDK_PATH    = SEED_DIR.parent / "mffd-showcase" / "raw-data" / "mffd-data" / "cell" / "MFZ.rdk"
MESH_NAMES      = ["base_link.stl", "link_1.stl", "link_2.stl", "link_3.stl",
                   "link_4.stl", "link_5.stl", "link_6.stl"]
# Source the meshes from frontend/public so we read what we ship.
FE_MESH_DIR     = SEED_DIR.parent.parent / "frontend" / "public" / "urdf-samples" / "kr210_r2700_2" / "kuka_quantec_support" / "meshes" / "kr210_r2700_2" / "visual"


# ---------------------------------------------------------------------------
# Helpers

def _log(action: str, name: str, kind: str, ident: object = "") -> None:
    suffix = f", {ident}" if ident != "" else ""
    print(f"{action:<6} {name} ({kind}{suffix})", flush=True)


def _query(name: str) -> str:
    return f'{{"property":"name","value":"{name}","operator":"eq"}}'


def _v2_base(host: str) -> str:
    return re.sub(r"/shepard/api/?$", "/v2", host.rstrip("/"))


@dataclass
class Apis:
    client: ApiClient
    collection: CollectionApi
    data_object: DataObjectApi
    file_container: FileContainerApi
    file_reference: FileReferenceApi
    timeseries_container: TimeseriesContainerApi
    timeseries_reference: TimeseriesReferenceApi
    search: SearchApi


# ---------------------------------------------------------------------------
# Lookup helpers (mirror mffd-showcase/seed.py)

def _find_collection_by_name(apis: Apis, name: str) -> Collection | None:
    body = CollectionSearchBody(
        searchParams=CollectionSearchParams(query=_query(name))
    )
    res = apis.search.search_collections(body)
    for c in res.results or []:
        if c.name == name:
            return c
    return None


def _find_container(apis: Apis, name: str, ctype: ContainerType):
    from shepard_client import ContainerSearchBody, ContainerSearchParams
    body = ContainerSearchBody(
        searchParams=ContainerSearchParams(query=_query(name), queryType=ctype)
    )
    res = apis.search.search_containers(body)
    for c in res.results or []:
        if c.name == name:
            return c
    return None


def _find_data_object_by_name(apis: Apis, coll_id: int, name: str) -> DataObject | None:
    objs = apis.data_object.get_all_data_objects(coll_id) or []
    for o in objs:
        if o.name == name:
            return o
    return None


def _ensure_public(get_perms_fn, set_perms_fn, entity_id: int) -> None:
    try:
        perms: Permissions = get_perms_fn(entity_id)
    except Exception as e:
        _log("SKIP", f"ensure-public (entity_id={entity_id})", f"perms — ({str(e)[:60]})")
        return
    if perms.permission_type != PermissionType.PUBLIC:
        try:
            perms.permission_type = PermissionType.PUBLIC
            set_perms_fn(entity_id, perms)
        except Exception as e:
            _log("SKIP", f"set-public (entity_id={entity_id})", f"403 — ({str(e)[:60]})")


# ---------------------------------------------------------------------------
# Containers

def ensure_file_container(apis: Apis, name: str) -> FileContainer:
    existing = _find_container(apis, name, ContainerType.FILE)
    if existing is not None:
        _ensure_public(
            apis.file_container.get_file_permissions,
            apis.file_container.edit_file_permissions,
            existing.id,
        )
        _log("SKIP", name, "FileContainer", existing.id)
        return existing
    fc = FileContainer(name=name)
    fc = apis.file_container.create_file_container(fc)
    _ensure_public(
        apis.file_container.get_file_permissions,
        apis.file_container.edit_file_permissions,
        fc.id,
    )
    _log("OK", name, "FileContainer", fc.id)
    return fc


def ensure_timeseries_container(apis: Apis, name: str) -> TimeseriesContainer:
    existing = _find_container(apis, name, ContainerType.TIMESERIES)
    if existing is not None:
        _ensure_public(
            apis.timeseries_container.get_timeseries_permissions,
            apis.timeseries_container.edit_timeseries_permissions,
            existing.id,
        )
        _log("SKIP", name, "TimeseriesContainer", existing.id)
        return existing
    tsc = TimeseriesContainer(name=name)
    tsc = apis.timeseries_container.create_timeseries_container(tsc)
    _ensure_public(
        apis.timeseries_container.get_timeseries_permissions,
        apis.timeseries_container.edit_timeseries_permissions,
        tsc.id,
    )
    _log("OK", name, "TimeseriesContainer", tsc.id)
    return tsc


# ---------------------------------------------------------------------------
# Collection + DataObjects

def ensure_collection(apis: Apis) -> Collection:
    existing = _find_collection_by_name(apis, COLLECTION_NAME)
    if existing is not None:
        if (existing.description or "") != COLLECTION_DESCRIPTION:
            existing.description = COLLECTION_DESCRIPTION
            existing.attributes = COLLECTION_ATTRIBUTES
            existing = apis.collection.update_collection(existing.id, existing)
            _log("UPDATE", COLLECTION_NAME, "Collection", existing.id)
        else:
            _log("SKIP", COLLECTION_NAME, "Collection", existing.id)
        return existing
    coll = Collection(
        name=COLLECTION_NAME,
        description=COLLECTION_DESCRIPTION,
        attributes=COLLECTION_ATTRIBUTES,
    )
    coll = apis.collection.create_collection(coll)
    perms = apis.collection.get_collection_permissions(coll.id)
    perms.permission_type = PermissionType.PUBLIC
    apis.collection.edit_collection_permissions(coll.id, perms)
    _log("OK", COLLECTION_NAME, "Collection", coll.id)
    return coll


def ensure_data_object(apis: Apis, coll: Collection, name: str, description: str,
                       attributes: dict) -> DataObject:
    existing = _find_data_object_by_name(apis, coll.id, name)
    if existing is not None:
        _log("SKIP", name, "DataObject", existing.id)
        return existing
    do = DataObject(name=name, description=description, attributes=attributes)
    do = apis.data_object.create_data_object(coll.id, do)
    _log("OK", name, "DataObject", do.id)
    return do


# ---------------------------------------------------------------------------
# File upload (v2 presigned)

def _get_fc_app_id(host: str, api_key: str, fc_id: int) -> str:
    resp = _http.get(f"{host}/fileContainers/{fc_id}", headers={"X-API-KEY": api_key}, timeout=30)
    resp.raise_for_status()
    return resp.json()["appId"]


def _upload_file_presigned(v2_base: str, api_key: str, container_app_id: str,
                           path: Path, content_type: str) -> str:
    fname = path.name
    r1 = _http.post(
        f"{v2_base}/file-containers/{container_app_id}/upload-url",
        json={"fileName": fname},
        headers={"X-API-KEY": api_key},
        timeout=30,
    )
    r1.raise_for_status()
    d = r1.json()
    upload_url, oid = d["uploadUrl"], d["oid"]
    data = path.read_bytes()
    r2 = _http.put(upload_url, data=data, timeout=180,
                   headers={"Content-Disposition": f'attachment; filename="{fname}"'})
    r2.raise_for_status()
    r3 = _http.post(
        f"{v2_base}/file-containers/{container_app_id}/upload-url/commit",
        json={"oid": oid, "fileName": fname, "contentType": content_type, "fileSize": len(data)},
        headers={"X-API-KEY": api_key},
        timeout=30,
    )
    r3.raise_for_status()
    return oid


def _content_type_for(path: Path) -> str:
    n = path.name.lower()
    if n.endswith(".urdf") or n.endswith(".xml"):
        return "application/xml"
    if n.endswith(".dae"):
        return "model/vnd.collada+xml"
    if n.endswith(".stl"):
        return "model/stl"
    if n.endswith(".rdk"):
        # Tier-1 scraper sniffs the extension regardless of MIME.
        return "application/octet-stream"
    return "application/octet-stream"


def upload_file_reference(apis: Apis, coll: Collection, do: DataObject,
                          fc: FileContainer, file_path: Path,
                          ref_name: str) -> FileReference | None:
    """Upload a single file under one FileReference (FR1b: one FileRef per file)."""
    existing_refs = apis.file_reference.get_all_file_references(coll.id, do.id) or []
    for r in existing_refs:
        if r.name == ref_name:
            _log("SKIP", ref_name, "FileReference", r.id)
            return r

    if not file_path.exists():
        _log("SKIP", ref_name, f"FileReference (missing local file: {file_path})")
        return None

    host    = apis.client.configuration.host.rstrip("/")
    api_key = (apis.client.configuration.api_key or {}).get("apikey", "")
    v2      = _v2_base(host)
    fc_app  = _get_fc_app_id(host, api_key, fc.id)

    ctype = _content_type_for(file_path)
    oid = _upload_file_presigned(v2, api_key, fc_app, file_path, ctype)

    fr = FileReference(
        name=ref_name,
        dataObjectId=do.id,
        fileContainerId=fc.id,
        fileOids=[oid],
    )
    fr = apis.file_reference.create_file_reference(coll.id, do.id, fr)
    _log("OK", ref_name, "FileReference", fr.id)
    return fr


# ---------------------------------------------------------------------------
# Timeseries trajectory upload

def _read_csv_points(csv_path: Path) -> list[TimeseriesDataPoint]:
    out: list[TimeseriesDataPoint] = []
    with csv_path.open() as f:
        r = csv.reader(f)
        next(r, None)  # header
        for row in r:
            if not row:
                continue
            out.append(TimeseriesDataPoint(timestamp=int(row[0]), value=float(row[1])))
    return out


def _chunked(seq: list, size: int):
    for i in range(0, len(seq), size):
        yield seq[i: i + size]


def upload_joint_trajectory(apis: Apis, coll: Collection, do: DataObject,
                             tsc: TimeseriesContainer) -> TimeseriesReference | None:
    """Upload the 6 joint-angle CSVs into one TimeseriesReference."""
    ref_name = "afp-layup-joint-trajectory"
    existing_refs = apis.timeseries_reference.get_all_timeseries_references(coll.id, do.id) or []
    for r in existing_refs:
        if r.name == ref_name:
            _log("SKIP", ref_name, "TimeseriesReference", r.id)
            return r

    timeseries_in_do: list[Timeseries] = []
    t0_ns: int | None = None
    tn_ns: int | None = None

    for joint in JOINTS:
        csv_path = TRAJECTORY_DIR / f"{joint}.csv"
        if not csv_path.exists():
            _log("SKIP", joint, f"trajectory CSV missing: {csv_path}")
            continue
        points = _read_csv_points(csv_path)
        if not points:
            continue
        t0_ns = points[0].timestamp if t0_ns is None else min(t0_ns, points[0].timestamp)
        tn_ns = points[-1].timestamp if tn_ns is None else max(tn_ns, points[-1].timestamp)

        ts = Timeseries(
            measurement="mffd-urdf",
            device="KR210-R2700-2",
            location="ZLP-Augsburg",
            symbolicName=f"afp_layup_{joint}",
            field=joint,
        )
        chunks = list(_chunked(points, TIMESERIES_CHUNK))
        created = apis.timeseries_container.create_timeseries(
            timeseries_container_id=tsc.id,
            timeseries_with_data_points=TimeseriesWithDataPoints(
                timeseries=ts, points=chunks[0]
            ),
        )
        for extra in chunks[1:]:
            apis.timeseries_container.create_timeseries(
                timeseries_container_id=tsc.id,
                timeseries_with_data_points=TimeseriesWithDataPoints(
                    timeseries=Timeseries(
                        measurement=created.measurement,
                        device=created.device,
                        location=created.location,
                        symbolicName=created.symbolic_name,
                        field=joint,
                    ),
                    points=extra,
                ),
            )
        timeseries_in_do.append(created)
        _log("OK", joint, "channel uploaded", f"{len(points)} points")

    if not timeseries_in_do:
        return None

    tsr = TimeseriesReference(
        name=ref_name,
        start=t0_ns,
        end=tn_ns,
        timeseries=timeseries_in_do,
        timeseriesContainerId=tsc.id,
    )
    tsr = apis.timeseries_reference.create_timeseries_reference(coll.id, do.id, tsr)
    _log("OK", ref_name, "TimeseriesReference", tsr.id)
    return tsr


# ---------------------------------------------------------------------------
# Joint-channel annotations (urn:shepard:urdf:joint = <jointName>)

def annotate_joint_channels(host: str, api_key: str, container_id: int) -> None:
    """Write urn:shepard:urdf:joint annotations to each KR210 joint channel.

    Calls:
      GET  /v2/timeseries-containers/{containerId}/channels
      POST /v2/timeseries-containers/{containerId}/channels/{shepardId}/annotations

    This is what makes the UrdfChannelPicker auto-bind channels to URDF
    joints (annotation-driven preselection per URDF-WEBVIEW-1 §3 and the
    project_annotation_preselection_principle).
    """
    v2 = _v2_base(host)
    headers = {"X-API-KEY": api_key, "Content-Type": "application/json"}

    all_channels: list[dict] = []
    page = 0
    page_size = 200
    while True:
        resp = _http.get(
            f"{v2}/timeseries-containers/{container_id}/channels",
            params={"page": page, "size": page_size},
            headers=headers,
            timeout=30,
        )
        resp.raise_for_status()
        batch = resp.json()
        if not batch:
            break
        all_channels.extend(batch)
        if len(batch) < page_size:
            break
        page += 1

    annotated = 0
    for ch in all_channels:
        # Only annotate channels whose device matches our trajectory upload.
        if ch.get("device") != "KR210-R2700-2":
            continue
        shepard_id = ch.get("shepardId")
        field = ch.get("field", "")
        if not shepard_id or field not in JOINTS:
            continue
        # Annotation value = the joint name (matches the URDF joint declaration).
        resp = _http.post(
            f"{v2}/timeseries-containers/{container_id}/channels/{shepard_id}/annotations",
            json={"predicate": URDF_JOINT_PREDICATE, "value": field},
            headers=headers,
            timeout=30,
        )
        if resp.status_code in (200, 201):
            annotated += 1
        else:
            # Older instance — predicate may be inferred from endpoint context.
            # Try the v2 axis-roles shape (single `value` field).
            resp2 = _http.post(
                f"{v2}/timeseries-containers/{container_id}/channels/{shepard_id}/annotations",
                json={"value": field},
                headers=headers,
                timeout=30,
            )
            if resp2.status_code in (200, 201):
                annotated += 1
            else:
                _log("WARN", f"channel {shepard_id} field={field}",
                     "joint annotation", f"{resp.status_code}/{resp2.status_code}")

    _log("OK", f"container={container_id}", f"{URDF_JOINT_PREDICATE} annotations", annotated)


# ---------------------------------------------------------------------------
# VIEW_RECIPE template (best-effort — requires instance-admin role)

def _find_view_recipe_template(host: str, api_key: str, name: str) -> str | None:
    v2 = _v2_base(host)
    try:
        resp = _http.get(f"{v2}/templates", params={"kind": TEMPLATE_KIND},
                         headers={"X-API-KEY": api_key, "Accept": "application/json"},
                         timeout=15)
        if resp.status_code != 200:
            return None
        rows = resp.json() if isinstance(resp.json(), list) else resp.json().get("content", [])
        for t in rows:
            if isinstance(t, dict) and t.get("name") == name:
                return t.get("appId")
    except Exception:
        return None
    return None


def ensure_view_recipe_template(host: str, api_key: str, joint_channel_ids: dict[str, str]) -> str | None:
    """POST a VIEW_RECIPE template wiring the KR210 URDF + joint→channel map.

    Returns the template appId or None if creation failed (typically 403 —
    the endpoint requires instance-admin and most demo users aren't).
    """
    existing = _find_view_recipe_template(host, api_key, TEMPLATE_NAME)
    if existing:
        _log("SKIP", TEMPLATE_NAME, "ShepardTemplate", existing)
        return existing

    body = {
        "renderer":         "urdf",
        "view":             "URDF + joint-trajectory animator",
        "shape":            "http://semantics.dlr.de/shepard-ui/urdf#UrdfViewShape",
        "viewRecipeShape":  "http://semantics.dlr.de/shepard-ui/urdf#UrdfViewShape",
        "urdfUrl":          URDF_PUBLIC_URL,
        "packagePath":      URDF_PACKAGE_DIR,
        "jointChannelMap":  joint_channel_ids,  # jointName → channel shepardId
        "label":            "MFFD AFP Ply 5 layup (KR210 R2700/2)",
    }
    payload = {
        "name":         TEMPLATE_NAME,
        "templateKind": TEMPLATE_KIND,
        "body":         json.dumps(body),
        "description":  ("Drives UrdfView with the KR210 R2700/2 KUKA URDF "
                         "+ the AFP joint trajectory's 6 joint-angle channels. "
                         "Channel binding via the urn:shepard:urdf:joint annotation."),
        "tags":         ["mffd", "urdf", "kr210_r2700_2", "view-recipe", "afp"],
    }
    v2 = _v2_base(host)
    resp = _http.post(f"{v2}/templates", json=payload,
                      headers={"X-API-KEY": api_key, "Content-Type": "application/json"},
                      timeout=30)
    if resp.status_code in (200, 201):
        app_id = resp.json().get("appId")
        _log("OK", TEMPLATE_NAME, "ShepardTemplate", app_id)
        return app_id
    if resp.status_code in (401, 403):
        _log("SKIP", TEMPLATE_NAME,
             "ShepardTemplate (needs instance-admin — view still launchable via URL)",
             resp.status_code)
        return None
    _log("WARN", TEMPLATE_NAME, "ShepardTemplate POST failed",
         f"{resp.status_code}: {resp.text[:120]}")
    return None


# ---------------------------------------------------------------------------
# Lookup joint channel shepardIds after upload

def lookup_joint_channel_ids(host: str, api_key: str, container_id: int) -> dict[str, str]:
    """Return jointName → channel shepardId for the trajectory we just uploaded."""
    v2 = _v2_base(host)
    out: dict[str, str] = {}
    page = 0
    while True:
        resp = _http.get(
            f"{v2}/timeseries-containers/{container_id}/channels",
            params={"page": page, "size": 200},
            headers={"X-API-KEY": api_key, "Accept": "application/json"},
            timeout=30,
        )
        if resp.status_code != 200:
            break
        batch = resp.json()
        if not batch:
            break
        for ch in batch:
            if ch.get("device") != "KR210-R2700-2":
                continue
            field = ch.get("field")
            shepard_id = ch.get("shepardId")
            if field in JOINTS and shepard_id and field not in out:
                out[field] = shepard_id
        if len(batch) < 200:
            break
        page += 1
    return out


# ---------------------------------------------------------------------------
# Reset

def reset(apis: Apis) -> None:
    existing = _find_collection_by_name(apis, COLLECTION_NAME)
    if existing is None:
        _log("SKIP", COLLECTION_NAME, "Collection (no prior seed)")
    else:
        apis.collection.delete_collection(existing.id)
        _log("OK", COLLECTION_NAME, "Collection deleted", existing.id)
    for name, ctype, delete_fn in (
        (FC_RDK_NAME, ContainerType.FILE,       apis.file_container.delete_file_container),
        (TSC_NAME,    ContainerType.TIMESERIES, apis.timeseries_container.delete_timeseries_container),
    ):
        c = _find_container(apis, name, ctype)
        if c is None:
            _log("SKIP", name, f"{ctype} (no prior seed)")
            continue
        try:
            delete_fn(c.id)
            _log("OK", name, f"{ctype} deleted", c.id)
        except Exception as exc:
            _log("SKIP", name, f"delete failed: {str(exc)[:80]}")


# ---------------------------------------------------------------------------
# Main

def seed(apis: Apis) -> None:
    print("\n=== MFFD RDK→URDF Showcase Seed ===\n", flush=True)

    host    = apis.client.configuration.host.rstrip("/")
    api_key = apis.client.configuration.api_key.get("apikey", "")

    # Containers
    fc  = ensure_file_container(apis, FC_RDK_NAME)
    tsc = ensure_timeseries_container(apis, TSC_NAME)

    # Collection
    coll = ensure_collection(apis)

    # 1) MFZ.rdk DataObject + FileReference (RDK-PARSE-1 scrapes on upload)
    do_rdk = ensure_data_object(
        apis, coll, DO_RDK,
        "MFZ.rdk — the real DLR MFFD AFP cell RoboDK station file. "
        "On upload, the RDK-PARSE-1 plugin scrapes 8 tier-1 "
        "urn:shepard:rdk:* annotations from the file body — appVersion, "
        "platform, programSource, robotController, apiEndpoint, plus "
        "3x cadRef and 2x stepRef. The annotations are visible on this "
        "FileReference's detail panel.",
        {
            "kind": "RoboDK station",
            "source-path": str(MFZ_RDK_PATH),
            "parser": "RdkTextScrapeParser (tier-1, plugins/fileformat-robotics)",
            "expected-scrape": "8 urn:shepard:rdk:* predicates",
        },
    )
    print("\n--- Uploading MFZ.rdk (real DLR data, 12.1 MB) ---", flush=True)
    if not MFZ_RDK_PATH.exists():
        print(f"WARN: MFZ.rdk not found at {MFZ_RDK_PATH}", file=sys.stderr)
        print("      The RDK upload step is skipped. Mount the MFFD raw-data tree "
              "under examples/mffd-showcase/raw-data/ to enable it.", file=sys.stderr)
    upload_file_reference(apis, coll, do_rdk, fc, MFZ_RDK_PATH, "mfz-rdk-source")

    # 2) URDF DataObject + URDF + meshes
    do_urdf = ensure_data_object(
        apis, coll, DO_URDF,
        "KUKA KR210 R2700/2 URDF (kroshu/kuka_robot_descriptions, "
        "Apache-2.0). The real MFFD AFP cell robot — `kuka_quantec_support` "
        "support package, flattened from xacro. The 7 visual STL meshes "
        "are referenced via package:// paths and served from the frontend "
        "public dir at /urdf-samples/kr210_r2700_2/.",
        {
            "robot-family": "KUKA KR210 R2700/2",
            "represents":   "KUKA KR210 R2700/2 (MFFD AFP cell — real model)",
            "license":      "Apache-2.0 (kroshu/kuka_robot_descriptions)",
            "url:public":   URDF_PUBLIC_URL,
            "packagePath":  URDF_PACKAGE_DIR,
            "joint-count":  "6 revolute (joint_1 .. joint_6)",
        },
    )
    print("\n--- Uploading URDF + STL meshes (provenance copies) ---", flush=True)
    upload_file_reference(apis, coll, do_urdf, fc, URDF_DIR / "kr210_r2700_2.urdf", "kr210-r2700-urdf")
    for mesh in MESH_NAMES:
        upload_file_reference(
            apis, coll, do_urdf, fc, FE_MESH_DIR / mesh, f"kr210-r2700-mesh-{mesh}",
        )

    # 3) KRL program DataObject + .src FileReference
    #    This is the anchor for the "Run / preview" UI (KRL-INTERPRETER-06):
    #    operator opens the .src FileReference → button → modal picks the
    #    URDF (from do_urdf) + target DataObject (defaults to this one) +
    #    timeseries container → POST /v2/krl/interpret → trajectory + URDF
    #    animator playback. Sidecar must be up:
    #      COMPOSE_PROFILES=krl-interpreter docker compose ... up -d
    do_krl = ensure_data_object(
        apis, coll, DO_KRL,
        "Synthetic MFFD AFP Ply 5 layup KUKA Robot Language (.src) program. "
        "Exercises the KRL-INTERPRETER tier-1 parser surface: PTP + LIN "
        "motions, FOR loop unrolling, $BASE / $TOOL frame switching, frame "
        "literals, named E6POS targets. Click 'Run / preview' on the "
        "FileReference detail page to resolve against the KR210 URDF "
        "(do_urdf) and land a joint trajectory in this DataObject's "
        "TimeseriesContainer for URDF animator playback.",
        {
            "kind": "KUKA KRL program (.src)",
            "process": "AFP Ply 5 layup, 5-pass raster",
            "robot-family": "KUKA KR210 R2700/2 (MFFD AFP cell)",
            "parser-tier1": "PTP, LIN, FOR, $BASE, $TOOL, frame literals",
            "synthetic": "true — believable but not the real MFFD Ply 5 program",
            "requires-sidecar": "shepard-krl-interpreter:local (opt-in compose profile)",
        },
    )
    print("\n--- Uploading KRL .src program ---", flush=True)
    upload_file_reference(apis, coll, do_krl, fc, KRL_SRC_PATH, "ply5-layup-krl")

    # 4) Trajectory DataObject + TS channels
    do_traj = ensure_data_object(
        apis, coll, DO_TRAJ,
        "Synthetic 30-second AFP ply-layup joint trajectory at 100 Hz "
        "(3000 samples per joint × 6 joints = 18000 points). Generated by "
        "trajectory/generate.py (deterministic). Each channel is annotated "
        "with urn:shepard:urdf:joint = <jointName> — the UrdfChannelPicker "
        "auto-binds these for one-click playback through the KR210 URDF.",
        {
            "duration-s": "30",
            "sample-hz":  "100",
            "joint-count": "6",
            "joint-names": ",".join(JOINTS),
            "annotation": URDF_JOINT_PREDICATE,
            "synthetic":  "true — believable AFP raster sweep motion, not physically solved",
        },
    )
    print("\n--- Uploading joint trajectory (6 channels × 3000 points) ---", flush=True)
    tsr = upload_joint_trajectory(apis, coll, do_traj, tsc)

    # 4) Annotate joint channels with urn:shepard:urdf:joint
    print("\n--- Annotating joint channels ---", flush=True)
    annotate_joint_channels(host, api_key, tsc.id)

    # 5) VIEW_RECIPE template (best-effort)
    print("\n--- VIEW_RECIPE template ---", flush=True)
    joint_ids = lookup_joint_channel_ids(host, api_key, tsc.id)
    if not joint_ids:
        _log("SKIP", TEMPLATE_NAME, "ShepardTemplate (no joint channels resolved)")
    else:
        ensure_view_recipe_template(host, api_key, joint_ids)

    # Final summary + URLs
    print(f"\nDone. Collection id={coll.id}", flush=True)
    print("\n--- Click-walkthrough ---", flush=True)
    front_host = host.replace("shepard-api.", "shepard.").replace("/shepard/api", "")
    print(f"  Collection:    {front_host}/collections/{coll.id}", flush=True)
    print(f"  RDK DataObj:   {front_host}/collections/{coll.id}/dataobjects/{do_rdk.id}", flush=True)
    print(f"  URDF DataObj:  {front_host}/collections/{coll.id}/dataobjects/{do_urdf.id}", flush=True)
    print(f"  Trajectory:    {front_host}/collections/{coll.id}/dataobjects/{do_traj.id}", flush=True)
    print(f"  KRL program:   {front_host}/collections/{coll.id}/dataobjects/{do_krl.id}", flush=True)
    print(f"                 → open the .src FileReference → 'Run / preview' button", flush=True)
    print(f"  Static URDF:   {front_host}/shapes/render?renderer=urdf"
          f"&urdfUrl={URDF_PUBLIC_URL.replace('/', '%2F')}"
          f"&packagePath={URDF_PACKAGE_DIR.replace('/', '%2F')}", flush=True)


# ---------------------------------------------------------------------------
# CLI

def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(
        description="Idempotent seeder for the MFFD RDK→URDF showcase.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python3 seed.py --host https://shepard-api.nuclide.systems --apikey XXX\n"
            "  python3 seed.py --host http://localhost:8080 --apikey XXX --reset\n"
        ),
    )
    ap.add_argument("--host",   required=True, help="Shepard backend base URL")
    ap.add_argument("--apikey", required=True, help="API key with write access")
    ap.add_argument("--reset",  action="store_true", help="Delete prior collection + containers first")
    args = ap.parse_args(argv)

    cfg = Configuration(host=args.host, api_key={"apikey": args.apikey})
    client = ApiClient(configuration=cfg)
    apis = Apis(
        client=client,
        collection=CollectionApi(client),
        data_object=DataObjectApi(client),
        file_container=FileContainerApi(client),
        file_reference=FileReferenceApi(client),
        timeseries_container=TimeseriesContainerApi(client),
        timeseries_reference=TimeseriesReferenceApi(client),
        search=SearchApi(client),
    )

    if args.reset:
        print("=== RESET ===", flush=True)
        reset(apis)
        print(flush=True)

    seed(apis)


if __name__ == "__main__":
    main()
