services:
  neo4j:
    image: neo4j:5.24
    container_name: neo
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PW}
    ports:
      - "7474:7474"
      - "7687:7687"

  mongodb:
    image: mongo:8.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: shepard
      MONGO_INITDB_DATABASE: test

  timescaledb:
    image: timescale/timescaledb:2.26.3-pg16
    container_name: timescale
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: shepard
      POSTGRES_PASSWORD: shepard_secret
    ports:
      - "5432:5432"

  postgis:
    image: postgis/postgis:16-3.5
    container_name: postgis
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: shepard
      POSTGRES_PASSWORD: shepard_secret
    ports:
      - "5433:5432"
