# For commits on any branches
stages:
  - check
  - build
  - test

# include:
#   - local: .gitlab/ci/jobs/get-version-dev.yml
#   - local: .gitlab/ci/jobs/build-backend.yml
#   - local: .gitlab/ci/jobs/integration-test.yml
#- local: .gitlab/ci/jobs/secret-detection.yml
#- local: .gitlab/ci/jobs/dependency-scanning.yml
#- local: .gitlab/ci/jobs/format-prettier.yml
#- local: .gitlab/ci/jobs/check-scripts.yml

test_test:
  image: alpine:3.20
  stage: test
  needs: []
  variables:
    # Variables for Database Services
    NEO4J_AUTH: neo4j/shepard
    MONGO_INITDB_ROOT_USERNAME: mongo
    MONGO_INITDB_ROOT_PASSWORD: shepard
    MONGO_INITDB_DATABASE: test
    INFLUXDB_ADMIN_USER: influx
    INFLUXDB_ADMIN_PASSWORD: shepard

  services:
    - name: neo4j:5.24
      alias: neo4j
      entrypoint:
        - bash
        - -c
        - |
          ls -laF /builds/
          cp /builds/dlr-shepard/neo4j-docker-entrypoint.sh /usr/local/bin/neo4j-docker-entrypoint.sh
          chmod +x /usr/local/bin/neo4j-docker-entrypoint.sh
          /usr/local/bin/neo4j-docker-entrypoint.sh
  script:
    - cat /builds/dlr-shepard/shepard.tmp/CI_SERVER_TLS_CA_FILE
    - env

  artifacts:
    paths:
      - neo4j-docker-entrypoint.sh
    expire_in: 1 hour
