# For commits on any branches
stages:
  - check
  - build
  - test
  # TODO: Remove
  - upload

include:
  - local: .gitlab/ci/jobs/secret-detection.yml
  - local: .gitlab/ci/jobs/dependency-scanning.yml
  - local: .gitlab/ci/jobs/format-prettier.yml
  - local: .gitlab/ci/jobs/check-scripts.yml
  # TODO: Remove
  - local: .gitlab/ci/jobs/build-backend.yml
  - local: .gitlab/ci/jobs/build-clients-dev.yml
  - local: .gitlab/ci/jobs/compare-typescript-client-dev.yml
