stages:
  - check
  - build
  - test
  - upload

include:
  - local: .gitlab/ci/jobs/secret-detection.yml
  # use VERSION_NUMBER as a dev version number
  - local: .gitlab/ci/jobs/get-version-dev.yml
  - local: .gitlab/ci/jobs/dependency-scanning.yml
  - local: .gitlab/ci/jobs/format-prettier.yml
  - local: .gitlab/ci/jobs/check-scripts.yml
  - local: .gitlab/ci/jobs/check-schema-name.yml
  - local: .gitlab/ci/jobs/build-backend.yml
  - local: .gitlab/ci/jobs/unrequire-attributes-for-python.yml
  - local: .gitlab/ci/jobs/build-frontend.yml
  - local: .gitlab/ci/jobs/test-backend.yml
  - local: .gitlab/ci/jobs/coverage.yml
  - local: .gitlab/ci/jobs/integration-test.yml
  - local: .gitlab/ci/jobs/build-documentation.yml
  - local: .gitlab/ci/jobs/build-maven-report.yml
  - local: .gitlab/ci/jobs/openapi-diff.yml
    inputs:
      target_branch: main
  - local: .gitlab/ci/jobs/build-clients.yml
  - local: .gitlab/ci/jobs/upload-clients.yml
  - local: .gitlab/ci/jobs/clients-diff.yml
  - local: .gitlab/ci/jobs/diff-backend-client.yml
  - local: .gitlab/ci/jobs/upload-docker.yml
    inputs:
      image_name: frontend
  - local: .gitlab/ci/jobs/upload-docker.yml
    inputs:
      image_name: backend
