# For commits on feature branches and merge requests to develop branch
stages:
  - check
  - build
  - test

include:
  - local: .gitlab/ci/jobs/secret-detection.yml
  - local: .gitlab/ci/jobs/dependency-scanning.yml
  - local: .gitlab/ci/jobs/format-prettier.yml
  - local: .gitlab/ci/jobs/check-scripts.yml
  - local: .gitlab/ci/jobs/build-backend.yml
  - local: .gitlab/ci/jobs/build-frontend.yml
  - local: .gitlab/ci/jobs/test-backend.yml
  - local: .gitlab/ci/jobs/integration-test.yml
  - local: .gitlab/ci/jobs/coverage.yml
  - local: .gitlab/ci/jobs/openapi-diff.yml
    inputs:
      target_branch: develop
      artifact_job_name: build_backend
  # - local: .gitlab/ci/jobs/build-quarkend.yml
