stages:
  - check
  - build
  - test
  - upload

include:
  - local: .gitlab/ci/jobs/secret-detection.yml
  # use regular VERSION_NUMBER
  - local: .gitlab/ci/jobs/get-version.yml
  - local: .gitlab/ci/jobs/dependency-scanning.yml
  - local: .gitlab/ci/jobs/format-prettier.yml
  - local: .gitlab/ci/jobs/check-scripts.yml
  - local: .gitlab/ci/jobs/build-backend.yml
  - local: .gitlab/ci/jobs/build-frontend.yml
  - local: .gitlab/ci/jobs/test-backend.yml
  - local: .gitlab/ci/jobs/test-backend-with-databases.yml
  - local: .gitlab/ci/jobs/coverage.yml
  - local: .gitlab/ci/jobs/integration-test.yml
  - local: .gitlab/ci/jobs/build-documentation.yml
  - local: .gitlab/ci/jobs/build-maven-report.yml
  - local: .gitlab/ci/jobs/pages.yml
  - local: .gitlab/ci/jobs/build-clients.yml
  - local: .gitlab/ci/jobs/upload-clients.yml
  - local: .gitlab/ci/jobs/upload-docker.yml
    inputs:
      image_name: frontend
  - local: .gitlab/ci/jobs/upload-docker.yml
    inputs:
      image_name: backend
