stages:
  - tag

fetch_latest_tag:
  stage: tag
  script:
    - echo "Fetching the latest tag..."
    # - LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
    # - echo "The latest tag is: $LATEST_TAG"
    # - echo ${CI_COMMIT_TAG}
